<#
.SYNOPSIS
    Create config file to store required or optional parameters for executing EntraOps without end-user prompts.

.DESCRIPTION
    Creates a configuration file used by other cmdlets, for example to create the required app registration and grant permissions.
    Connect-EntraOps can also import the file so the same settings are available to interactive and automated runs.

.PARAMETER AuthenticationType
    Defines the authentication method used to request tokens for Microsoft Graph, Azure Resource Manager, and other APIs. Default is FederatedCredentials.

.PARAMETER UseInvokeRestMethodOnly
    Defines if all Invoke-EntraOps*Query cmdlets should use Invoke-RestMethod instead of the Microsoft Graph SDK (Invoke-MgGraphRequest). Default is false.
    In this mode the Microsoft Graph SDK is neither required nor installed; tokens are provided via Connect-EntraOps -MsGraphAccessToken or acquired with Get-AzAccessToken from the Az PowerShell context.
    Written as top-level setting "UseInvokeRestMethodOnly" to the config file and read by Connect-EntraOps; an explicit Connect-EntraOps -UseInvokeRestMethodOnly parameter wins over the config file.
    Note: REST-only parallel object resolution pre-warms a Graph token from the Az PowerShell context. If that token cannot be prepared, resolution falls back to sequential processing.

.PARAMETER IncludeObjectDetails
    Include display names, UPNs, and detailed object-specific errors in console output. Object IDs are always
    shown. Written as ConsoleOutput.IncludeObjectDetails and disabled by default for automation-log privacy.

.PARAMETER DevOpsPlatform
    Defines the platform where the EntraOps repository is hosted. Supported values are GitHub, AzureDevOps and None.
    Default is GitHub.

.PARAMETER ConfigFilePath
    Location of the config file which will be created. Default is ./EntraOpsConfig.json.

.PARAMETER IngestToLogAnalytics
    Defines if the classification data should be ingested to Log Analytics or Microsoft Sentinel Workspace. Default is false.

.PARAMETER IngestToWatchLists
    Defines if the classification data should be ingested to Microsoft Sentinel WatchLists. Default is false.

.PARAMETER ApplyAutomatedControlPlaneScopeUpdate
    Defines whether role-assignment scopes containing Control Plane assets should be updated before privileges are analyzed. Default is false.
    You are able to customize in the config file the data source ("EntraOps", "PrivilegedRolesFromAzGraph", "PrivilegedEdgesFromExposureManagement") and which criticality level or role definition/scope level should be considered.

.PARAMETER ClassificationParameterScope
    Array of RBAC systems whose classification parameter files are (re)generated by Update-EntraOpsClassificationControlPlaneScope, written to the config file as AutomatedControlPlaneScopeUpdate.ClassificationParameterScope. Default is all supported RBAC systems ("Azure", "EntraID", "IdentityGovernance", "ResourceApps", "DeviceManagement", "Defender").
    This is distinct from EntraOpsScopes (RbacSystems parameter/AutomatedControlPlaneScopeUpdate.EntraOpsScopes in the config file), which selects which RBAC systems' already-classified EAM export data is read as input to discover privileged objects. ClassificationParameterScope instead selects which RBAC systems' classification template/parameter files are written as output during that same run.

.PARAMETER ApplyAutomatedClassificationUpdate
    Defines whether classification templates should be updated from "https://github.com/Cloud-Architekt/AzurePrivilegedIAM" before privileges are analyzed. Default is false.
    You are able to define which classification files should be updated in the config file later.

.PARAMETER ApplyAutomatedEntraOpsUpdate
    Defines whether the Update-EntraOps workflow and its weekly schedule are enabled. Default is false.
    Workflow definitions are excluded from the default automated target set because GITHUB_TOKEN cannot
    publish changes below .github/workflows. Update them interactively with Update-EntraOps, or explicitly
    add the workflow target after configuring the documented EntraOps update publisher GitHub App.
    When enabled with the default PullRequest publication mode, the repository setting
    "Allow GitHub Actions to create and approve pull requests" (Settings > Actions > General >
    Workflow permissions) must be turned on, otherwise pull request creation fails.

.PARAMETER UpdateRepository
    Repository name below the Cloud-Architekt organization that serves EntraOps updates. Default is
    "EntraOps" (public release channel, no credentials). "EntraOps-Insiders" is the private preview
    channel and requires the EntraOpsUpdatePat repository secret. Both are declared in the local
    EntraOpsUpdateContract.json; another repository is accepted only when it publishes a matching contract.

.PARAMETER ValidationFrequency
    Controls candidate validation in the Update-EntraOps workflow. OnChange (default) validates new
    source commits and validation-setting changes, Always validates every workflow run, and Never
    applies changed candidates without executing their validation suite.

.PARAMETER RunBrowserTests
    Defines whether update-candidate validation includes the Playwright documentation and report tests.
    Default is true. This setting has no effect when ValidationFrequency is Never.

.PARAMETER UpdatePublicationMode
    Controls how the Update-EntraOps workflow publishes an applied candidate. PullRequest (default)
    creates or updates a review branch and pull request; DirectPush commits to the current branch.

.PARAMETER ApplyPrivilegedElmCatalogProtection
    Defines if Entitlement Management catalogs with Control Plane scope should be updated to privileged catalogs (Update-EntraOpsPrivilegedUnprotectedElmCatalog) as part of the push pipeline. Default is false.
    Caution: Enabling this setting requires the elevated Microsoft Graph permission "EntitlementManagement.ReadWrite.All" which will be assigned by New-EntraOpsWorkloadIdentity only if this setting is enabled.

.PARAMETER IncludeUnprotectedDevices
    Defines if devices owned by or associated with privileged users should be added to the same tier's unprotected-objects Restricted Management Administrative Unit when they are not already protected by another RMAU. Default is false.

.PARAMETER RemovalSafetyThreshold
    Safety brake for every automated cmdlet that removes protections from classified EAM data (Conditional Access target groups, Administrative Units, Restricted Management AUs including devices, and Entitlement Management catalog privilege levels). The value is the fraction (0..1) of a target's currently protected members/objects that a single run may remove. Each target plans all eligible removals before mutation; when the plan exceeds Ceiling(current count x threshold), no removals are applied to that target, a SafetyAbort is recorded, and the command fails after its summary. Non-destructive additions or protection operations may still proceed. Example with the default 0.5: a CA group with 20 current members permits at most 10 removals; a plan for 11 aborts before group removals begin. Setting the value to 1.0 permits removal of the complete current protected set and therefore disables threshold-based SafetyAbort protection for automated runs. After reviewing the reported plan, run the affected cmdlet manually with -ForceRemovalBeyondSafetyThreshold to apply an intentional oversized reconciliation. The force switch is deliberately not configurable because bypassing the brake must remain an explicit invocation-time decision. Written to all four mutation sections of the config file. Default is 0.5.

.PARAMETER ClassifyConstrainedDelegationAlwaysAsControlPlane
    Defines if Azure RBAC role assignments with an authorization/role assignment ABAC condition (constrained delegation) should always be classified as Control Plane instead of being dynamically downgraded based on the scope and the role definitions allowed by the condition. Default is false (dynamic downgrade).

.PARAMETER UnresolvedRoleDefinitionFallbackTier
    Tier assigned to Azure RBAC role assignments whose role definition could not be resolved from Azure Resource Graph (e.g. ARG replication lag for a new custom role, deleted role definition or a transient ARG failure). Allowed values: "Unclassified" (default, consistent with the Unclassified fallback of the other RBAC systems), "ManagementPlane" or "ControlPlane" (stricter fail-closed tiers) or "None" (skip classification).

.PARAMETER DeletedPrincipalAssignmentHandling
    Controls Azure RBAC assignments whose principal is confirmed deleted by HTTP 404 responses from both Microsoft Graph identity endpoints. "Filter" (default) removes it from Azure EAM output; "Keep" preserves the unresolved assignment. Other resolution failures are never filtered.

.PARAMETER ApplyAutomatedReportingGeneration
    Defines if the EntraOps Reporting static web apps (Classification Explorer, Tier Breach Analyzer, EAM Dashboard and Access Path Map) should be regenerated automatically by the Push-EntraOpsPrivilegedReporting workflow. Default is false.
    The generated report is uploaded as a downloadable workflow artifact; it is not committed back to the repository.
    The trigger for this workflow is controlled by the config file's `WorkflowTrigger` section: by default (`PushReportingAfterPullWorkflowTrigger` set to `true`) it runs right after every successful Pull-EntraOpsPrivilegedEAM run. It can additionally/alternatively be run on a recurring schedule by enabling `PushReportingScheduledTrigger` and customizing the cron expression in `PushReportingScheduledCron` (default is weekly, every Monday at 09:00 UTC). Disable both settings to only allow manual (`workflow_dispatch`) runs.

.PARAMETER PublishReportsAsRelease
    Publishes generated reports as GitHub Releases in addition to the 30-day workflow artifact. Disabled by default because each release contains a full tenant-data snapshot.

.PARAMETER ReportingReleasesToKeep
    Number of `reporting-*` GitHub Releases to retain when release publishing is enabled. Default is 10.
    Accepts 1 to 1000, so a generated configuration always prunes. Turning pruning off is deliberately not
    offered here because every retained release holds a full tenant-data snapshot; set
    `AutomatedReportingGeneration.ReportingReleasesToKeep` to an empty value in the Configuration Wizard or
    directly in the configuration file if unbounded retention is really intended.

.PARAMETER AccessPathMapResolveObjectIdsOutsidePrivilegedEAM
    Defines if New-EntraOpsAccessPathMapData should resolve edge endpoints that reference an object id outside the Privileged EAM export (e.g. a standard, non-privileged work account or a group/application owned by a privileged principal - referenced via OwnedObjects, Owners, AssociatedPawDevice or AssociatedWorkAccount) via Microsoft Graph to their display name and object type, instead of showing them as an anonymous "unresolved" placeholder node in Access Path Map. Default is true.
    Requires an active Microsoft Graph connection with at least directory read permissions (User.Read.All, Group.Read.All, Application.Read.All or Directory.Read.All) when generating the Access Path Map data.

.PARAMETER EamDashboardResolveLinkedIdentityObjectIds
    Defines if New-EntraOpsPrivilegedEamDashboardData should resolve linked identity object IDs outside the Privileged EAM export to display names through Microsoft Graph. Default is true.
    Requires an active Microsoft Graph connection with directory read permissions when generating EAM Dashboard data.

.PARAMETER ClassificationExplorerGenerateChangeHistory
    Defines if New-EntraOpsClassificationExplorerData should derive the classification change history
    from the source repository's git log. Default is false because the derivation requires a full
    AzurePrivilegedIAM checkout and is rarely needed in deployment reporting. Written as
    ClassificationExplorer.GenerateChangeHistory; a missing configuration file or setting also skips
    history generation.

.PARAMETER ResolveGroupMembersForPrivilegedAssets
    Defines if Configuration Analyzer should resolve included Conditional Access and authentication
    method policy target groups through PIM-aware transitive membership. Default is true.

.PARAMETER AllowPartialTenantGovernanceSnapshot
    Defines if the Push-EntraOpsPrivilegedReporting workflow should generate Configuration Analyzer
    data from a partially successful Tenant Governance snapshot. Failed resource types remain marked
    as stale in the report. Default is true.

.PARAMETER PimRequestFlowExcludedRiskFlags
    Array of PIM Request Flow risk-flag IDs to exclude from the generated report. Default is empty,
    so every supported risk flag is reported. Use the Configuration Wizard to select flags by name.

.PARAMETER EnableAlternateObjectTierLevelAttributes
    Defines if User and ServicePrincipal objects should be classified by PowerShell filter expressions evaluated against their own resolved EntraOps details (section AlternateObjectTierLevelAttributes) instead of Custom Security Attributes. Default is false. The config file always includes the section with empty filter expressions so it can be filled in and enabled later; see README.md "Classify privileged objects by Alternate Tier Level Attributes" for the required syntax. Group objects don't support Custom Security Attributes; the 'Group' filter expressions of this section classify groups whenever at least one is set, independent of this switch.    

.PARAMETER EnableTenantGovernanceSnapshot
    Defines if the EntraOps Tenant Governance Snapshot feature is enabled. Default is false.
When enabled, run New-EntraOpsWorkloadIdentity afterwards to grant the workload identity the required "ConfigurationMonitoring.ReadWrite.All" Microsoft Graph permission, and to configure the read permissions of the first-party "Microsoft Tenant Configuration Management" (UTCM) service principal for the resources configured in `TenantGovernanceSnapshot.ResourcesToInclude`.
    Snapshots are captured by Save-EntraOpsTenantGovernanceSnapshotJson (and the Pull-EntraOpsTenantGovernance workflow) and stored as per-resource files under `TenantGovernance/Snapshots`; historical versions are tracked via Git history.
    Reference: https://learn.microsoft.com/en-us/graph/utcm-entra-resources

.PARAMETER TenantGovernanceResourcesToInclude
    Array of Microsoft Entra resource types (e.g. "microsoft.entra.conditionalAccessPolicy") to capture in each Tenant Governance snapshot. Defaults to the recommended tenant governance resource set.

.PARAMETER TenantGovernanceSnapshotScheduledCron
    Cron expression for the "start" scheduled trigger of the Pull-EntraOpsTenantGovernance workflow,
    which creates the snapshot job without waiting for it to complete. Default is daily at 06:00 UTC ("0 6 * * *").

.PARAMETER TenantGovernanceSnapshotScheduledCronComplete
    Cron expression for the first "collect" trigger of the Pull-EntraOpsTenantGovernance workflow,
    which checks the pending snapshot job once without polling. Default is daily at 07:00 UTC.

.PARAMETER TenantGovernanceSnapshotScheduledCronCompleteRetry1
    Cron expression for the first collection retry. Default is daily at 07:30 UTC.

.PARAMETER TenantGovernanceSnapshotScheduledCronCompleteRetry2
    Cron expression for the final collection retry. Default is daily at 08:00 UTC.

.PARAMETER TenantGovernanceSnapshotResourceFileNaming
    Controls the file name used for each persisted Tenant Governance snapshot resource file. "ResourceId"
    (default) names files after the immutable resource Id; "DisplayName" produces readable paths but changes
    them on rename. Resource-ID naming falls back to a display-name path for singleton types without an Id.

.EXAMPLE
    Create a configuration file in the default location, update classification files before analyzing privileges, and enable both Log Analytics and Sentinel WatchList ingestion.
    New-EntraOpsConfigFile -TenantName "contoso.onmicrosoft.com" -ApplyAutomatedControlPlaneScopeUpdate $true -IngestToLogAnalytics $true -IngestToWatchLists $true -ApplyAutomatedClassificationUpdate $true

.EXAMPLE
    Create environment file for Azure DevOps deployment with core monitoring only.
    New-EntraOpsConfigFile -TenantName "contoso.onmicrosoft.com" -DevOpsPlatform "AzureDevOps" -ApplyAutomatedClassificationUpdate $true
 #>

function New-EntraOpsConfigFile {

    [CmdletBinding()]
    param (
        [parameter(Mandatory = $true)]
        [string]$TenantName,

        [parameter(Mandatory = $false)]
        [string]$ManagingTenantName = "",        

        [parameter(Mandatory = $false)]
        [string]$ManagingTenantId = "",

        [Parameter(Mandatory = $false)]
        [ValidateSet('UserInteractive', 'SystemAssignedMSI', 'UserAssignedMSI', 'FederatedCredentials', 'AlreadyAuthenticated', 'DeviceAuthentication')]
        [string]$AuthenticationType = "FederatedCredentials",

        [Parameter(Mandatory = $false)]
        [boolean]$UseInvokeRestMethodOnly = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$IncludeObjectDetails = $false,

        [Parameter(Mandatory = $false)]
        [ValidateSet('AzureDevOps', 'GitHub', 'None')]
        [string]$DevOpsPlatform = "GitHub",

        [Parameter(Mandatory = $false)]
        [ValidateScript({ Test-Path (Split-Path $_ -Parent) })]
        [string]$ConfigFilePath = "$EntraOpsBasefolder/EntraOpsConfig.json",

        [Parameter(Mandatory = $false)]
        [boolean]$IngestToLogAnalytics = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$IngestToWatchLists = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$ApplyAutomatedControlPlaneScopeUpdate = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$ApplyAutomatedClassificationUpdate = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$FailOnContradictoryTierPair = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$FailOnPrivilegedAssignmentWithoutClassification = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$ApplyAutomatedEntraOpsUpdate = $false,

        [Parameter(Mandatory = $false)]
        [ValidatePattern('^[A-Za-z0-9_.-]+$')]
        [string]$UpdateRepository = 'EntraOps',

        [Parameter(Mandatory = $false)]
        [ValidateSet('OnChange', 'Always', 'Never')]
        [string]$ValidationFrequency = 'OnChange',

        [Parameter(Mandatory = $false)]
        [boolean]$RunBrowserTests = $true,

        [Parameter(Mandatory = $false)]
        [ValidateSet('PullRequest', 'DirectPush')]
        [string]$UpdatePublicationMode = 'PullRequest',

        [Parameter(Mandatory = $false)]
        [boolean]$ApplyConditionalAccessTargetGroups = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$ApplyAdministrativeUnitAssignments = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$ApplyRmauAssignmentsForUnprotectedObjects = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$IncludeUnprotectedDevices = $false,

        [Parameter(Mandatory = $false)]
        [ValidateRange(0, 1)]
        [double]$RemovalSafetyThreshold = 0.5,

        [Parameter(Mandatory = $false)]
        [boolean]$ApplyPrivilegedElmCatalogProtection = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$ClassifyConstrainedDelegationAlwaysAsControlPlane = $false,

        [Parameter(Mandatory = $false)]
        [ValidateSet("Unclassified", "ManagementPlane", "ControlPlane", "None")]
        [string]$UnresolvedRoleDefinitionFallbackTier = "Unclassified",

        [Parameter(Mandatory = $false)]
        [ValidateSet("Keep", "Filter")]
        [string]$DeletedPrincipalAssignmentHandling = "Filter",

        [Parameter(Mandatory = $false)]
        [boolean]$ApplyAutomatedReportingGeneration = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$PublishReportsAsRelease = $false,

        [Parameter(Mandatory = $false)]
        [ValidateRange(1, 1000)]
        [int]$ReportingReleasesToKeep = 10,

        [Parameter(Mandatory = $false)]
        [boolean]$EnablePrivilegeHistory = $true,

        [Parameter(Mandatory = $false)]
        [Nullable[int]]$PrivilegeHistoryTimeRangeInDays = $null,

        [Parameter(Mandatory = $false)]
        [string]$PrivilegeHistorySnapshotInterval = "P2W",

        [Parameter(Mandatory = $false)]
        [boolean]$AccessPathMapResolveObjectIdsOutsidePrivilegedEAM = $true,

        [Parameter(Mandatory = $false)]
        [boolean]$EamDashboardResolveLinkedIdentityObjectIds = $true,

        [Parameter(Mandatory = $false)]
        [boolean]$ClassificationExplorerGenerateChangeHistory = $false,

        [Parameter(Mandatory = $false)]
        [boolean]$ResolveGroupMembersForPrivilegedAssets = $true,

        [Parameter(Mandatory = $false)]
        [boolean]$AllowPartialTenantGovernanceSnapshot = $true,

        [Parameter(Mandatory = $false)]
        [ValidateSet('noMfaActivation', 'noApprovalActivation', 'approverNotEnforced', 'approverLowerTier', 'authContextMissing', 'permanentEligible', 'permanentActive', 'noMfaActiveAssign')]
        [string[]]$PimRequestFlowExcludedRiskFlags = @(),

        [Parameter(Mandatory = $false)]
        [ValidateSet('noApproval', 'broadRequestor', 'approverLowerTier', 'assignedMorePrivileged')]
        [string[]]$AccessPackageFlowExcludedRiskFlags = @(),

        [Parameter(Mandatory = $false)]
        [ValidateSet('policyNotEnforced', 'legacyAuthentication', 'allUserMfa', 'privilegedRoleControls', 'riskBasedPolicies', 'deviceControls', 'guestCoverage', 'clientAppCoverage', 'exclusionSurface')]
        [string[]]$ConditionalAccessAnalysisExcludedFindings = @(),

        [Parameter(Mandatory = $false)]
        [string[]]$EidscaExcludedFindings = @(),

        [Parameter(Mandatory = $false)]
        [boolean]$EnableAlternateObjectTierLevelAttributes = $false,        

        [Parameter(Mandatory = $false)]
        [boolean]$EnableTenantGovernanceSnapshot = $false,

        [Parameter(Mandatory = $false)]
        [Array]$TenantGovernanceResourcesToInclude,

        [Parameter(Mandatory = $false)]
        [string]$TenantGovernanceSnapshotScheduledCron = "0 6 * * *",

        [Parameter(Mandatory = $false)]
        [string]$TenantGovernanceSnapshotScheduledCronComplete = "0 7 * * *",

        [Parameter(Mandatory = $false)]
        [string]$TenantGovernanceSnapshotScheduledCronCompleteRetry1 = "30 7 * * *",

        [Parameter(Mandatory = $false)]
        [string]$TenantGovernanceSnapshotScheduledCronCompleteRetry2 = "0 8 * * *",

        [Parameter(Mandatory = $false)]
        [ValidateSet("DisplayName", "ResourceId")]
        [string]$TenantGovernanceSnapshotResourceFileNaming = "ResourceId",

        [Parameter(Mandatory = $false)]
        [ValidateSet("Azure", "EntraID", "IdentityGovernance", "DeviceManagement", "ResourceApps", "Defender")]
        [Array]$RbacSystems = ("Azure", "EntraID", "IdentityGovernance", "ResourceApps", "DeviceManagement"),

        [Parameter(Mandatory = $false)]
        [ValidateSet("Azure", "EntraID", "IdentityGovernance", "DeviceManagement", "ResourceApps", "Defender")]
        [Array]$ClassificationParameterScope = ("Azure", "EntraID", "IdentityGovernance", "ResourceApps", "DeviceManagement", "Defender"),

        [Parameter(Mandatory = $false)]
        [ValidateSet("None", "All", "VIPUsers", "HighValueAssets", "IdentityCorrelation")]
        [Array]$WatchListTemplates = "None",

        [Parameter(Mandatory = $false)]
        [ValidateSet("ManagedIdentityAssignedResourceId", "All", "WorkloadIdentityAttackPaths", "WorkloadIdentityInfo", "WorkloadIdentityRecommendations")]
        [Array]$WatchListWorkloadIdentity = "None"
    )

    $ErrorActionPreference = "Stop"

    #region Connect to Azure Resource Manager
    # Get TenantId
    try {
        $TenantId = (Invoke-RestMethod -Uri ("https://login.windows.net/$($TenantName)/.well-known/openid-configuration")).token_endpoint.split('/')[3]
    } catch {
        Write-Error "Can't find tenant with name $TenantName. Error: $_"
    }

    Write-Output "Connect to Azure Resource Manager..."
    $AzContext = Get-AzContext
    if ($AzContext.Tenant.Id -ne $TenantId) {
        Write-Verbose "Call Connect-AzAccount to $($TenantId)..."
        Connect-AzAccount -TenantId $TenantId
    } else {
        Write-Verbose "Already connected to $($AzContext.Tenant.Id)"
    }

    try {
        $TenantDetails = Get-AzTenant -TenantId $TenantId
    } catch {
        Write-Error "Failed to get Tenant details for TenantId $TenantId. Error: $_"
    }
    #endregion

    #region Create configuration file schema with default values
    $DefaultUpdateTargets = if ($DevOpsPlatform -eq 'AzureDevOps') {
        @("./.azure-pipelines", "./Docs", "./EntraOps", "./Parsers", "./Queries", "./Reports", "./Samples", "./Tests", "./Workbooks", "./package.json", "./package-lock.json", "./playwright.config.mjs", "./CHANGELOG.md", "./EntraOpsUpdateContract.json")
    } else {
        @("./.github/actions", "./.github/agents", "./.github/scripts", "./Docs", "./EntraOps", "./Parsers", "./Queries", "./Reports", "./Samples", "./Tests", "./Workbooks", "./package.json", "./package-lock.json", "./playwright.config.mjs", "./CHANGELOG.md", "./EntraOpsUpdateContract.json")
    }
    $DefaultUpdatePublicationMode = if ($DevOpsPlatform -eq 'AzureDevOps' -and -not $PSBoundParameters.ContainsKey('UpdatePublicationMode')) {
        'DirectPush'
    } else {
        $UpdatePublicationMode
    }

    $EnvConfigSchema = [ordered]@{
        TenantId                                      = $($TenantId)
        TenantName                                    = $($TenantDetails.Domains[0])
        ManagingTenantId                              = $($ManagingTenantId)
        ManagingTenantName                            = $($ManagingTenantName)
        AuthenticationType                            = $($AuthenticationType)
        UseInvokeRestMethodOnly                       = $UseInvokeRestMethodOnly
        ConsoleOutput                                 = [ordered]@{
            IncludeObjectDetails = $IncludeObjectDetails
        }
        ClientId                                      = "Use New-EntraOpsWorkloadIdentity to create a new App Registration or enter here manually"
        DevOpsPlatform                                = $($DevOpsPlatform)
        RbacSystems                                   = $($RbacSystems)
        AzureRbacClassification                       = [ordered]@{
            ClassifyConstrainedDelegationAlwaysAsControlPlane = $ClassifyConstrainedDelegationAlwaysAsControlPlane
            UnresolvedRoleDefinitionFallbackTier              = $UnresolvedRoleDefinitionFallbackTier
            DeletedPrincipalAssignmentHandling                = $DeletedPrincipalAssignmentHandling
        }
        WorkflowTrigger                               = [ordered]@{
            PullScheduledTrigger                  = $true
            PullScheduledCron                     = "30 9 * * *"
            PushAfterPullWorkflowTrigger          = $true
            PushReportingAfterPullWorkflowTrigger = $true
            PushReportingScheduledTrigger         = $false
            PushReportingScheduledCron            = "0 9 * * 1"
        }
        AutomatedControlPlaneScopeUpdate              = [ordered]@{
            ApplyAutomatedControlPlaneScopeUpdate = $ApplyAutomatedControlPlaneScopeUpdate
            PrivilegedObjectClassificationSource  = ("EntraOps", "PrivilegedRolesFromAzGraph", "PrivilegedEdgesFromExposureManagement")
            EntraOpsScopes                        = @($RbacSystems)
            ClassificationParameterScope          = $($ClassificationParameterScope)
            AzureHighPrivilegedRoles              = ("Owner", "Role Based Access Control Administrator", "User Access Administrator")
            AzureHighPrivilegedScopes             = ("/", "/providers/microsoft.management/managementgroups/$($TenantId)")
            ExposureCriticalityLevel              = "<1"
        }
        AutomatedClassificationUpdate                 = [ordered]@{
            ApplyAutomatedClassificationUpdate = $ApplyAutomatedClassificationUpdate
            Classifications                    = ("All")
        }
        GeneratedArtifactValidation                   = [ordered]@{
            # Contradictory tier pairs come from Custom Security Attribute drift on the source object,
            # so they are reported as warnings by default instead of blocking the whole collection run.
            FailOnContradictoryTierPair                     = $FailOnContradictoryTierPair
            FailOnPrivilegedAssignmentWithoutClassification = $FailOnPrivilegedAssignmentWithoutClassification
        }
        AutomatedEntraOpsUpdate                       = [ordered]@{
            ApplyAutomatedEntraOpsUpdate = $ApplyAutomatedEntraOpsUpdate
            UpdateScheduledTrigger       = $ApplyAutomatedEntraOpsUpdate
            UpdateScheduledCron          = "0 9 * * 3"
            ValidationFrequency          = $ValidationFrequency
            RunBrowserTests              = $RunBrowserTests
            # Distribution repositories are declared once in EntraOpsUpdateContract.json: "EntraOps"
            # (public release channel, no credentials) or "EntraOps-Insiders" (private, requires the
            # EntraOpsUpdatePat secret). A different source is accepted only when it publishes a
            # matching EntraOpsUpdateContract.json.
            Repository                   = $UpdateRepository
            # Track main by default so enabled automated updates require no release-ref maintenance.
            Branch                       = "main"
            # GitHub workflow definitions are intentionally opt-in because GITHUB_TOKEN cannot push
            # them. Azure DevOps configurations instead include their pipeline templates by default.
            TargetUpdateFolders          = $DefaultUpdateTargets
            PublicationMode              = $DefaultUpdatePublicationMode
        }
        LogAnalytics                                  = [ordered]@{
            IngestToLogAnalytics             = $IngestToLogAnalytics
            DataCollectionRuleName           = "Enter Data Collection Rule Name and run New-EntraOpsWorkloadIdentity to assign permissions"
            DataCollectionRuleSubscriptionId = "Enter Subscription Id of Data Collection Rule and run New-EntraOpsWorkloadIdentity to assign permissions"
            DataCollectionResourceGroupName  = "Enter Resource Group Name of Data Collection Rule and run New-EntraOpsWorkloadIdentity to assign permissions"
            TableName                        = "PrivilegedEAM_CL"
        }
        SentinelWatchLists                            = [ordered]@{
            IngestToWatchLists        = $IngestToWatchLists
            WatchListTemplates        = $WatchListTemplates
            WatchListWorkloadIdentity = $WatchListWorkloadIdentity
            SentinelWorkspaceName     = "Enter Log Analytics Workspace Name and run New-EntraOpsWorkloadIdentity to assign permissions"
            SentinelSubscriptionId    = "Enter Subscription Id of Log Analytics Workspace and run New-EntraOpsWorkloadIdentity to assign permissions"
            SentinelResourceGroupName = "Enter Resource Group of Log Analytics Workspace and run New-EntraOpsWorkloadIdentity to assign permissions"
            WatchListPrefix           = "EntraOps_"
        }        
        AutomatedAdministrativeUnitManagement         = [ordered]@{
            ApplyAdministrativeUnitAssignments = $ApplyAdministrativeUnitAssignments
            ApplyToAccessTierLevel             = ("ControlPlane", "ManagementPlane")
            FilterObjectType                   = ("User", "Group")
            RbacSystems                        = ("EntraID", "IdentityGovernance", "ResourceApps", "DeviceManagement")
            RestrictedAuMode                   = "selected"
            RemovalSafetyThreshold             = $RemovalSafetyThreshold
        }
        AutomatedConditionalAccessTargetGroups        = [ordered]@{
            ApplyConditionalAccessTargetGroups = $ApplyConditionalAccessTargetGroups
            AdminUnitName                      = "Tier0-ControlPlane.ConditionalAccess"
            ApplyToAccessTierLevel             = ("ControlPlane", "ManagementPlane")
            FilterObjectType                   = ("User", "Group")
            GroupPrefix                        = "sug_Entra.CA.IncludeUsers.PrivilegedAccounts."
            RbacSystems                        = ("EntraID", "IdentityGovernance", "ResourceApps", "DeviceManagement")
            RemovalSafetyThreshold             = $RemovalSafetyThreshold
        }
        AutomatedRmauAssignmentsForUnprotectedObjects = [ordered]@{
            ApplyRmauAssignmentsForUnprotectedObjects = $ApplyRmauAssignmentsForUnprotectedObjects
            ApplyToAccessTierLevel                    = ("ControlPlane", "ManagementPlane")
            FilterObjectType                          = ("User", "Group")
            RbacSystems                               = ("EntraID", "IdentityGovernance", "DeviceManagement")
            IncludeUnprotectedDevices                 = $IncludeUnprotectedDevices
            RemovalSafetyThreshold                    = $RemovalSafetyThreshold
        }
        AutomatedReportingGeneration                  = [ordered]@{
            ApplyAutomatedReportingGeneration = $ApplyAutomatedReportingGeneration
            PublishReportsAsRelease           = $PublishReportsAsRelease
            ReportingReleasesToKeep           = $ReportingReleasesToKeep
            GenerateClassificationExplorer    = $true
            GenerateTierBreachAnalyzer        = $true
            GenerateEamDashboard              = $true
            GenerateAccessPathMap             = $true
            GenerateConfigurationAnalyzer     = $true
            GenerateAccessPackageFlow         = $true
            GeneratePrivilegeHistory          = $true
            ClassificationExplorerRepository  = "Cloud-Architekt/AzurePrivilegedIAM"
        }
        ConfigurationAnalyzer                         = [ordered]@{
            ResolveGroupMembersForPrivilegedAssets    = $ResolveGroupMembersForPrivilegedAssets
            AllowPartialTenantGovernanceSnapshot      = $AllowPartialTenantGovernanceSnapshot
            PimRequestFlowExcludedRiskFlags           = @($PimRequestFlowExcludedRiskFlags)
            AccessPackageFlowExcludedRiskFlags        = @($AccessPackageFlowExcludedRiskFlags)
            ConditionalAccessAnalysisExcludedFindings = @($ConditionalAccessAnalysisExcludedFindings)
            EidscaExcludedFindings                    = @($EidscaExcludedFindings)
        }
        AutomatedElmCatalogProtection                 = [ordered]@{
            ApplyPrivilegedElmCatalogProtection = $ApplyPrivilegedElmCatalogProtection
            ApplyToAccessTierLevel              = , "ControlPlane"
            RemovalSafetyThreshold              = $RemovalSafetyThreshold
        }
        CustomSecurityAttributes                      = [ordered]@{
            PrivilegedUserAttribute                               = "privilegedUser"
            PrivilegedUserPawAttribute                            = "associatedSecureAdminWorkstation"
            PrivilegedServicePrincipalAttribute                   = "privilegedWorkloadIdentity"
            UserWorkAccountAttribute                              = "associatedWorkAccount"
            PrivilegedUserAdminTierLevelAttribute                 = "adminTierLevel"
            PrivilegedUserAdminTierLevelNameAttribute             = "adminTierLevelName"
            PrivilegedServicePrincipalAdminTierLevelAttribute     = "adminTierLevel"
            PrivilegedServicePrincipalAdminTierLevelNameAttribute = "adminTierLevelName"
        }
        AlternateObjectTierLevelAttributes            = [ordered]@{
            Enabled          = $EnableAlternateObjectTierLevelAttributes
            User             = [ordered]@{
                ControlPlane    = ""
                ManagementPlane = ""
                UserAccess      = ""
            }
            ServicePrincipal = [ordered]@{
                ControlPlane    = ""
                ManagementPlane = ""
                UserAccess      = ""
            }
            Group            = [ordered]@{
                ControlPlane    = ""
                ManagementPlane = ""
                UserAccess      = ""
            }
        }
        PrivilegeHistory                              = [ordered]@{
            EnablePrivilegeHistory = $EnablePrivilegeHistory
            TimeRangeInDays        = $PrivilegeHistoryTimeRangeInDays
            SnapshotInterval       = $PrivilegeHistorySnapshotInterval
        }
        AccessPathMap                                 = [ordered]@{
            ResolveObjectIdsOutsidePrivilegedEAM = $AccessPathMapResolveObjectIdsOutsidePrivilegedEAM
        }
        EamDashboard                                  = [ordered]@{
            ResolveLinkedIdentityObjectIds = $EamDashboardResolveLinkedIdentityObjectIds
        }
        ClassificationExplorer                        = [ordered]@{
            GenerateChangeHistory = $ClassificationExplorerGenerateChangeHistory
        }
        TenantGovernanceSnapshot                      = [ordered]@{
            EnableTenantGovernanceSnapshot      = $EnableTenantGovernanceSnapshot
            ResourcesToInclude                  = if ($TenantGovernanceResourcesToInclude) { $TenantGovernanceResourcesToInclude } else { (Get-EntraOpsTenantGovernanceResourceDefinition).DefaultResources }
            SnapshotDisplayNamePrefix           = "EntraOps TG"
            SnapshotResourceFileNaming          = $TenantGovernanceSnapshotResourceFileNaming
            SnapshotScheduledTrigger            = $EnableTenantGovernanceSnapshot
            SnapshotScheduledCron               = $TenantGovernanceSnapshotScheduledCron
            SnapshotScheduledCronComplete       = $TenantGovernanceSnapshotScheduledCronComplete
            SnapshotScheduledCronCompleteRetry1 = $TenantGovernanceSnapshotScheduledCronCompleteRetry1
            SnapshotScheduledCronCompleteRetry2 = $TenantGovernanceSnapshotScheduledCronCompleteRetry2
        }
        ServiceEM                                     = [ordered]@{
            GovernanceModel                  = "Centralized"
            ControlPlaneDelegationGroupId    = ""
            ControlPlaneGroupName            = "PRG-Tenant-ControlPlane-IdentityOps"
            ManagementPlaneDelegationGroupId = ""
            ManagementPlaneGroupName         = "PRG-Tenant-ManagementPlane-PlatformOps"
            AdministratorGroupId             = ""
            DefaultAzureRegion               = ""
            SkipCatalogOwnerAssignment       = $false
            CreateM365Group                  = $false
            AddWorkloadPlaneAdminToUsers     = $false
            GroupPrefix                      = "SG"
            ConstrainedDelegation            = [ordered]@{
                ManagementPlane = [ordered]@{
                    ExcludedRoleDefinitionIds = @(
                        "8e3af657-a8ff-443c-a75c-2fe8c4bcb635"  # Owner
                        "18d7d88d-d35e-4fb5-a5c3-7773c20a72d9"  # User Access Administrator
                        "f58310d9-a9f6-439a-9e8d-f62e7b41a168"  # Role Based Access Control Administrator
                    )
                    AllowedTargetGroupFilter  = "WorkloadPlane-Admins"
                }
                WorkloadPlane   = [ordered]@{
                    AllowedRoleDefinitionIds = @(
                        # Key Vault roles
                        "00482a5a-887f-4fb3-b363-3b7fe8e74483"  # Key Vault Administrator
                        "a4417e6f-fecd-4de8-b567-7b0420556985"  # Key Vault Certificates Officer
                        "14b46e9e-c2b7-41b4-b07b-48a6ebf60603"  # Key Vault Crypto Officer
                        "12338af0-0e69-4776-bea7-57ae8d297424"  # Key Vault Crypto User
                        "21090545-7ca7-4776-b22c-e363652d74d2"  # Key Vault Reader
                        "b86a8fe4-44ce-4948-aee5-eccb2c155cd7"  # Key Vault Secrets Officer
                        "4633458b-17de-408a-b874-0445c86b69e6"  # Key Vault Secrets User
                        # Storage roles
                        "ba92f5b4-2d11-453d-a403-e96b0029c9fe"  # Storage Blob Data Contributor
                        "b7e6dc6d-f1e8-4753-8033-0f276bb0955b"  # Storage Blob Data Owner
                        "2a2b9908-6ea1-4ae2-8e65-a410df84e7d1"  # Storage Blob Data Reader
                        "0a9a7e1f-b9d0-4cc4-a60d-0319b160aaa3"  # Storage Table Data Contributor
                        "76199698-9eea-4c19-bc75-cec21354c6b6"  # Storage Table Data Reader
                        "974c5e8b-45b9-4653-ba55-5f855dd0fb88"  # Storage Queue Data Contributor
                        "19e7f393-937e-4f77-808e-94535e297925"  # Storage Queue Data Reader
                        "8a0f0c08-91a1-4084-bc3d-661d67233fed"  # Storage Queue Data Message Processor
                        "c6a89b2d-59bc-44d0-9896-0f6e12d7b80a"  # Storage Queue Data Message Sender
                    )
                    AllowedTargetGroupFilter = "WorkloadPlane-Users"
                }
            }
            PIMAuthenticationContext         = [ordered]@{
                EnableAuthenticationContext = $false
                ControlPlane                = [ordered]@{
                    AuthenticationContextClassReferenceId = ""
                    AuthenticationContextDisplayName      = ""
                }
                ManagementPlane             = [ordered]@{
                    AuthenticationContextClassReferenceId = ""
                    AuthenticationContextDisplayName      = ""
                }
                WorkloadPlane               = [ordered]@{
                    AuthenticationContextClassReferenceId = ""
                    AuthenticationContextDisplayName      = ""
                }
            }
            PIMForGroups                     = [ordered]@{
                MaximumActivationDuration       = "PT10H"
                MaximumActiveAssignmentDuration = "P15D"
            }
            AssignmentPolicies               = [ordered]@{
                BaselinePolicy              = [ordered]@{ Expiration = "P365D"; ApprovalTimeout = "P2D"; AllowExtension = $true }
                WorkloadPlaneUsers          = [ordered]@{ Expiration = "P365D"; ApprovalTimeout = "P2D"; RequestorScope = "AllMemberUsers"; AllowExtension = $true }
                WorkloadPlaneAdmins         = [ordered]@{ Expiration = "P365D"; ApprovalTimeout = "P2D"; AllowExtension = $true }
                ManagementPlaneAdmins       = [ordered]@{ Expiration = "P365D"; ApprovalTimeout = "P1D"; AllowExtension = $true }
                InitialWorkloadMembership   = [ordered]@{ Expiration = "P365D" }
                InitialManagementMembership = [ordered]@{ Expiration = "P365D"; ApprovalTimeout = "P2D" }
                InitialManagementAdmins     = [ordered]@{ Expiration = "P365D" }
                InitialWorkloadUsers        = [ordered]@{ Expiration = "P365D" }
                InitialWorkloadAdmins       = [ordered]@{ Expiration = "P365D" }
            }
            AccessReviews                    = [ordered]@{
                EnableAccessReviews        = $true
                RecurrenceIntervalInMonths = 3
                StartAfterDays             = 4
                ReviewDuration             = "P25D"
                Policies                   = [ordered]@{
                    BaselinePolicy              = [ordered]@{ ReviewerType = "Group"; Reviewers = @("ManagementPlane-Admins") }
                    WorkloadPlaneUsers          = [ordered]@{ ReviewerType = "Group"; Reviewers = @("WorkloadPlane-Admins") }
                    WorkloadPlaneAdmins         = [ordered]@{ ReviewerType = "Group"; Reviewers = @("ManagementPlane-Admins") }
                    ManagementPlaneAdmins       = [ordered]@{ ReviewerType = "Group"; Reviewers = @("ManagementPlane-Admins") }
                    InitialWorkloadMembership   = [ordered]@{ ReviewerType = "Group"; Reviewers = @("ManagementPlane-Admins") }
                    InitialManagementMembership = [ordered]@{ ReviewerType = "Group"; Reviewers = @("ManagementPlane-Admins") }
                    InitialManagementAdmins     = [ordered]@{ ReviewerType = "Group"; Reviewers = @("ManagementPlane-Admins") }
                    InitialWorkloadUsers        = [ordered]@{ ReviewerType = "Group"; Reviewers = @("WorkloadPlane-Admins") }
                    InitialWorkloadAdmins       = [ordered]@{ ReviewerType = "Group"; Reviewers = @("ManagementPlane-Admins") }
                }
            }
        }
    }
    #endregion

    #region Write configuration file to disk
    try {
        Write-Output "Writing configuration file to $($ConfigFilePath)..."
        $EnvConfigSchema | ConvertTo-Json -Depth 10 | Out-File -Path $($ConfigFilePath)
    } catch {
        Write-Error "Failed to write configuration file to $($ConfigFilePath). Error: $_"
    }
    #endregion
}
