name: "Git - Initialize"

on:
  workflow_call:

runs:
  using: "composite"
  steps:
    - name: "Configure GitUser"
      shell: bash
      run: |
        git config --global user.email "EntraOpsGHActions@ghActions.com"
        git config --global user.name "$GITHUB_ACTOR"

    - name: "Checkout"
      shell: bash
      run: |
        git checkout -b ${{ env.branch }} main
