/*
 * EntraOps Access Package Flow
 *
 * Visualizes the Entra ID Governance Entitlement Management configuration of a captured
 * EntraOps Tenant Governance snapshot (see Reports/ConfigurationAnalyzer, generated by
 * New-EntraOpsTenantGovernanceConfigurationAnalyzerData) as a filterable Sankey flow:
 *
 *   Requestor scope -> Assignment policy -> Access package -> Target resource role
 *
 * mirroring the Conditional Access Analysis app's CA Policy Flow. Every requestor,
 * approver and target resource that resolves to a known object id is cross-referenced
 * against the optional EAM Dashboard dataset (../EamDashboard/data/eam-dashboard-data.js,
 * loaded by ../ConfigurationAnalyzer/js/core.js as EAM_DATA / objectTierIndex) to surface
 * its access tier, so the app can flag:
 *
 *   - Access packages that grant Control Plane / Management Plane resources without
 *     requiring approval ("self-service to a privileged resource").
 *   - Access packages any directory member can request ("broad requestor scope") that
 *     grant a privileged resource.
 *   - Approvers who are classified at a *lower* privilege tier than the resource they are
 *     approving access to.
 *   - (When the optional Reports/AccessPackageFlow/data/access-package-assignments-data.js
 *     dataset is present, generated by New-EntraOpsAccessPackageFlowData) currently
 *     assigned principals who are more privileged than the policy's own approvers.
 *
 * Reuses the snapshot/blob parsing model from ../ConfigurationAnalyzer/js/core.js (loaded
 * before this file - see index.html).
 */
(function () {
    "use strict";

    var excludedRiskFlagIds = new Set((DATA && Array.isArray(DATA.accessPackageFlowExcludedRiskFlags) ? DATA.accessPackageFlowExcludedRiskFlags : []).map(String));

    var RT = {
        catalog: "microsoft.entra.entitlementmanagementaccesspackagecatalog",
        pkg: "microsoft.entra.entitlementmanagementaccesspackage",
        policy: "microsoft.entra.entitlementmanagementaccesspackageassignmentpolicy",
        catalogResource: "microsoft.entra.entitlementmanagementaccesspackagecatalogresource"
    };

    var TIER_COLORS = { ControlPlane: "#a4262c", ManagementPlane: "#c07807", UserAccess: "#0e700e", Unclassified: "#a19f9d" };
    function tierColor(tier) { return TIER_COLORS[tier] || "#a19f9d"; }

    var SCOPE_TYPE_LABELS = {
        NoSubjects: "No one (self-service disabled)",
        AllConfiguredConnectedOrganizationSubjects: "All configured connected organizations",
        AllExistingConnectedOrganizationSubjects: "All existing connected organization members",
        AllExistingDirectoryMemberUsers: "All members (any directory user can request)",
        AllExistingDirectorySubjects: "All users, service principals, and agent identities in the directory can request",
        AllExternalSubjects: "All external users can request"
    };
    var BROAD_SCOPE_TYPES = ["AllExistingDirectoryMemberUsers", "AllExistingDirectorySubjects", "AllExternalSubjects", "AllExistingConnectedOrganizationSubjects"];
    // Subset of BROAD_SCOPE_TYPES that is still an internal-tenant audience (not external users/
    // connected orgs, which EntraOps has no classification data for at all) - classified as User
    // Access rather than left unresolved.
    var BROAD_USER_ACCESS_SCOPES = ["AllExistingDirectoryMemberUsers", "AllExistingDirectorySubjects"];

    // Optional live assignment dataset (generated by New-EntraOpsAccessPackageFlowData).
    // Absent by default - the app degrades gracefully (no "Assigned" enrichment) when it
    // hasn't been generated, same pattern as the optional EAM Dashboard cross-reference.
    var ASSIGNMENT_DATA = window.ENTRAOPS_ACCESSPACKAGE_ASSIGNMENTS || null;
    var assignmentsByPackage = new Map(); // accessPackageId -> [assignment,...]
    if (ASSIGNMENT_DATA && Array.isArray(ASSIGNMENT_DATA.assignments)) {
        ASSIGNMENT_DATA.assignments.forEach(function (a) {
            if (!a.accessPackageId) return;
            if (!assignmentsByPackage.has(a.accessPackageId)) assignmentsByPackage.set(a.accessPackageId, []);
            assignmentsByPackage.get(a.accessPackageId).push(a);
        });
    }

    // Optional: requestor/approver subject ids recovered live from Microsoft Graph
    // (New-EntraOpsAccessPackageFlowData) - the Tenant Governance Snapshot never captures a
    // 'groupMembers' subject's group id (only odataType/IsBackup are serialized), so this is the
    // only source that can resolve WHICH group a requestor scope/approver refers to. Matched
    // positionally against the snapshot-captured usersets of the same policy (see
    // accessPackageModelForSnapshot) - both arrays come from the same underlying policy property.
    var POLICY_REQUESTOR_APPROVERS = (ASSIGNMENT_DATA && ASSIGNMENT_DATA.policyRequestorApprovers) || {};
    var LIVE_PACKAGES = (ASSIGNMENT_DATA && ASSIGNMENT_DATA.packages) || {};

    // Optional: tier (+ per-member classification breakdown) of requestor/approver groups
    // resolved via transitive membership from the live-recovered ids above - same shape as the
    // Configuration Analyzer's resolvedGroupTiers (core.js's resolvedGroupTierIndex), but for
    // groups that could only be discovered here (never captured in the snapshot at all).
    var assignmentResolvedGroupTierIndex = new Map();
    if (ASSIGNMENT_DATA && ASSIGNMENT_DATA.resolvedGroupTiers && typeof ASSIGNMENT_DATA.resolvedGroupTiers === "object") {
        Object.keys(ASSIGNMENT_DATA.resolvedGroupTiers).forEach(function (id) {
            var g = ASSIGNMENT_DATA.resolvedGroupTiers[id];
            if (g && g.tierName) assignmentResolvedGroupTierIndex.set(id.toUpperCase(), g);
        });
    }

    // ---- Case-insensitive property lookup (see EIDSCA's resolveEidscaPath for why: the
    // Tenant Governance Snapshot's userset/subject objects can vary slightly in casing). ----
    function prop(obj, name) {
        if (!obj || typeof obj !== "object") return undefined;
        if (obj[name] !== undefined) return obj[name];
        var lower = name.toLowerCase();
        var key = Object.keys(obj).filter(function (k) { return k.toLowerCase() === lower; })[0];
        return key !== undefined ? obj[key] : undefined;
    }

    function lookupById(items, id) {
        if (!items || !id) return null;
        if (items[id]) return items[id];
        var wanted = String(id).toUpperCase();
        var key = Object.keys(items).filter(function (candidate) { return String(candidate).toUpperCase() === wanted; })[0];
        return key === undefined ? null : items[key];
    }

    // Tenant Governance snapshots serialize AccessPackageId as the package display name,
    // whereas Graph enrichment uses the package's GUID as the object key.
    function lookupPackage(packages, idOrName) {
        var byId = lookupById(packages, idOrName);
        if (byId) return byId;
        var wanted = String(idOrName || "").toUpperCase();
        var key = Object.keys(packages).filter(function (candidate) {
            return String(packages[candidate].displayName || "").toUpperCase() === wanted;
        })[0];
        return key === undefined ? null : packages[key];
    }

    function targetResourceType(resourceType, originSystem) {
        var value = [resourceType, originSystem].filter(Boolean).join(" ").toLowerCase();
        if (/group|aadgroup/.test(value)) return "Groups";
        if (/azureresources|azure\s*resource|subscription|management\s*group/.test(value)) return "AzureRbac";
        if (/directory\s*role|aadrole|entra\s*role/.test(value)) return "DirectoryRoles";
        if (/\bapi\b|application|service\s*principal|aadapplication/.test(value)) return "ApiPermissions";
        return "Other";
    }

    // Resolves an id directly classified by EntraOps (objectTierIndex) OR - when the id is a
    // group not itself classified - via its transitive membership (resolvedGroupTierIndex,
    // populated by New-EntraOpsTenantGovernanceConfigurationAnalyzerData
    // -ResolveGroupMembersForPrivilegedAssets). Both Maps are defined in core.js.
    function resolveIdentityHit(id, preferGroupMembership) {
        if (!id) return null;
        var upper = String(id).toUpperCase();
        var candidates = [objectTierIndex.get(upper), resolvedGroupTierIndex.get(upper), assignmentResolvedGroupTierIndex.get(upper)].filter(Boolean);
        if (!candidates.length) return null;
        candidates.sort(function (left, right) {
            var rankDiff = tierRank(left.tierName) - tierRank(right.tierName);
            if (rankDiff) return rankDiff;
            if (preferGroupMembership) return (Array.isArray(right.members) ? 1 : 0) - (Array.isArray(left.members) ? 1 : 0);
            return 0;
        });
        return candidates[0];
    }

    // Explains WHY a requestor/approver entry got its tier, for the tooltip/detail panel - the
    // user-facing answer to "which classification applies and where did it come from".
    function tierSourceExplanation(entry) {
        if (!entry) return "";
        switch (entry.source) {
            case "direct":
                return "Classified directly by EntraOps" + (entry.tier ? " as " + entry.tier : "") + ".";
            case "groupMembership":
                return "Group tier resolved from " + (entry.totalMembers != null ? entry.totalMembers : "its") + " transitive member(s)" +
                    (entry.privilegedMemberCount ? " (" + entry.privilegedMemberCount + " privileged)" : "") +
                    (entry.idSource === "live" ? " - group id recovered via a live Microsoft Graph query (not captured by the snapshot)." : ".");
            case "default":
                return "Not covered by any EntraOps classification - defaulted to User Access" + (entry.idSource === "live" ? " (id recovered via a live Microsoft Graph query)." : ".");
            case "broadScope":
                return "Broad self-service scope (any eligible directory member can request) - classified as User Access.";
            case "scopeClassification":
                return entry.classificationReason || "Classified from the assigned Identity Governance resource role scope.";
            default:
                return entry.resolved ? "" : "Could not be resolved to a specific identity.";
        }
    }

    function describeUserSet(us, liveUserSet) {
        var typeName = String(prop(us, "odataType") || "").replace("#microsoft.graph.", "");
        var id = prop(us, "Id") || null;
        var idSource = id ? "snapshot" : null;
        var liveId = liveUserSet ? prop(liveUserSet, "Id") : null;
        var liveDescription = liveUserSet ? (prop(liveUserSet, "DisplayName") || prop(liveUserSet, "Description")) : null;
        var snapshotDescription = prop(us, "DisplayName") || prop(us, "Description");
        if (!id && liveId) { id = liveId; idSource = "live"; }
        var hit = resolveIdentityHit(id, typeName === "groupMembers");
        var tier = hit ? hit.tierName : null;
        var source = null;
        if (hit) {
            // A group-membership roll-up (resolvedGroupTierIndex/assignmentResolvedGroupTierIndex)
            // always carries a members[] breakdown - a directly EntraOps-classified object never
            // does (its classification is the object's own, not derived from its members).
            source = Array.isArray(hit.members) ? "groupMembership" : "direct";
        } else if (id && (typeName === "singleUser" || typeName === "groupMembers")) {
            // A real id is known but not covered by any EntraOps classification - per the
            // Privileged Assets "not covered by EntraOps => User Access" convention (core.js's
            // identityTierFor), rather than leaving it unclassified/gray.
            tier = "UserAccess";
            source = "default";
        }
        var base;
        switch (typeName) {
            case "singleUser":
                base = hit ? "User: " + hit.displayName : (liveDescription || snapshotDescription ? "User: " + (liveDescription || snapshotDescription) : (id ? "User (" + id + ")" : "User (id not captured by snapshot)")); break;
            case "groupMembers":
                base = hit ? "Members of: " + hit.displayName : (liveDescription || snapshotDescription ? "Members of: " + (liveDescription || snapshotDescription) : (id ? "Members of group (" + id + ")" : "Group members (id not captured by snapshot)")); break;
            case "connectedOrganizationMembers":
                base = "Connected org members" + (id ? " (" + id + ")" : ""); break;
            case "requestorManager": {
                var level = prop(us, "ManagerLevel");
                base = "Requestor's manager" + (level && level > 1 ? " (level " + level + ")" : ""); break;
            }
            case "internalSponsors": base = "Internal sponsors"; break;
            case "externalSponsors": base = "External sponsors"; break;
            default: base = typeName || "Unknown subject";
        }
        return {
            label: base,
            tier: tier,
            resolved: !!hit,
            source: source,
            idSource: idSource,
            groupId: (typeName === "groupMembers" && id) ? id : null,
            members: (hit && Array.isArray(hit.members)) ? hit.members : null,
            membersTruncated: hit ? !!hit.membersTruncated : false,
            totalMembers: hit ? hit.totalMembers : null,
            privilegedMemberCount: hit ? hit.privilegedMemberCount : null
        };
    }

    function dedupBySet(list, keyFn) {
        var seen = {}, out = [];
        list.forEach(function (item) {
            var k = keyFn(item);
            if (seen[k]) return;
            seen[k] = true;
            out.push(item);
        });
        return out;
    }

    function conditionalAccessTargetGroupReferences(snap) {
        var references = new Set();
        snap.resources.forEach(function (resource) {
            if (String(resource.type || "").toLowerCase() !== "microsoft.entra.conditionalaccesspolicy") return;
            var policy = blobContent(resource.h);
            var properties = policy && policy.properties;
            (Array.isArray(properties && properties.IncludeGroups) ? properties.IncludeGroups : []).forEach(function (group) {
                references.add(String(group).toUpperCase());
            });
        });
        return references;
    }

    function isConditionalAccessTargetAssignment(entry, references) {
        if (!entry) return false;
        var label = String(entry.label || "");
        var isGroupLabel = /^Members of:\s*/i.test(label);
        if (!entry.groupId && !isGroupLabel) return false;
        var groupName = label.replace(/^Members of:\s*/i, "");
        return (entry.groupId && references.has(String(entry.groupId).toUpperCase())) ||
            (groupName && references.has(groupName.toUpperCase()));
    }

    // ---- Parse one snapshot's entitlement management resources into the flow model -----
    var apCache = {};
    function accessPackageModelForSnapshot(snap) {
        var key = snap.commitSha + "|" + snap.commitDate;
        if (apCache[key]) return apCache[key];

        var catalogs = {}, catalogResourcesByOriginId = {}, packages = {}, policies = [];

        snap.resources.forEach(function (r) {
            var type = String(r.type).toLowerCase();
            if (type !== RT.catalog && type !== RT.pkg && type !== RT.policy && type !== RT.catalogResource) return;
            var blob = blobContent(r.h);
            if (blob === undefined || blob === null) return;
            var p = blob.properties || {};

            if (type === RT.catalog) {
                catalogs[prop(p, "Id") || r.name] = { id: prop(p, "Id"), displayName: prop(p, "DisplayName") || r.name, status: prop(p, "CatalogStatus"), catalogType: prop(p, "CatalogType") };
            } else if (type === RT.catalogResource) {
                var originId = prop(p, "OriginId");
                if (originId) {
                    catalogResourcesByOriginId[originId] = {
                        displayName: prop(p, "DisplayName") || r.name,
                        resourceType: prop(p, "ResourceType") || prop(p, "OriginSystem") || "Resource",
                        catalogId: prop(p, "CatalogId")
                    };
                }
            } else if (type === RT.pkg) {
                var scopes = (prop(p, "AccessPackageResourceRoleScopes") || []).map(function (rs) { return rs; });
                packages[prop(p, "Id") || r.name] = {
                    id: prop(p, "Id"),
                    displayName: prop(p, "DisplayName") || r.name,
                    catalogId: prop(p, "CatalogId"),
                    isHidden: !!prop(p, "IsHidden"),
                    resourceRoleScopes: scopes,
                    resource: r
                };
            } else if (type === RT.policy) {
                policies.push({ p: p, resource: r });
            }
        });

        // Snapshots can omit access packages and their resource-role scopes. The optional
        // Graph enrichment dataset restores those current package definitions by package id.
        Object.keys(LIVE_PACKAGES).forEach(function (packageId) {
            var livePackage = LIVE_PACKAGES[packageId];
            if (!livePackage) return;
            if (!packages[packageId]) {
                packages[packageId] = {
                    id: packageId,
                    displayName: livePackage.displayName || packageId,
                    catalogId: livePackage.catalogId,
                    isHidden: false,
                    resourceRoleScopes: [],
                    resource: null
                };
            }
            var pkg = packages[packageId];
            if (livePackage.displayName) pkg.displayName = livePackage.displayName;
            if (!pkg.catalogId && livePackage.catalogId) pkg.catalogId = livePackage.catalogId;
            if (!pkg.catalogName && livePackage.catalogName) pkg.catalogName = livePackage.catalogName;
            if (pkg.resourceRoleScopes.length || !Array.isArray(livePackage.targets)) return;
            pkg.resourceRoleScopes = livePackage.targets.map(function (target) {
                if (target.originId && target.displayName) {
                    catalogResourcesByOriginId[target.originId] = {
                        displayName: target.displayName,
                        resourceType: target.resourceType || "Resource",
                        originSystem: target.originSystem || null,
                        catalogId: pkg.catalogId
                    };
                }
                return {
                    AccessPackageResourceOriginId: target.originId,
                    AccessPackageResourceRoleDisplayName: target.role || "(role)",
                    AccessPackageResourceTierName: target.tierName,
                    AccessPackageResourceClassificationReason: target.classificationReason
                };
            });
        });

        // Resolve target resource/tier info for every access package now that catalog
        // resources are fully indexed (order of resource files within a snapshot isn't
        // guaranteed).
        Object.keys(packages).forEach(function (pkgId) {
            var pkg = packages[pkgId];
            pkg.targets = pkg.resourceRoleScopes.map(function (rs) {
                var originId = prop(rs, "AccessPackageResourceOriginId");
                var roleLabel = prop(rs, "AccessPackageResourceRoleDisplayName") || "(role)";
                var res = originId ? catalogResourcesByOriginId[originId] : null;
                var hit = resolveIdentityHit(originId);
                var capturedName = res ? res.displayName : null;
                var resourceName = hit && hit.displayName && (!capturedName || capturedName === "Root") ? hit.displayName : (capturedName || (originId || "(unresolved resource)"));
                var classifiedTier = prop(rs, "AccessPackageResourceTierName") || null;
                var hitTier = hit ? hit.tierName : null;
                var tier = classifiedTier && hitTier
                    ? (tierRank(classifiedTier) <= tierRank(hitTier) ? classifiedTier : hitTier)
                    : (classifiedTier || hitTier);
                var classificationReason = prop(rs, "AccessPackageResourceClassificationReason") || null;
                return {
                    label: resourceName + " (" + roleLabel + ")",
                    originId: originId,
                    resourceName: resourceName,
                    role: roleLabel,
                    resourceType: res ? res.resourceType : null,
                    targetType: targetResourceType(res ? res.resourceType : null, res ? res.originSystem : null),
                    catalogId: res ? res.catalogId : null,
                    tier: tier,
                    source: hitTier && tier === hitTier ? (Array.isArray(hit.members) ? "groupMembership" : "direct") : (classifiedTier ? "scopeClassification" : null),
                    classificationReason: classificationReason,
                    members: (hit && Array.isArray(hit.members)) ? hit.members : null,
                    membersTruncated: hit ? !!hit.membersTruncated : false,
                    totalMembers: hit ? hit.totalMembers : null,
                    privilegedMemberCount: hit ? hit.privilegedMemberCount : null
                };
            });
            if (!pkg.targets.length) pkg.targets = [{ label: "(no target resource captured)", resourceName: null, role: null, resourceType: null, tier: null }];
        });

        // Computed once per snapshot (not per policy) - scans every captured Conditional
        // Access policy's IncludeGroups, so it would be wasteful to repeat for each of
        // potentially many access package assignment policies below.
        var conditionalAccessGroups = conditionalAccessTargetGroupReferences(snap);

        // Count assignment policies per resolved access package - an assignment record without
        // an assignmentPolicyId can only be attributed unambiguously when its package has
        // exactly one policy (see policyAssignments below).
        var policyCountByPackage = {};
        policies.forEach(function (item) {
            var livePolicy = lookupById(POLICY_REQUESTOR_APPROVERS, prop(item.p, "Id"));
            var pkgRef = (livePolicy && prop(livePolicy, "AccessPackageId")) || prop(item.p, "AccessPackageId");
            var pkgHit = lookupPackage(packages, pkgRef);
            var resolvedRef = pkgHit && pkgHit.id ? pkgHit.id : pkgRef;
            if (resolvedRef) policyCountByPackage[resolvedRef] = (policyCountByPackage[resolvedRef] || 0) + 1;
        });

        // Build one flow entry per assignment policy (a policy always belongs to exactly
        // one access package).
        var flows = policies.map(function (item) {
            var p = item.p;
            var policyId = prop(p, "Id");
            var liveForPolicy = lookupById(POLICY_REQUESTOR_APPROVERS, policyId);
            var pkgId = (liveForPolicy && prop(liveForPolicy, "AccessPackageId")) || prop(p, "AccessPackageId");
            var pkg = lookupPackage(packages, pkgId);
            var resolvedPkgId = pkg && pkg.id ? pkg.id : pkgId;
            var catalogId = pkg && (pkg.catalogId || (pkg.targets || []).map(function (target) { return target.catalogId; }).filter(Boolean)[0]);
            var catalog = lookupById(catalogs, catalogId);
            var catalogName = catalog ? catalog.displayName : (pkg && pkg.catalogName ? pkg.catalogName : (catalogId ? "Catalog " + catalogId : null));
            var liveRequestors = (liveForPolicy && Array.isArray(liveForPolicy.requestors)) ? liveForPolicy.requestors : [];
            var liveApprovers = (liveForPolicy && Array.isArray(liveForPolicy.approvers)) ? liveForPolicy.approvers : [];

            var requestorSettings = prop(p, "RequestorSettings") || {};
            var snapshotScopeType = prop(requestorSettings, "ScopeType") || "NoSubjects";
            var liveScopeType = liveForPolicy && prop(liveForPolicy, "ScopeType");
            var scopeType = snapshotScopeType === "Unknown" && liveScopeType ? liveScopeType : snapshotScopeType;
            var allowedRequestors = prop(requestorSettings, "AllowedRequestors") || [];
            var requestors;
            if (SCOPE_TYPE_LABELS[scopeType] && (!allowedRequestors.length || scopeType.indexOf("All") === 0)) {
                // Broad "any directory member/subject can self-service request" scopes are not a
                // specific privileged identity - classified as User Access (the least-privileged
                // default), matching the same "not a known privileged object => User Access"
                // convention applied to individual/group requestors below.
                var isUserAccessScope = BROAD_USER_ACCESS_SCOPES.indexOf(scopeType) !== -1;
                requestors = [{ label: SCOPE_TYPE_LABELS[scopeType], tier: isUserAccessScope ? "UserAccess" : null, resolved: false, source: isUserAccessScope ? "broadScope" : null }];
            } else if (allowedRequestors.length) {
                requestors = dedupBySet(allowedRequestors.map(function (u, i) {
                    return describeUserSet(u, liveRequestors[i] || null);
                }), function (x) { return x.label; });
            } else {
                requestors = [{ label: SCOPE_TYPE_LABELS[scopeType] || "(no requestor scope captured)", tier: null, resolved: false }];
            }

            var approvalSettings = prop(p, "RequestApprovalSettings") || {};
            var isApprovalRequired = !!prop(approvalSettings, "IsApprovalRequired");
            var stages = prop(approvalSettings, "ApprovalStages") || [];
            var approverSets = [];
            stages.forEach(function (stage) { (prop(stage, "PrimaryApprovers") || []).forEach(function (u) { approverSets.push(u); }); });
            var approvers = isApprovalRequired
                ? (approverSets.length ? dedupBySet(approverSets.map(function (u, i) {
                    return describeUserSet(u, liveApprovers[i] || null);
                }), function (x) { return x.label; }) : [{ label: "(no approver captured)", tier: null, resolved: false }])
                : [];

            // Every requestor/approver/target here is already, by definition, part of this
            // access package's flow - tagging that fact would just restate the column it's
            // already in. The only tag worth surfacing is a genuinely non-obvious cross-report
            // fact: this same group is ALSO a Conditional Access target (a relationship a user
            // wouldn't otherwise see while looking at Access Package Flow alone).
            requestors.forEach(function (entry) {
                entry.conditionalAccessTargetAssignment = isConditionalAccessTargetAssignment(entry, conditionalAccessGroups);
                entry.tags = entry.conditionalAccessTargetAssignment ? ["Conditional Access Target Assignment"] : [];
            });
            approvers.forEach(function (entry) {
                entry.conditionalAccessTargetAssignment = isConditionalAccessTargetAssignment(entry, conditionalAccessGroups);
                entry.tags = entry.conditionalAccessTargetAssignment ? ["Conditional Access Target Assignment"] : [];
            });

            var targets = pkg ? pkg.targets : [{ label: "(access package not resolved: " + (pkgId || "?") + ")", resourceName: null, role: null, resourceType: null, tier: null }];
            targets.forEach(function (entry) {
                entry.conditionalAccessTargetAssignment = !!entry.originId &&
                    (conditionalAccessGroups.has(String(entry.originId).toUpperCase()) || conditionalAccessGroups.has(String(entry.resourceName || "").toUpperCase()));
                entry.tags = entry.conditionalAccessTargetAssignment ? ["Conditional Access Target Assignment"] : [];
            });

            var approverBestRank = approvers.reduce(function (best, a) { return a.tier ? Math.min(best, tierRank(a.tier)) : best; }, TIER_ORDER.length);
            var approvalTier = approverBestRank < TIER_ORDER.length ? TIER_ORDER[approverBestRank] : null;
            // Unresolved approvers default to User Access for display only (see describeUserSet) -
            // exclude them from the lower-tier comparison so a subject that merely could not be
            // resolved against the EAM dataset never triggers a false "lower tier" flag.
            var resolvedApproverBestRank = approvers.reduce(function (best, a) { return a.resolved && a.tier ? Math.min(best, tierRank(a.tier)) : best; }, TIER_ORDER.length);
            var targetWorstRank = targets.reduce(function (best, t) { return t.tier ? Math.min(best, tierRank(t.tier)) : best; }, TIER_ORDER.length);
            var targetIsPrivileged = targets.some(function (t) { return t.tier === "ControlPlane" || t.tier === "ManagementPlane"; });

            var flags = [];
            if (!isApprovalRequired && targetIsPrivileged) {
                flags.push({ id: "noApproval", severity: "fail", text: "No approval required to obtain a Control Plane / Management Plane resource." });
            }
            if (BROAD_SCOPE_TYPES.indexOf(scopeType) !== -1 && targetIsPrivileged) {
                flags.push({ id: "broadRequestor", severity: "fail", text: "Any directory member (or external user) can request a Control Plane / Management Plane resource." });
            }
            if (isApprovalRequired && resolvedApproverBestRank < TIER_ORDER.length && targetWorstRank < TIER_ORDER.length && resolvedApproverBestRank > targetWorstRank) {
                flags.push({
                    id: "approverLowerTier", severity: "warn",
                    text: "Approver(s) are classified at a lower privilege tier (" + TIER_ORDER[resolvedApproverBestRank] + ") than the resource being granted (" + TIER_ORDER[targetWorstRank] + ")."
                });
            }

            var assignments = resolvedPkgId ? (assignmentsByPackage.get(resolvedPkgId) || []) : [];
            var packagePolicyCount = resolvedPkgId ? (policyCountByPackage[resolvedPkgId] || 0) : 0;
            var policyAssignments = assignments.filter(function (a) {
                // No policy id on the assignment: only attributable when the package has exactly
                // one policy - otherwise it would inflate every policy's counts.
                if (!a.assignmentPolicyId) return packagePolicyCount === 1;
                return a.assignmentPolicyId === policyId;
            });
            var assignedTierCounts = {};
            var assignedPrincipals = [];
            var assignedMorePrivilegedThanApprover = [];
            policyAssignments.forEach(function (a) {
                var t = a.target || {};
                var hit = t.objectId ? objectTierIndex.get(String(t.objectId).toUpperCase()) : null;
                var tierName = hit ? hit.tierName : (t.objectId ? "UserAccess" : "Unclassified");
                var principalName = (hit && hit.displayName) || t.displayName || t.principalName || t.objectId || "(unresolved principal)";
                assignedTierCounts[tierName] = (assignedTierCounts[tierName] || 0) + 1;
                assignedPrincipals.push({
                    label: principalName,
                    tier: tierName,
                    resolved: !!hit,
                    source: hit ? "direct" : (t.objectId ? "default" : null)
                });
                if (isApprovalRequired && hit && approverBestRank < TIER_ORDER.length && tierRank(tierName) < approverBestRank) {
                    assignedMorePrivilegedThanApprover.push(hit.displayName || t.principalName || t.objectId);
                }
            });
            if (assignedMorePrivilegedThanApprover.length) {
                flags.push({
                    id: "assignedMorePrivileged", severity: "warn",
                    text: "Currently assigned principal(s) are classified at a higher privilege tier than this policy's approver(s): " + assignedMorePrivilegedThanApprover.slice(0, 5).join(", ") + (assignedMorePrivilegedThanApprover.length > 5 ? ", …" : "") + "."
                });
            }
            flags = flags.filter(function (flag) { return !excludedRiskFlagIds.has(flag.id); });

            return {
                id: policyId || item.resource.p,
                name: prop(p, "DisplayName") || item.resource.name,
                description: prop(p, "Description"),
                resource: item.resource,
                accessPackageId: resolvedPkgId,
                accessPackageName: pkg ? pkg.displayName : (pkgId || "(unresolved access package)"),
                catalogId: catalogId,
                catalogName: catalogName,
                scopeType: scopeType,
                acceptRequests: prop(requestorSettings, "AcceptRequests"),
                requestors: requestors,
                isApprovalRequired: isApprovalRequired,
                approvalMode: prop(approvalSettings, "ApprovalMode") || "NoApproval",
                approvalTier: approvalTier,
                approvalStages: stages.map(function (stage, index) {
                    var timeout = prop(stage, "ApprovalStageTimeOutInDays");
                    var escalation = prop(stage, "IsEscalationEnabled") ? ", escalation after " + (prop(stage, "EscalationTimeInMinutes") || 0) + " minute(s)" : ", no escalation";
                    return "Stage " + (index + 1) + (timeout != null ? ": " + timeout + " day timeout" : "") + escalation;
                }),
                approvalRequiredForExtension: !!prop(approvalSettings, "IsApprovalRequiredForExtension"),
                requestorJustificationRequired: !!prop(approvalSettings, "IsRequestorJustificationRequired"),
                approvers: approvers,
                targets: targets,
                durationInDays: prop(p, "DurationInDays"),
                canExtend: !!prop(p, "CanExtend"),
                accessReviewEnabled: !!prop(prop(p, "AccessReviewSettings") || {}, "IsEnabled"),
                accessReviewSettings: prop(p, "AccessReviewSettings") || {},
                flags: flags,
                assignedCount: policyAssignments.length,
                assignedTierCounts: assignedTierCounts,
                assignedPrincipals: assignedPrincipals,
                hasAssignmentData: !!ASSIGNMENT_DATA
            };
        });

        flows.sort(function (a, b) { return a.name.localeCompare(b.name); });
        apCache[key] = { catalogs: catalogs, packages: packages, flows: flows };
        return apCache[key];
    }

    // =====================================================================================
    // State + filters
    // =====================================================================================
    var apState = {
        snapshotIdx: -1,
        columns: new Set(["requestor", "policy", "package", "target"]),
        approvalFilter: "",
        expirationFilter: "",
        flagFilter: "",
        metricFilter: "all",
        requestorTierFilter: "",
        memberTierFilter: "",
        catalogFilter: "",
        targetTypeFilter: "",
        search: "",
        traceNodeId: null
    };
    var apFlagState = { groupBy: "tier", sortBy: "severity", search: "", collapsedGroups: new Set(), collapseStateGroupBy: null };

    var COLUMN_ORDER = ["requestor", "policy", "package", "target"];
    var COLUMNS = {
        requestor: { label: "Requestor scope", values: function (f) { return f.requestors.map(function (r) { return r.label; }); } },
        policy: { label: "Assignment policy", values: function (f) { return [f.name]; } },
        package: { label: "Access package", values: function (f) { return [f.accessPackageName]; } },
        target: { label: "Target resource role", values: function (f) { return f.targets.map(function (t) { return t.label; }); } }
    };

    function currentFlows() {
        if (apState.snapshotIdx < 0) return [];
        return accessPackageModelForSnapshot(snapshots[apState.snapshotIdx]).flows;
    }

    function flowMatchesFilters(f) {
        if (apState.approvalFilter === "required" && !f.isApprovalRequired) return false;
        if (apState.approvalFilter === "none" && f.isApprovalRequired) return false;
        var hasFixedExpiration = f.durationInDays != null && Number(f.durationInDays) > 0;
        if (apState.expirationFilter === "none" && hasFixedExpiration) return false;
        if (apState.expirationFilter === "fixed" && !hasFixedExpiration) return false;
        if (apState.flagFilter && !f.flags.some(function (fl) { return fl.id === apState.flagFilter; })) return false;
        if (apState.metricFilter === "noApproval" && f.isApprovalRequired) return false;
        if (apState.metricFilter === "anyRisk" && !f.flags.length) return false;
        if (apState.requestorTierFilter) {
            var wantUnclassified = apState.requestorTierFilter === "Unclassified";
            if (!f.requestors.some(function (r) { return wantUnclassified ? !r.tier : r.tier === apState.requestorTierFilter; })) return false;
        }
        if (apState.memberTierFilter && !f.requestors.some(function (r) {
            return r.members && r.members.some(function (member) { return member.tierName === apState.memberTierFilter; });
        })) return false;
        if (apState.catalogFilter && f.catalogId !== apState.catalogFilter) return false;
        var matchingTargets = apState.targetTypeFilter ? f.targets.filter(function (target) {
            return target.targetType === apState.targetTypeFilter;
        }) : f.targets;
        if (!matchingTargets.length) return false;
        if (apState.search) {
            var q = apState.search.toLowerCase();
            var hay = [f.name, f.accessPackageName, f.catalogName || ""].concat(
                f.requestors.map(function (r) { return r.label; }),
                f.approvers.map(function (a) { return a.label; }),
                matchingTargets.map(function (t) { return t.label; })
            ).join("   ").toLowerCase();
            if (hay.indexOf(q) === -1) return false;
        }
        return true;
    }

    function visibleFlow(f) {
        if (!apState.targetTypeFilter) return f;
        return Object.assign({}, f, {
            targets: f.targets.filter(function (target) { return target.targetType === apState.targetTypeFilter; })
        });
    }

    function nodeId(col, label, flow) {
        return col === "policy" ? "policy|" + flow.id : col + "|" + label;
    }

    function nodeColor(n, flowsById) {
        if (n.column === "policy") {
            var f = flowsById.get(n.id.slice("policy|".length));
            if (f && f.flags.some(function (fl) { return fl.severity === "fail"; })) return "#a4262c";
            if (f && f.flags.length) return "#8a6d00";
            return f && f.isApprovalRequired ? tierColor(f.approvalTier) : "#0078d4";
        }
        if (n.column === "target" || n.column === "requestor") return tierColor(n.tier);
        return "#5c2d91";
    }

    function buildGraph(flows) {
        var activeCols = COLUMN_ORDER.filter(function (c) { return apState.columns.has(c); });
        var nodeMap = new Map();
        var linkMap = new Map();
        var flowsById = new Map();
        flows.forEach(function (f) { flowsById.set(f.id, f); });

        function tierForLabel(col, label, f) {
            if (col === "target") { var t = f.targets.filter(function (x) { return x.label === label; })[0]; return t ? t.tier : null; }
            if (col === "requestor") { var r = f.requestors.filter(function (x) { return x.label === label; })[0]; return r ? r.tier : null; }
            return null;
        }

        function ensureNode(col, label, f) {
            var id = nodeId(col, label, f);
            if (!nodeMap.has(id)) {
                var entry = col === "requestor" ? f.requestors.filter(function (item) { return item.label === label; })[0] :
                    (col === "target" ? f.targets.filter(function (item) { return item.label === label; })[0] : null);
                nodeMap.set(id, {
                    id: id, name: label, column: col, tier: tierForLabel(col, label, f), flowIds: new Set(),
                    // Representative requestor/target entry (all flows sharing this node carry the
                    // same label/tier) - lets findEntryForNode avoid scanning every flow per lookup.
                    entry: entry || null,
                    tags: entry && entry.tags ? entry.tags.slice() : []
                });
            }
            if (col === "requestor" || col === "target") {
                var entryForTag = col === "requestor" ? f.requestors.filter(function (item) { return item.label === label; })[0] : f.targets.filter(function (item) { return item.label === label; })[0];
                if (entryForTag && entryForTag.tags) entryForTag.tags.forEach(function (tag) {
                    if (nodeMap.get(id).tags.indexOf(tag) === -1) nodeMap.get(id).tags.push(tag);
                });
            }
            nodeMap.get(id).flowIds.add(f.id);
            return id;
        }

        flows.forEach(function (f) {
            var perCol = activeCols.map(function (c) {
                return COLUMNS[c].values(f).map(function (label) { return ensureNode(c, label, f); });
            });
            for (var i = 0; i < perCol.length - 1; i++) {
                perCol[i].forEach(function (sId) {
                    perCol[i + 1].forEach(function (tId) {
                        var key = sId + "→" + tId;
                        var link = linkMap.get(key);
                        if (!link) { link = { source: sId, target: tId, value: 0, flowIds: new Set() }; linkMap.set(key, link); }
                        link.value += 1;
                        link.flowIds.add(f.id);
                    });
                });
            }
        });

        var nodes = Array.from(nodeMap.values());
        var index = new Map(nodes.map(function (n, i) { return [n.id, i]; }));
        var links = Array.from(linkMap.values()).map(function (l) {
            return { source: index.get(l.source), target: index.get(l.target), value: l.value, flowIds: l.flowIds };
        });
        return { nodes: nodes, links: links, flowsById: flowsById };
    }

    // =====================================================================================
    // Rendering
    // =====================================================================================
    function renderStats() {
        var flows = currentFlows();
        $("apStatPolicies").textContent = flows.length.toLocaleString();
        var pkgIds = {}; flows.forEach(function (f) { if (f.accessPackageId) pkgIds[f.accessPackageId] = true; });
        $("apStatPackages").textContent = Object.keys(pkgIds).length.toLocaleString();
        var noApproval = flows.filter(function (f) { return !f.isApprovalRequired; }).length;
        $("apStatNoApproval").textContent = noApproval.toLocaleString();
        var flagged = flows.filter(function (f) { return f.flags.length > 0; }).length;
        $("apStatFlagged").textContent = flagged.toLocaleString();
        $("apStatAssignData").textContent = ASSIGNMENT_DATA ? "loaded" : "not generated";
    }

    function renderControls() {
        var sel = $("apSnapshot");
        var idxs = detailedSnapshotIdxs();
        var html = "";
        idxs.forEach(function (i) {
            html += '<option value="' + i + '"' + (i === apState.snapshotIdx ? " selected" : "") + ">" + esc(snapshotLabel(snapshots[i], i)) + "</option>";
        });
        sel.innerHTML = html;

        var colHtml = "";
        COLUMN_ORDER.forEach(function (c) {
            colHtml += '<span class="ca-toggle' + (apState.columns.has(c) ? " on" : "") + '" role="button" tabindex="0" data-col="' + c + '">' + COLUMNS[c].label + "</span>";
        });
        $("apColToggles").innerHTML = colHtml;

        function renderFilterOptions(id, emptyLabel, options, selected) {
            var unique = {};
            options.forEach(function (option) { if (option.value) unique[option.value] = option.label; });
            var values = Object.keys(unique).sort(function (a, b) { return unique[a].localeCompare(unique[b]); });
            if (selected && values.indexOf(selected) === -1) selected = "";
            $(id).innerHTML = '<option value="">' + esc(emptyLabel) + '</option>' + values.map(function (value) {
                return '<option value="' + esc(value) + '"' + (value === selected ? ' selected' : '') + '>' + esc(unique[value]) + '</option>';
            }).join("");
            return selected;
        }
        var selectableFlows = currentFlows();
        apState.catalogFilter = renderFilterOptions("apFltCatalog", "All catalogs", selectableFlows.map(function (f) { return { value: f.catalogId, label: f.catalogName }; }), apState.catalogFilter);

        var flags = {};
        currentFlows().forEach(function (f) { f.flags.forEach(function (fl) { flags[fl.id] = fl.text.split(".")[0]; }); });
        var fHtml = '<option value="">All flags</option>';
        Object.keys(flags).sort().forEach(function (id) {
            fHtml += '<option value="' + esc(id) + '"' + (id === apState.flagFilter ? " selected" : "") + ">" + esc(flags[id]) + "</option>";
        });
        $("apFltFlag").innerHTML = fHtml;
    }

    var apSvg = null, apTooltip = null, apTraceFlowIds = null;

    function renderSankey() {
        apSvg = apSvg || d3.select("#apSankey");
        apTooltip = apTooltip || d3.select("#tooltip");
        var emptyEl = $("apSankeyEmpty");
        var all = currentFlows();
        var flows = all.filter(flowMatchesFilters).map(visibleFlow);
        if (apState.traceNodeId) {
            flows = flows.filter(function (f) { return apTraceFlowIds && apTraceFlowIds.has(f.id); });
        }
        $("apFreshness").textContent = EntraOpsReportUtils.freshnessText(DATA, snapshots[apState.snapshotIdx]);
        $("apFilterSummary").textContent = " · " + flows.length + " of " + all.length + " policy path(s) shown";
        $("apClearTrace").classList.toggle("hidden", !apState.traceNodeId);

        renderStats();
        renderFlagsSummary(all);

        if (!all.length) {
            apSvg.selectAll("*").remove();
            apSvg.attr("height", 0);
            emptyEl.classList.remove("hidden");
            emptyEl.textContent = "No entitlement management assignment policies with embedded content in this snapshot. Pick a snapshot marked with ✓ content, ensure microsoft.entra.entitlementManagementAccessPackage(AssignmentPolicy|Catalog|CatalogResource) are in TenantGovernanceSnapshot.ResourcesToInclude, or regenerate the dataset with a higher -MaxDetailedSnapshots.";
            return;
        }
        if (!flows.length || apState.columns.size < 2) {
            apSvg.selectAll("*").remove();
            apSvg.attr("height", 0);
            emptyEl.classList.remove("hidden");
            emptyEl.textContent = apState.columns.size < 2 ? "Select at least two columns to draw a flow." : "No access package flows match the current filters.";
            return;
        }
        emptyEl.classList.add("hidden");

        var graph = buildGraph(flows);
        var nodeCount = graph.nodes.length;

        // Looks up the underlying requestor/target entry (tier, classification source, member
        // breakdown) for a Sankey node - a node can be shared by several flows, so the first
        // match (they all carry the same label/tier) is representative.
        function findEntryForNode(d) {
            // The representative entry is stashed on the node at graph build time (see ensureNode);
            // the previous per-call scan over every flow ran on each tooltip mousemove.
            return d.entry || null;
        }
        var width = Math.max(960, document.querySelector("#secApSankey .diagram-wrap").clientWidth - 48);
        var height = Math.max(480, nodeCount * 19);

        apSvg.attr("width", width).attr("height", height);
        apSvg.selectAll("*").remove();

        var sankey = d3.sankey().nodeWidth(14).nodePadding(9).extent([[8, 28], [width - 8, height - 8]]);
        var layout;
        try {
            layout = sankey({
                nodes: graph.nodes.map(function (d) { return Object.assign({}, d); }),
                links: graph.links.map(function (d) { return Object.assign({}, d); })
            });
        } catch (e) {
            emptyEl.classList.remove("hidden");
            emptyEl.textContent = "Unable to lay out the flow (possible cycle). Try different columns.";
            return;
        }
        var nodes = layout.nodes, links = layout.links;

        // Id-indexed lookup so the link mousemove handler doesn't scan all flows per pointer event.
        var allFlowsById = new Map();
        all.forEach(function (f) { allFlowsById.set(f.id, f); });

        function flowNamesFor(ids, limit) {
            var names = [];
            ids.forEach(function (id) { var f = allFlowsById.get(id); if (f) names.push(f.name); });
            var shown = names.slice(0, limit || 6).map(esc).join("<br/>");
            if (names.length > (limit || 6)) shown += "<br/>… and " + (names.length - (limit || 6)) + " more";
            return shown;
        }

        apSvg.append("g").attr("class", "links")
            .selectAll("path").data(links).join("path")
            .attr("class", "link")
            .attr("d", d3.sankeyLinkHorizontal())
            .attr("stroke", "var(--viz-flow-link)")
            .attr("stroke-opacity", 0.32)
            .attr("stroke-width", function (d) { return Math.max(1, d.width); })
            .on("mousemove", function (ev, d) {
                apTooltip.classed("hidden", false)
                    .style("left", (ev.clientX + 14) + "px").style("top", (ev.clientY + 14) + "px")
                    .html("<b>" + esc(d.source.name) + "</b> → <b>" + esc(d.target.name) + "</b><br/>" +
                        d.flowIds.size + " polic" + (d.flowIds.size === 1 ? "y" : "ies") + ":<br/>" + flowNamesFor(d.flowIds));
            })
            .on("mouseleave", function () { apTooltip.classed("hidden", true); });

        var nodeSel = apSvg.append("g").attr("class", "nodes")
            .selectAll("g").data(nodes).join("g").attr("class", "node");

        nodeSel.append("rect")
            .attr("x", function (d) { return d.x0; })
            .attr("y", function (d) { return d.y0; })
            .attr("width", function (d) { return d.x1 - d.x0; })
            .attr("height", function (d) { return Math.max(2, d.y1 - d.y0); })
            .attr("fill", function (d) { return nodeColor(d, graph.flowsById); })
            .attr("rx", 2)
            .on("mousemove", function (ev, d) {
                var extra = "";
                if (d.column === "policy") {
                    var f = graph.flowsById.get(d.id.slice("policy|".length));
                    if (f) {
                        extra = (f.isApprovalRequired ? "Approval required (" + esc(f.approvalMode) + ")" : "No approval required") +
                            "<br/>Access package: " + esc(f.accessPackageName) +
                            (f.flags.length ? "<br/>" + f.flags.map(function (fl) { return "⚠ " + esc(fl.text); }).join("<br/>") : "") +
                            "<br/><i>Click for full detail</i>";
                    }
                } else {
                    var entry = findEntryForNode(d);
                    var explain = entry ? tierSourceExplanation(entry) : "";
                    extra = (d.tier ? "Tier: " + esc(d.tier) + "<br/>" : "") +
                        (explain ? esc(explain) + "<br/>" : "") +
                        (d.tags.length ? "<b>Tags:</b> " + d.tags.map(esc).join(", ") + "<br/>" : "") +
                        d.flowIds.size + " polic" + (d.flowIds.size === 1 ? "y" : "ies") +
                        (entry && entry.members && entry.members.length ? "<br/><i>Click to trace this node and view its " + entry.members.length + " member(s)</i>" : "<br/><i>Click to trace this node</i>");
                }
                apTooltip.classed("hidden", false)
                    .style("left", (ev.clientX + 14) + "px").style("top", (ev.clientY + 14) + "px")
                    .html("<b>" + esc(d.name) + "</b><br/>" + extra);
            })
            .on("mouseleave", function () { apTooltip.classed("hidden", true); })
            .on("click", function (ev, d) {
                ev.stopPropagation();
                apState.traceNodeId = d.id;
                apTraceFlowIds = d.flowIds;
                if (d.column === "policy") {
                    renderFlowDetail(d.id.slice("policy|".length));
                } else {
                    $("apFlowDetail").classList.add("hidden");
                    var clickEntry = findEntryForNode(d);
                    if (clickEntry && clickEntry.members && clickEntry.members.length) renderGroupMemberPanel(clickEntry);
                    else $("apGroupMemberDetail").classList.add("hidden");
                }
                var detailEntry = findEntryForNode(d);
                var detailReference = detailEntry && (detailEntry.groupId || detailEntry.resourceName || detailEntry.originId);
                var canonicalReference = window.EntraOpsObjectInspector.canonicalReference(detailReference);
                var policyDetail = d.column === "policy" ? graph.flowsById.get(d.id.slice("policy|".length)) : null;
                var accessReview = policyDetail ? policyDetail.accessReviewSettings : {};
                var inspectorFields = policyDetail ? [
                    { section: "General", label: "Policy ID", value: policyDetail.id },
                    { section: "General", label: "Description", value: policyDetail.description },
                    { section: "General", label: "Access package", value: policyDetail.accessPackageName },
                    { section: "General", label: "Access package ID", value: policyDetail.accessPackageId },
                    { section: "General", label: "Catalog", value: policyDetail.catalogName },
                    { section: "General", label: "Target resource roles", value: policyDetail.targets.map(function (entry) { return entry.label + (entry.tier ? " [" + entry.tier + "]" : ""); }).join("; ") },
                    { section: "General", label: "Source path", value: policyDetail.resource.p },
                    { section: "Approval", label: "Requestor scope", value: policyDetail.scopeType },
                    { section: "Approval", label: "Accept requests", value: policyDetail.acceptRequests == null ? null : (policyDetail.acceptRequests ? "Yes" : "No") },
                    { section: "Approval", label: "Requestors", value: policyDetail.requestors.map(function (entry) { return entry.label + (entry.tier ? " [" + entry.tier + "]" : ""); }).join("; ") },
                    { section: "Approval", label: "Approval", value: policyDetail.isApprovalRequired ? policyDetail.approvalMode : "Not required" },
                    { section: "Approval", label: "Approval tier", value: policyDetail.approvalTier },
                    { section: "Approval", label: "Approval stages", value: policyDetail.approvalStages.join("; ") },
                    { section: "Approval", label: "Requestor justification", value: policyDetail.requestorJustificationRequired ? "Required" : "Not required" },
                    { section: "Reviewers", label: "Approvers", value: policyDetail.approvers.map(function (entry) { return entry.label + (entry.tier ? " [" + entry.tier + "]" : ""); }).join("; ") },
                    { section: "Reviewers", label: "Access review", value: policyDetail.accessReviewEnabled ? "Enabled" : "Disabled" },
                    { section: "Reviewers", label: "Review recurrence", value: prop(accessReview, "RecurrenceType") },
                    { section: "Reviewers", label: "Review duration", value: prop(accessReview, "DurationInDays") != null ? prop(accessReview, "DurationInDays") + " day(s)" : null },
                    { section: "Reviewers", label: "Reviewers", value: prop(accessReview, "ReviewerType") },
                    { section: "Reviewers", label: "Review timeout behavior", value: prop(accessReview, "AccessReviewTimeoutBehavior") },
                    { section: "Expiration", label: "Duration", value: policyDetail.durationInDays != null ? policyDetail.durationInDays + " day(s)" : "No fixed duration" },
                    { section: "Expiration", label: "Can extend", value: policyDetail.canExtend ? "Yes" : "No" },
                    { section: "Expiration", label: "Extension approval", value: policyDetail.approvalRequiredForExtension ? "Required" : "Not required" }
                ] : [
                    { label: "Flow column", value: COLUMNS[d.column].label },
                    { label: "Group ID", value: detailEntry && detailEntry.groupId },
                    { label: "Resource type", value: detailEntry && detailEntry.resourceType },
                    { label: "Role", value: detailEntry && detailEntry.role },
                    { label: "Classification source", value: detailEntry && tierSourceExplanation(detailEntry) }
                ];
                window.EntraOpsObjectInspector.open({
                    title: d.name,
                    reference: detailReference,
                    urlReference: canonicalReference,
                    updateUrl: !!canonicalReference,
                    tier: policyDetail ? policyDetail.approvalTier : ((detailEntry && detailEntry.tier) || d.tier),
                    roleReference: detailEntry && detailEntry.role,
                    tags: d.tags,
                    fallbackUserAccess: !!detailEntry && detailEntry.tier === "UserAccess",
                    fields: inspectorFields,
                    related: Array.from(d.flowIds).map(function (id) {
                        var flow = graph.flowsById.get(id);
                        return {
                            label: "Assignment policy: " + flow.name + " - Access package: " + flow.accessPackageName + (flow.catalogName ? " - Catalog: " + flow.catalogName : ""),
                            href: EntraOpsReportUtils.flowDeepLink(id)
                        };
                    })
                });
                renderSankey();
            });

        nodeSel.append("text")
            .attr("x", function (d) { return d.x0 < width / 2 ? d.x1 + 6 : d.x0 - 6; })
            .attr("y", function (d) { return (d.y0 + d.y1) / 2; })
            .attr("dy", "0.35em")
            .attr("text-anchor", function (d) { return d.x0 < width / 2 ? "start" : "end"; })
            .text(function (d) { return truncate(d.name, 42); })
            .each(function (d) {
                if (!d.tags.length) return;
                d3.select(this).append("tspan").attr("fill", "var(--viz-muted)").text(" ⓘ").append("title").text(d.tags.join("; "));
            })
            .filter(function (d) { return d.y1 - d.y0 < 8; })
            .remove();

        var colX = {};
        nodes.forEach(function (n) {
            if (!(n.column in colX)) colX[n.column] = [];
            colX[n.column].push((n.x0 + n.x1) / 2);
        });
        Object.keys(colX).forEach(function (c) {
            var cx = colX[c].reduce(function (a, b) { return a + b; }, 0) / colX[c].length;
            var words = COLUMNS[c].label.toUpperCase().split(" ");
            var splitAt = Math.ceil(words.length / 2);
            var lines = [words.slice(0, splitAt).join(" "), words.slice(splitAt).join(" ")].filter(Boolean);
            var heading = apSvg.append("text").attr("x", cx).attr("y", 0).attr("text-anchor", "middle")
                .attr("font-size", 11).attr("font-weight", 600).attr("fill", "var(--viz-muted)");
            lines.forEach(function (line, index) {
                heading.append("tspan").attr("x", cx).attr("dy", index ? "1.1em" : "0.8em").text(line);
            });
        });

        apSvg.on("click", function () {
            if (apState.traceNodeId) {
                apState.traceNodeId = null;
                apTraceFlowIds = null;
                $("apFlowDetail").classList.add("hidden");
                $("apGroupMemberDetail").classList.add("hidden");
                renderSankey();
            }
        });
    }

    // Populated by tieredList()/renderFlowDetail() each render, so the delegated "View members"
    // click handler (wired once, see onReady) can look up the full entry (incl. members[]) by a
    // small integer index embedded in the button's data attribute - simpler and safer than
    // stuffing a whole member array into a DOM attribute.
    var apMemberPanelData = [];

    function renderFlowDetail(policyId) {
        // Use the same target-type-filtered view of the flow as the Sankey (visibleFlow), so
        // the detail panel never lists targets the diagram is currently hiding.
        var f = currentFlows().filter(function (x) { return x.id === policyId; }).map(visibleFlow)[0];
        var el = $("apFlowDetail");
        if (!f) { el.classList.add("hidden"); return; }

        apMemberPanelData = [];

        function list(title, items) {
            if (!items || !items.length) return "";
            return "<div style='margin-bottom:6px;'><b>" + esc(title) + ":</b> " + items.map(esc).join(" · ") + "</div>";
        }
        function tieredList(title, items) {
            if (!items || !items.length) return "";
            var html = items.map(function (it) {
                var explain = tierSourceExplanation(it);
                var chip = it.tier ? ' <span class="status-chip modified" style="background:' + tierColor(it.tier) + ';color:#fff;" title="' + esc(explain) + '">' + esc(it.tier) + "</span>" : "";
                var memberBtn = "";
                if (it.members && it.members.length) {
                    var idx = apMemberPanelData.length;
                    apMemberPanelData.push(it);
                    memberBtn = ' <button type="button" class="btn small ap-view-members" data-member-idx="' + idx + '">View ' + it.members.length + (it.membersTruncated ? "+" : "") + " member" + (it.members.length === 1 ? "" : "s") + "</button>";
                }
                var groupId = it.groupId ? ' <code title="Requestor or approver group ID">' + esc(it.groupId) + "</code>" : "";
                var tag = it.tags && it.tags.length ? ' <span class="muted" title="' + esc(it.tags.join("; ")) + '">ⓘ</span>' : "";
                return '<span title="' + esc(explain) + '">' + esc(it.label) + "</span>" + tag + groupId + chip + memberBtn;
            }).join(" · ");
            return "<div style='margin-bottom:6px;'><b>" + esc(title) + ":</b> " + html + "</div>";
        }

        var html = '<div class="card" style="border-left:4px solid ' + (f.flags.some(function (fl) { return fl.severity === "fail"; }) ? "#a4262c" : (f.flags.length ? "#8a6d00" : "#0e700e")) + ';">';
        html += '<div class="card-head">' + esc(f.name) + '<span class="chip ' + (f.isApprovalRequired ? "brand" : "warn") + '">' + (f.isApprovalRequired ? "Approval required" : "No approval required") + "</span></div>";
        html += '<div class="card-pad" style="font-size:13px;">';
        html += list("Access package", [f.accessPackageName + (f.catalogName ? " (catalog: " + f.catalogName + ")" : "")]);
        html += tieredList("Applicable (who can request)", f.requestors);
        html += tieredList("Approver(s)", f.approvers);
        html += tieredList("Target resource role(s)", f.targets);
        if (f.hasAssignmentData) {
            html += f.assignedPrincipals.length
                ? tieredList("Assigned principal(s) (" + f.assignedCount + ")", f.assignedPrincipals)
                : list("Assigned (0)", ["none currently assigned"]);
        } else {
            html += "<div class='muted' style='font-size:12px;margin-bottom:6px;'>Generate <code>data/access-package-assignments-data.js</code> (New-EntraOpsAccessPackageFlowData) to see currently assigned principals.</div>";
        }
        html += list("Duration / extend / access review", [
            (f.durationInDays != null ? f.durationInDays + " day(s)" : "no fixed duration"),
            (f.canExtend ? "extendable" : "not extendable"),
            (f.accessReviewEnabled ? "access review enabled" : "no access review")
        ]);
        if (f.flags.length) {
            html += "<div style='margin-top:8px;'>" + f.flags.map(function (fl) {
                return '<div class="ca-gap-row"><span class="ca-gap-icon ' + (fl.severity === "fail" ? "fail" : "warn") + '">' + (fl.severity === "fail" ? "✕" : "!") + '</span><div class="ca-gap-detail">' + esc(fl.text) + "</div></div>";
            }).join("") + "</div>";
        }
        html += '<div class="muted" style="font-size:12px;margin-top:4px;">Source: <code>' + esc(f.resource.p) + "</code></div>";
        html += "</div></div>";
        el.innerHTML = html;
        el.classList.remove("hidden");
    }

    // ---- Group member detail panel (requestor/approver/target entries resolved via group
    // membership roll-up carry a members[] breakdown - see describeUserSet/pkg.targets). --------
    function renderGroupMemberPanel(entry) {
        var el = $("apGroupMemberDetail");
        if (!entry || !entry.members || !entry.members.length) { el.classList.add("hidden"); return; }

        var counts = {};
        entry.members.forEach(function (m) { counts[m.tierName] = (counts[m.tierName] || 0) + 1; });
        var summary = Object.keys(counts).sort(function (a, b) { return tierRank(a) - tierRank(b); }).map(function (t) {
            return '<span class="status-chip modified" style="background:' + tierColor(t) + ';color:#fff;">' + esc(t) + ": " + counts[t] + "</span>";
        }).join(" ");
        var rows = entry.members.map(function (m) {
            return "<tr><td>" + esc(m.displayName || m.id || "(unknown)") + '</td><td><span class="status-chip modified" style="background:' + tierColor(m.tierName) + ';color:#fff;">' + esc(m.tierName) + "</span></td></tr>";
        }).join("");

        var html = '<div class="card" style="border-left:4px solid #5c2d91;">';
        html += '<div class="card-head">' + esc(entry.label) + '<span class="chip brand">' + entry.members.length + (entry.membersTruncated ? "+" : "") + " member(s)</span></div>";
        html += '<div class="card-pad" style="font-size:13px;">';
        if (entry.groupId) html += '<div style="margin-bottom:8px;"><b>Group ID:</b> <code>' + esc(entry.groupId) + "</code></div>";
        html += '<div style="margin-bottom:8px;">' + summary + "</div>";
        html += '<p class="muted" style="font-size:12px;">' + esc(tierSourceExplanation(entry)) + "</p>";
        if (entry.membersTruncated) {
            html += '<p class="muted" style="font-size:12px;">Showing the first ' + entry.members.length + " of " + entry.totalMembers + " resolved member(s) - increase -MaxMembersPerGroup to see more.</p>";
        }
        html += '<div class="table-wrap"><table class="grid-table"><thead><tr><th>Member</th><th>Access tier (from EntraOps, defaults to User Access when not classified)</th></tr></thead><tbody>' + rows + "</tbody></table></div>";
        html += "</div></div>";
        el.innerHTML = html;
        el.classList.remove("hidden");
        el.scrollIntoView({ behavior: "smooth", block: "nearest" });
    }

    // =====================================================================================
    // Risk flags summary (mirrors the Conditional Access coverage gap list)
    // =====================================================================================
    function renderFlagsSummary(flows) {
        var el = $("apFlagsBody");
        if (!flows.length) { el.innerHTML = '<div class="muted">No access package assignment policies with embedded content in the selected snapshot.</div>'; return; }

        var flagged = flows.filter(function (f) { return f.flags.length > 0; });
        if (!flagged.length) {
            el.innerHTML = '<div class="ca-gap-row"><span class="ca-gap-icon ok">✓</span><div><div class="ca-gap-title">No risk flags found</div><div class="ca-gap-detail">Every access package assignment policy in this snapshot requires approval before granting a Control Plane / Management Plane resource, and no lower-tier approver was detected.</div></div></div>';
            return;
        }

        var rows = [];
        flagged.forEach(function (f) {
            f.flags.forEach(function (fl) {
                var tier = f.targets.reduce(function (best, target) {
                    return target.tier && tierRank(target.tier) < tierRank(best) ? target.tier : best;
                }, "Unclassified");
                rows.push({ flow: f, flag: fl, tier: tier, catalog: f.catalogName || "Unclassified / no catalog" });
            });
        });
        if (apFlagState.search) {
            var query = apFlagState.search.toLowerCase();
            rows = rows.filter(function (row) {
                return [row.flow.name, row.flow.accessPackageName, row.catalog, row.tier, row.flag.text].join(" ").toLowerCase().indexOf(query) !== -1;
            });
        }
        if (!rows.length) {
            el.innerHTML = '<div class="muted">No risk flags match the current search.</div>';
            return;
        }
        rows.sort(function (a, b) {
            if (apFlagState.sortBy === "severity") {
                var severityOrder = { fail: 0, warn: 1 };
                var severityDiff = severityOrder[a.flag.severity] - severityOrder[b.flag.severity];
                if (severityDiff) return severityDiff;
            } else if (apFlagState.sortBy === "tier") {
                var tierDiff = tierRank(a.tier) - tierRank(b.tier);
                if (tierDiff) return tierDiff;
            } else if (apFlagState.sortBy === "catalog") {
                var catalogDiff = a.catalog.localeCompare(b.catalog);
                if (catalogDiff) return catalogDiff;
            }
            return a.flow.name.localeCompare(b.flow.name) || a.flag.text.localeCompare(b.flag.text);
        });
        var groups = {};
        rows.forEach(function (row) {
            var key = apFlagState.groupBy === "tier" ? row.tier : (apFlagState.groupBy === "catalog" ? row.catalog : "All risk flags");
            if (!groups[key]) groups[key] = [];
            groups[key].push(row);
        });
        var groupNames = Object.keys(groups).sort(function (a, b) {
            return apFlagState.groupBy === "tier" ? tierRank(a) - tierRank(b) : a.localeCompare(b);
        });
        if (apFlagState.collapseStateGroupBy !== apFlagState.groupBy) {
            apFlagState.collapsedGroups = new Set(groupNames);
            apFlagState.collapseStateGroupBy = apFlagState.groupBy;
        }
        var html = "";
        groupNames.forEach(function (group) {
            var isCollapsed = apFlagState.collapsedGroups.has(group);
            var counts = { fail: 0, warn: 0 };
            groups[group].forEach(function (row) { counts[row.flag.severity]++; });
            var pills = (counts.fail ? '<span class="ap-risk-stat-pill fail">&#10005; ' + counts.fail + '</span>' : "") + (counts.warn ? '<span class="ap-risk-stat-pill warn">! ' + counts.warn + '</span>' : "");
            html += '<div class="ap-risk-area"><button type="button" class="ap-risk-area-head" data-ap-risk-group="' + esc(group) + '" aria-expanded="' + (!isCollapsed) + '"><span class="ap-risk-chevron">' + (isCollapsed ? "&#9656;" : "&#9662;") + '</span><span class="ap-risk-title">' + esc(group) + '</span><span class="ap-risk-stats">' + pills + '</span></button><div class="ap-risk-area-body' + (isCollapsed ? " collapsed" : "") + '">';
            groups[group].forEach(function (row) {
                var f = row.flow, fl = row.flag;
                var metadata = f.accessPackageName + " · " + row.catalog + " · " + row.tier;
                html += '<div class="ca-gap-row"><span class="ca-gap-icon ' + (fl.severity === "fail" ? "fail" : "warn") + '">' + (fl.severity === "fail" ? "✕" : "!") + '</span>' +
                    '<div><div class="ca-gap-title">' + esc(f.name) + ' <span class="muted" style="font-size:11px;">(' + esc(metadata) + ')</span> ' + EntraOpsReportUtils.reviewControl("access-package-flow", f.id + "|" + fl.id) + '</div>' +
                    '<div class="ca-gap-detail">' + esc(fl.text) + ' · <a href="../ConfigurationAnalyzer/index.html?view=resources#resource=' + apState.snapshotIdx + "|" + encodeURIComponent(f.resource.p) + '">Inspect source resource</a></div></div></div>';
            });
            html += "</div></div>";
        });
        html += '<p class="muted" style="font-size:12px;margin-top:10px;">Tier-comparison flags are computed only from approver/target identities that resolve to a known object id in the optional EAM Dashboard dataset - unresolved subjects (e.g. an external group without a captured classification) are shown with the User Access default tier but are excluded from the lower-tier approver comparison and never flagged on tier alone.</p>';
        el.innerHTML = html;
        EntraOpsReportUtils.bindReviewControls(el);
    }

    function applyFlowDeepLink() {
        var flowId = EntraOpsReportUtils.flowReferenceFromHash();
        if (!flowId) return;
        var flow = currentFlows().filter(function (item) { return item.id === flowId; })[0];
        if (!flow) {
            var previousIdx = apState.snapshotIdx;
            var detailIdxs = detailedSnapshotIdxs();
            for (var index = detailIdxs.length - 1; index >= 0 && !flow; index--) {
                apState.snapshotIdx = detailIdxs[index];
                flow = currentFlows().filter(function (item) { return item.id === flowId; })[0];
            }
            if (flow) renderControls();
            else apState.snapshotIdx = previousIdx;
        }
        if (!flow) return;
        apState.traceNodeId = "policy|" + flowId;
        apTraceFlowIds = new Set([flowId]);
        renderSankey();
        renderFlowDetail(flowId);
        $("secApSankey").scrollIntoView({ block: "start" });
    }

    // =====================================================================================
    // Wiring + init
    // =====================================================================================
    function onReady(fn) {
        if (document.readyState !== "loading") fn();
        else document.addEventListener("DOMContentLoaded", fn);
    }

    onReady(function () {
        var navToggle = $("navToggle");
        var nav = $("nav");
        if (navToggle && nav) navToggle.addEventListener("click", function () { nav.classList.toggle("open"); });
        document.querySelectorAll(".nav-item.section-item").forEach(function (item) {
            item.addEventListener("click", function () {
                var target = document.getElementById(item.getAttribute("data-target"));
                if (target) target.scrollIntoView({ behavior: "smooth", block: "start" });
                if (nav) nav.classList.remove("open");
            });
            item.addEventListener("keydown", function (ev) {
                if (ev.key !== "Enter" && ev.key !== " ") return;
                ev.preventDefault();
                item.click();
            });
        });

        if (!DATA || !snapshots.length) return; // empty state stays visible

        $("apEmptyState").classList.add("hidden");
        $("apContent").classList.remove("hidden");

        var detailIdxs = detailedSnapshotIdxs();
        if (detailIdxs.length) apState.snapshotIdx = detailIdxs[detailIdxs.length - 1];

        renderControls();
        renderSankey();
        window.addEventListener("hashchange", applyFlowDeepLink);
        applyFlowDeepLink();

        $("apSnapshot").addEventListener("change", function () {
            apState.snapshotIdx = Number(this.value);
            apState.traceNodeId = null;
            apTraceFlowIds = null;
            apState.approvalFilter = "";
            apState.expirationFilter = "";
            apState.flagFilter = "";
            apState.metricFilter = "all";
            apState.requestorTierFilter = "";
            apState.memberTierFilter = "";
            apState.catalogFilter = "";
            apState.targetTypeFilter = "";
            ["apFltApproval", "apFltExpiration", "apFltRequestorTier", "apFltMemberTier", "apFltTargetType"].forEach(function (id) { $(id).value = ""; });
            $("apFlowDetail").classList.add("hidden");
            $("apGroupMemberDetail").classList.add("hidden");
            renderControls();
            renderSankey();
        });
        $("apColToggles").addEventListener("keydown", function (ev) {
            if (ev.key !== "Enter" && ev.key !== " ") return;
            var t = ev.target.closest(".ca-toggle");
            if (!t) return;
            ev.preventDefault();
            t.click();
        });
        $("apColToggles").addEventListener("click", function (ev) {
            var t = ev.target.closest("[data-col]");
            if (!t) return;
            var c = t.getAttribute("data-col");
            if (apState.columns.has(c)) {
                if (apState.columns.size <= 2) return;
                apState.columns.delete(c);
            } else apState.columns.add(c);
            apState.traceNodeId = null;
            apTraceFlowIds = null;
            renderControls();
            renderSankey();
        });
        $("apFltApproval").addEventListener("change", function () { apState.approvalFilter = this.value; renderSankey(); });
        $("apFltExpiration").addEventListener("change", function () { apState.expirationFilter = this.value; renderSankey(); });
        $("apFltFlag").addEventListener("change", function () { apState.flagFilter = this.value; apState.metricFilter = "all"; renderSankey(); });
        $("apFltRequestorTier").addEventListener("change", function () { apState.requestorTierFilter = this.value; renderSankey(); });
        $("apFltMemberTier").addEventListener("change", function () { apState.memberTierFilter = this.value; renderSankey(); });
        $("apFltCatalog").addEventListener("change", function () { apState.catalogFilter = this.value; renderSankey(); });
        $("apFltTargetType").addEventListener("change", function () { apState.targetTypeFilter = this.value; renderSankey(); });
        document.querySelectorAll("[data-ap-metric]").forEach(function (tile) {
            tile.addEventListener("click", function () {
                var metric = tile.getAttribute("data-ap-metric");
                if (metric === "all" || apState.metricFilter === metric) apState.metricFilter = "all";
                else {
                    apState.metricFilter = metric;
                    apState.flagFilter = "";
                }
                apState.traceNodeId = null;
                apTraceFlowIds = null;
                renderControls();
                renderSankey();
            });
        });
        $("apFlagGroup").addEventListener("change", function () { apFlagState.groupBy = this.value; renderFlagsSummary(currentFlows()); });
        $("apFlagSort").addEventListener("change", function () { apFlagState.sortBy = this.value; renderFlagsSummary(currentFlows()); });
        $("apFlagsBody").addEventListener("click", function (ev) {
            var groupHead = ev.target.closest("[data-ap-risk-group]");
            if (!groupHead) return;
            var group = groupHead.getAttribute("data-ap-risk-group");
            if (apFlagState.collapsedGroups.has(group)) apFlagState.collapsedGroups.delete(group);
            else apFlagState.collapsedGroups.add(group);
            renderFlagsSummary(currentFlows());
        });
        $("apExpandAllRiskGroups").addEventListener("click", function () {
            apFlagState.collapsedGroups.clear();
            renderFlagsSummary(currentFlows());
        });
        $("apCollapseAllRiskGroups").addEventListener("click", function () {
            var query = apFlagState.search.toLowerCase();
            var groups = new Set();
            currentFlows().forEach(function (flow) {
                var tier = flow.targets.reduce(function (best, target) { return target.tier && tierRank(target.tier) < tierRank(best) ? target.tier : best; }, "Unclassified");
                var catalog = flow.catalogName || "Unclassified / no catalog";
                flow.flags.forEach(function (flag) {
                    if (query && [flow.name, flow.accessPackageName, catalog, tier, flag.text].join(" ").toLowerCase().indexOf(query) === -1) return;
                    groups.add(apFlagState.groupBy === "tier" ? tier : (apFlagState.groupBy === "catalog" ? catalog : "All risk flags"));
                });
            });
            apFlagState.collapsedGroups = groups;
            renderFlagsSummary(currentFlows());
        });
        var flagSearchTimer = null;
        $("apFlagSearch").addEventListener("input", function () {
            var value = this.value;
            clearTimeout(flagSearchTimer);
            flagSearchTimer = setTimeout(function () { apFlagState.search = value.trim(); renderFlagsSummary(currentFlows()); }, 180);
        });
        var searchTimer = null;
        $("apFltSearch").addEventListener("input", function () {
            var v = this.value;
            clearTimeout(searchTimer);
            searchTimer = setTimeout(function () { apState.search = v.trim(); renderSankey(); }, 180);
        });
        $("apClearTrace").addEventListener("click", function () {
            apState.traceNodeId = null;
            apTraceFlowIds = null;
            $("apFlowDetail").classList.add("hidden");
            $("apGroupMemberDetail").classList.add("hidden");
            renderSankey();
        });
        $("apResetFilters").addEventListener("click", function () {
            apState.approvalFilter = "";
            apState.expirationFilter = "";
            apState.flagFilter = "";
            apState.metricFilter = "all";
            apState.requestorTierFilter = "";
            apState.memberTierFilter = "";
            apState.catalogFilter = "";
            apState.targetTypeFilter = "";
            apState.search = "";
            apState.traceNodeId = null;
            apTraceFlowIds = null;
            ["apFltApproval", "apFltExpiration", "apFltRequestorTier", "apFltMemberTier", "apFltTargetType", "apFltSearch", "apFlagSearch"].forEach(function (id) { $(id).value = ""; });
            apFlagState.search = "";
            $("apFlowDetail").classList.add("hidden");
            $("apGroupMemberDetail").classList.add("hidden");
            renderControls();
            renderSankey();
        });
        $("apExportFiltered").addEventListener("click", function () {
            var rows = currentFlows().filter(flowMatchesFilters).map(visibleFlow).map(function (flow) {
                return { snapshot: snapshotLabel(snapshots[apState.snapshotIdx], apState.snapshotIdx), policy: flow.name, catalog: flow.catalogName || "", accessPackage: flow.accessPackageName, requestors: flow.requestors.map(function (entry) { return entry.label; }).join("; "), approvers: flow.approvers.map(function (entry) { return entry.label; }).join("; "), targets: flow.targets.map(function (entry) { return entry.label; }).join("; "), targetResourceTypes: Array.from(new Set(flow.targets.map(function (entry) { return entry.targetType; }))).join("; "), approvalRequired: flow.isApprovalRequired, durationInDays: flow.durationInDays, riskFlags: flow.flags.map(function (flag) { return flag.id; }).join("; ") };
            });
            EntraOpsReportUtils.exportRows("entraops-access-package-flow-filtered", rows);
        });
        $("apExportRiskFlags").addEventListener("click", function () {
            var query = apFlagState.search.toLowerCase();
            var rows = [];
            currentFlows().forEach(function (flow) {
                var tier = flow.targets.reduce(function (best, target) { return target.tier && tierRank(target.tier) < tierRank(best) ? target.tier : best; }, "Unclassified");
                flow.flags.forEach(function (flag) {
                    var catalog = flow.catalogName || "Unclassified / no catalog";
                    if (query && [flow.name, flow.accessPackageName, catalog, tier, flag.text].join(" ").toLowerCase().indexOf(query) === -1) return;
                    rows.push({ snapshot: snapshotLabel(snapshots[apState.snapshotIdx], apState.snapshotIdx), policy: flow.name, catalog: catalog, accessPackage: flow.accessPackageName, accessLevel: tier, severity: flag.severity, flag: flag.id, detail: flag.text, sourceResource: flow.resource.p });
                });
            });
            EntraOpsReportUtils.exportRows("entraops-access-package-risk-flags", rows);
        });
        $("apFlowDetail").addEventListener("click", function (ev) {
            var btn = ev.target.closest(".ap-view-members");
            if (!btn) return;
            var idx = Number(btn.getAttribute("data-member-idx"));
            renderGroupMemberPanel(apMemberPanelData[idx]);
        });
    });
})();
