/*
 * EntraOps PIM Request Flow
 *
 * Visualizes the Entra ID PIM (Privileged Identity Management) role settings of a captured
 * EntraOps Tenant Governance snapshot (see Reports/ConfigurationAnalyzer, generated by
 * New-EntraOpsTenantGovernanceConfigurationAnalyzerData) as a filterable Sankey flow:
 *
 *   Role -> Assignment path -> Requirement(s) -> Approval -> Notification(s)
 *
 * mirroring the Conditional Access Analysis / Access Package Flow apps. Every captured
 * microsoft.entra.rolesetting resource is expanded into up to three "assignment path" flows -
 * the three ways a principal ends up holding the role, each governed by its own slice of PIM
 * role settings (see EntraOps/Public/TenantGovernance snapshot schema and the M365DSC
 * AADRoleSetting resource):
 *
 *   - "Activate eligible role"  (ActivationReq* / ApprovaltoActivate / ActivateApprover /
 *     AuthenticationContext* + the Eligible*Notification* group) - the self-service PIM
 *     request: an eligible member activates the role for a limited time, optionally requiring
 *     MFA, justification, a ticket number, an authentication context and/or approval.
 *   - "Assign eligible role"   (ElegibilityAssignmentReq* / ExpireEligibleAssignment /
 *     PermanentEligibleAssignmentisExpirationRequired + the EligibleAssignment*Notification*
 *     group) - an administrator grants a principal eligibility for the role.
 *   - "Assign active role"     (AssignmentReq* / ExpireActiveAssignment /
 *     PermanentActiveAssignmentisExpirationRequired + the Active*Notification* group) - an
 *     administrator grants a principal the role directly as an active (non-eligible)
 *     assignment.
 *
 * The role definition (microsoft.entra.roledefinition, joined on Id/TemplateId) supplies the
 * role's description. The role's access tier (Control Plane / Management Plane / User Access)
 * starts with Classification Explorer's generated role catalog. The optional EAM Dashboard
 * dataset then overrides it with tenant/scope-specific classified assignment evidence and
 * resolves activation approvers. This reuses EntraOps classification output instead of
 * re-implementing the role-action classification rule engine client-side.
 *
 * Reuses the snapshot/blob parsing model from ../ConfigurationAnalyzer/js/core.js (loaded
 * before this file - see index.html).
 */
(function () {
    "use strict";

    var RT = {
        roleSetting: "microsoft.entra.rolesetting",
        roleDefinition: "microsoft.entra.roledefinition"
    };

    var TIER_COLORS = { ControlPlane: "#a4262c", ManagementPlane: "#c07807", UserAccess: "#0e700e", Unclassified: "#a19f9d" };
    function tierColor(tier) { return TIER_COLORS[tier] || "#a19f9d"; }

    var PATH_COLORS = { activation: "#0078d4", eligibleAssignment: "#5c2d91", activeAssignment: "#038387" };
    var APPROVAL_COLORS = { "Approval required": "#0e700e", "No approval required": "#c07807" };
    var excludedRiskFlagIds = new Set((DATA && Array.isArray(DATA.pimRequestFlowExcludedRiskFlags) ? DATA.pimRequestFlowExcludedRiskFlags : []).map(String));

    // ---- Role tier indexes from Classification Explorer, with optional EAM enrichment. ----
    var roleDefinitionTierIndex = new Map();
    var roleActionTierIndex = new Map();
    (function buildRoleDefinitionTierIndex() {
        var tierMapRoles = window.EOCE_TIER_MAP && Array.isArray(window.EOCE_TIER_MAP.roles) ? window.EOCE_TIER_MAP.roles : [];
        tierMapRoles.forEach(function (role) {
            if (String(role.sys).toLowerCase() !== "entraid" || !role.roleId || !role.roleClass || role.roleClass === "Unclassified") return;
            roleDefinitionTierIndex.set(String(role.roleId).toUpperCase(), {
                tierName: role.roleClass,
                service: role.service || "Entra ID directory role catalog"
            });
        });
        var tierMapPaths = window.EOCE_TIER_MAP && Array.isArray(window.EOCE_TIER_MAP.paths) ? window.EOCE_TIER_MAP.paths : [];
        tierMapPaths.forEach(function (path) {
            if (String(path.sys).toLowerCase() !== "entraid") return;
            if (path.action && path.tier && path.tier !== "Unclassified") {
                var actionKey = String(path.action).toLowerCase();
                var actionCurrent = roleActionTierIndex.get(actionKey);
                if (!actionCurrent || tierRank(path.tier) < tierRank(actionCurrent.tierName)) {
                    roleActionTierIndex.set(actionKey, {
                        tierName: path.tier,
                        service: path.service || "Entra ID directory role action"
                    });
                }
            }
            if (!path.roleId) return;
            var tierName = path.roleClass || path.tier;
            if (!tierName || tierName === "Unclassified") return;
            var key = String(path.roleId).toUpperCase();
            var current = roleDefinitionTierIndex.get(key);
            if (!current || tierRank(tierName) < tierRank(current.tierName)) {
                roleDefinitionTierIndex.set(key, {
                    tierName: tierName,
                    service: path.service || "Entra ID directory role catalog"
                });
            }
        });
        if (!EAM_DATA) return;
        (Array.isArray(EAM_DATA.roleDefinitions) ? EAM_DATA.roleDefinitions : []).forEach(function (role) {
            if (!role.roleDefinitionId || !role.tierName) return;
            roleDefinitionTierIndex.set(String(role.roleDefinitionId).toUpperCase(), {
                tierName: role.tierName,
                service: role.service || "Entra ID directory role"
            });
        });
        if (!Array.isArray(EAM_DATA.objects)) return;
        var votes = new Map(); // uppercased roleDefinitionId -> Map("tierName|service" -> count)
        EAM_DATA.objects.forEach(function (o) {
            (Array.isArray(o.roleAssignments) ? o.roleAssignments : []).forEach(function (ra) {
                if (!ra.roleDefinitionId) return;
                var cls = Array.isArray(ra.classification) ? ra.classification : [];
                if (!cls.length) return;
                // An assignment can match several classification entries (several services) -
                // the most-privileged (lowest tierRank) one determines the role's tier for this
                // assignment, same "worst case wins" rule the classification engine itself uses.
                var best = cls.reduce(function (acc, c) {
                    var r = tierRank(c.adminTierLevelName);
                    return r < acc.rank ? { rank: r, tierName: c.adminTierLevelName, service: c.service } : acc;
                }, { rank: TIER_ORDER.length, tierName: null, service: null });
                if (!best.tierName) return;
                var key = String(ra.roleDefinitionId).toUpperCase();
                if (!votes.has(key)) votes.set(key, new Map());
                var vkey = best.tierName + "|" + (best.service || "");
                votes.get(key).set(vkey, (votes.get(key).get(vkey) || 0) + 1);
            });
        });
        votes.forEach(function (m, key) {
            var best = null;
            m.forEach(function (count, vkey) {
                var sep = vkey.indexOf("|");
                var tierName = vkey.slice(0, sep), service = vkey.slice(sep + 1);
                var rank = tierRank(tierName);
                if (!best || rank < best.rank) best = { tierName: tierName, rank: rank, service: service };
            });
            // Classified assignment evidence includes tenant overwrites and scope-specific
            // evaluation, so it supersedes the catalog fallback for assigned roles.
            if (best) roleDefinitionTierIndex.set(key, { tierName: best.tierName, service: best.service });
        });
    })();

    function tierForRoleDefinition(roleDef) {
        if (!roleDef || !Array.isArray(roleDef.rolePermissions)) return null;
        var actions = roleDef.rolePermissions.flatMap(function (permission) {
            if (typeof permission === "string") return [permission];
            return Array.isArray(permission.AllowedResourceActions) ? permission.AllowedResourceActions : [];
        });
        return actions.reduce(function (best, action) {
            var candidate = roleActionTierIndex.get(String(action).toLowerCase());
            return candidate && (!best || tierRank(candidate.tierName) < tierRank(best.tierName)) ? candidate : best;
        }, null);
    }

    function describeApprover(upn) {
        var upper = String(upn).toUpperCase();
        var hit = objectUpnIndex.get(upper) || objectDisplayNameIndex.get(upper);
        return {
            label: hit ? hit.displayName + " (" + upn + ")" : String(upn),
            tier: hit ? hit.tierName : "UserAccess", // not covered by EntraOps => User Access (see core.js identityTierFor)
            resolved: !!hit,
            source: hit ? "direct" : "default"
        };
    }

    function fmtIsoDuration(iso) {
        if (!iso) return "not set";
        var m = /^P(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?)?$/.exec(iso);
        if (!m) return iso;
        var labels = ["year", "month", "day", "hour", "minute", "second"];
        var parts = [];
        for (var i = 1; i <= 6; i++) {
            if (m[i]) parts.push(m[i] + " " + labels[i - 1] + (m[i] === "1" ? "" : "s"));
        }
        return parts.length ? parts.join(" ") : iso;
    }

    function activationRequirements(p) {
        var reqs = [];
        if (p.ActivationReqMFA) reqs.push("MFA required");
        if (p.ActivationReqJustification) reqs.push("Justification required");
        if (p.ActivationReqTicket) reqs.push("Ticket information required");
        if (p.AuthenticationContextRequired) reqs.push(p.AuthenticationContextName ? "Authentication context: " + p.AuthenticationContextName : "Authentication context required");
        if (!reqs.length) reqs.push("No additional requirement");
        return reqs;
    }
    function simpleRequirements(p, justificationField, mfaField) {
        var reqs = [];
        if (p[mfaField]) reqs.push("MFA required");
        if (p[justificationField]) reqs.push("Justification required");
        if (!reqs.length) reqs.push("No additional requirement");
        return reqs;
    }

    // prefix: "Eligible" | "EligibleAssignment" | "Active" - see file header comment for how
    // these three notification field groups map to the three assignment paths.
    function notificationList(p, prefix, includeApprove) {
        var out = [];
        function add(role, label) {
            var def = !!p[prefix + role + "NotificationDefaultRecipient"];
            var extra = p[prefix + role + "NotificationAdditionalRecipient"] || [];
            var onlyCritical = !!p[prefix + role + "NotificationOnlyCritical"];
            if (def || extra.length) {
                out.push(label + " notified" + (extra.length ? " (+" + extra.length + " additional)" : "") + (onlyCritical ? " · critical only" : ""));
            }
        }
        add("Alert", "Admin");
        if (includeApprove) add("Approve", "Approver");
        add("Assignee", "Requestor");
        if (!out.length) out.push("No notifications configured");
        return out;
    }

    // =====================================================================================
    // Assignment path definitions - one microsoft.entra.rolesetting resource expands into up
    // to three flow records, one per path, so the Sankey can show how requirements, approval
    // and notifications differ between activating an eligible role vs. an admin directly
    // granting eligible/active access.
    // =====================================================================================
    var PATH_DEFS = [
        {
            key: "activation", order: 0, label: "Activate eligible role", shortLabel: "Activation",
            description: "Self-service PIM request: an eligible member activates the role for a limited time.",
            build: function (p, roleDef, resource, roleId, roleName) {
                var approvers = (Array.isArray(p.ActivateApprover) ? p.ActivateApprover : []).map(describeApprover);
                return {
                    id: (roleId || resource.p) + "|activation", path: "activation", pathOrder: 0, pathLabel: "Activate eligible role", pathShortLabel: "Activation",
                    roleId: roleId, roleName: roleName, resource: resource, roleDef: roleDef,
                    requirements: activationRequirements(p),
                    approvalRequired: !!p.ApprovaltoActivate,
                    approvalLabel: p.ApprovaltoActivate ? "Approval required" : "No approval required",
                    approvers: approvers,
                    notifications: notificationList(p, "Eligible", true),
                    duration: "Max activation duration: " + fmtIsoDuration(p.ActivationMaxDuration),
                    raw: p
                };
            }
        },
        {
            key: "eligibleAssignment", order: 1, label: "Assign eligible role", shortLabel: "Eligible assignment",
            description: "An administrator grants a principal eligibility for this role (PIM eligible assignment).",
            build: function (p, roleDef, resource, roleId, roleName) {
                return {
                    id: (roleId || resource.p) + "|eligibleAssignment", path: "eligibleAssignment", pathOrder: 1, pathLabel: "Assign eligible role", pathShortLabel: "Eligible assignment",
                    roleId: roleId, roleName: roleName, resource: resource, roleDef: roleDef,
                    requirements: simpleRequirements(p, "ElegibilityAssignmentReqJustification", "ElegibilityAssignmentReqMFA"),
                    approvalRequired: false,
                    approvalLabel: "No approval workflow (admin-assigned)",
                    approvers: [],
                    notifications: notificationList(p, "EligibleAssignment", false),
                    duration: "Expires after: " + (p.PermanentEligibleAssignmentisExpirationRequired === false ? fmtIsoDuration(p.ExpireEligibleAssignment) + " (permanent allowed)" : fmtIsoDuration(p.ExpireEligibleAssignment) + " (expiration required)"),
                    raw: p
                };
            }
        },
        {
            key: "activeAssignment", order: 2, label: "Assign active role", shortLabel: "Active assignment",
            description: "An administrator grants a principal this role directly as an active (non-eligible) assignment.",
            build: function (p, roleDef, resource, roleId, roleName) {
                return {
                    id: (roleId || resource.p) + "|activeAssignment", path: "activeAssignment", pathOrder: 2, pathLabel: "Assign active role", pathShortLabel: "Active assignment",
                    roleId: roleId, roleName: roleName, resource: resource, roleDef: roleDef,
                    requirements: simpleRequirements(p, "AssignmentReqJustification", "AssignmentReqMFA"),
                    approvalRequired: false,
                    approvalLabel: "No approval workflow (admin-assigned)",
                    approvers: [],
                    notifications: notificationList(p, "Active", true),
                    duration: "Expires after: " + (p.PermanentActiveAssignmentisExpirationRequired === false ? fmtIsoDuration(p.ExpireActiveAssignment) + " (permanent allowed)" : fmtIsoDuration(p.ExpireActiveAssignment) + " (expiration required)"),
                    raw: p
                };
            }
        }
    ];

    function computeFlagsForFlow(flow, p, pathKey, roleTier) {
        var flags = [];
        var privileged = roleTier === "ControlPlane" || roleTier === "ManagementPlane";
        var roleRank = tierRank(roleTier);
        if (pathKey === "activation") {
            if (privileged && !p.ActivationReqMFA) {
                flags.push({ id: "noMfaActivation", severity: "fail", text: "Privileged role (" + roleTier + ") can be activated without requiring MFA." });
            }
            if (privileged && !p.ApprovaltoActivate) {
                flags.push({ id: "noApprovalActivation", severity: "fail", text: "Privileged role (" + roleTier + ") can be activated without approval." });
            }
            if (!p.ApprovaltoActivate && Array.isArray(p.ActivateApprover) && p.ActivateApprover.length) {
                flags.push({ id: "approverNotEnforced", severity: "warn", text: "Approver(s) are configured (" + p.ActivateApprover.length + ") but 'Require approval to activate' is disabled - the approver list has no effect." });
            }
            if (p.ApprovaltoActivate && roleRank < TIER_ORDER.length) {
                var lowerTier = flow.approvers.filter(function (a) { return a.source === "direct" && a.tier && tierRank(a.tier) > roleRank; });
                if (lowerTier.length) {
                    flags.push({ id: "approverLowerTier", severity: "warn", text: "Approver(s) classified at a lower access tier than the role being activated: " + lowerTier.map(function (a) { return a.label; }).join(", ") + "." });
                }
            }
            if (p.ApprovaltoActivate) {
                var unresolvedApprovers = flow.approvers.filter(function (a) { return !a.resolved; });
                if (unresolvedApprovers.length) {
                    flags.push({ id: "approverUnclassified", severity: "warn", text: unresolvedApprovers.length + " approver(s) could not be resolved against the EAM dataset - tier comparison skipped for them." });
                }
            }
            if (p.AuthenticationContextRequired && !p.AuthenticationContextName) {
                flags.push({ id: "authContextMissing", severity: "warn", text: "Authentication context is required but no context is configured." });
            }
        } else if (pathKey === "eligibleAssignment") {
            if (privileged && p.PermanentEligibleAssignmentisExpirationRequired === false) {
                flags.push({ id: "permanentEligible", severity: "warn", text: "A permanent (non-expiring) eligible assignment is allowed for a privileged role (" + roleTier + ")." });
            }
        } else if (pathKey === "activeAssignment") {
            if (privileged && p.PermanentActiveAssignmentisExpirationRequired === false) {
                flags.push({ id: "permanentActive", severity: "warn", text: "A permanent (non-expiring) active assignment is allowed for a privileged role (" + roleTier + ")." });
            }
            if (privileged && !p.AssignmentReqMFA) {
                flags.push({ id: "noMfaActiveAssign", severity: "warn", text: "Privileged role (" + roleTier + ") can be assigned directly as Active without requiring MFA at assignment time." });
            }
        }
        return flags;
    }

    // ---- Parse one snapshot's role settings + role definitions into the flow model ----------
    var pimCache = {};
    function pimModelForSnapshot(snap) {
        var key = snap.commitSha + "|" + snap.commitDate;
        if (pimCache[key]) return pimCache[key];

        var roleDefs = {}, roleSettings = [];
        snap.resources.forEach(function (r) {
            var type = String(r.type).toLowerCase();
            if (type !== RT.roleSetting && type !== RT.roleDefinition) return;
            var blob = blobContent(r.h);
            if (blob === undefined || blob === null) return;
            var p = blob.properties || {};
            if (type === RT.roleDefinition) {
                var id = p.Id || p.TemplateId;
                if (id) roleDefs[id] = { id: id, displayName: p.DisplayName || r.name, description: p.Description || "", rolePermissions: Array.isArray(p.RolePermissions) ? p.RolePermissions : [], resource: r };
            } else {
                roleSettings.push({ p: p, resource: r });
            }
        });

        var flows = [];
        roleSettings.forEach(function (item) {
            var p = item.p;
            var roleId = p.Id;
            var roleDef = roleId ? roleDefs[roleId] : null;
            var roleName = p.DisplayName || (roleDef ? roleDef.displayName : item.resource.name);
            var tierHit = roleId ? roleDefinitionTierIndex.get(String(roleId).toUpperCase()) : null;
            if (!tierHit) tierHit = tierForRoleDefinition(roleDef);
            var roleTier = tierHit ? tierHit.tierName : null;
            var roleTierService = tierHit ? tierHit.service : null;

            PATH_DEFS.forEach(function (pathDef) {
                var flow = pathDef.build(p, roleDef, item.resource, roleId, roleName);
                flow.roleTier = roleTier;
                flow.roleTierService = roleTierService;
                flow.flags = computeFlagsForFlow(flow, p, pathDef.key, roleTier).filter(function (flag) { return !excludedRiskFlagIds.has(flag.id); });
                flows.push(flow);
            });
        });

        flows.sort(function (a, b) { return a.roleName.localeCompare(b.roleName) || a.pathOrder - b.pathOrder; });
        pimCache[key] = { flows: flows, roleCount: roleSettings.length, roleDefCount: Object.keys(roleDefs).length };
        return pimCache[key];
    }

    // =====================================================================================
    // State + filters
    // =====================================================================================
    var pimState = {
        snapshotIdx: -1,
        columns: new Set(["role", "path", "requirement", "approval", "notification"]),
        pathFilter: new Set(["activation", "eligibleAssignment", "activeAssignment"]),
        tierFilter: "",
        approvalFilter: "",
        flagFilter: "",
        metricFilter: "all",
        requirementFilter: "",
        search: "",
        traceNodeId: null
    };
    var pimFlagState = { groupBy: "tier", sortBy: "severity", search: "", collapsedGroups: new Set(), collapseStateGroupBy: null };

    var COLUMN_ORDER = ["role", "path", "requirement", "approval", "notification"];
    var COLUMNS = {
        role: { label: "Role", values: function (f) { return [f.roleName]; } },
        path: { label: "Assignment path", values: function (f) { return [f.pathLabel]; } },
        requirement: { label: "Requirement", values: function (f) { return f.requirements; } },
        approval: { label: "Approval", values: function (f) { return [f.approvalLabel]; } },
        notification: { label: "Notification", values: function (f) { return f.notifications; } }
    };

    function currentFlows() {
        if (pimState.snapshotIdx < 0) return [];
        return pimModelForSnapshot(snapshots[pimState.snapshotIdx]).flows;
    }

    function flowMatchesFilters(f) {
        if (!pimState.pathFilter.has(f.path)) return false;
        if (pimState.tierFilter) {
            var wantUnclassified = pimState.tierFilter === "Unclassified";
            if (wantUnclassified ? !!f.roleTier : f.roleTier !== pimState.tierFilter) return false;
        }
        if (pimState.approvalFilter === "required" && !f.approvalRequired) return false;
        if (pimState.approvalFilter === "none" && f.approvalRequired) return false;
        if (pimState.flagFilter && !f.flags.some(function (fl) { return fl.id === pimState.flagFilter; })) return false;
        if (pimState.metricFilter === "anyRisk" && !f.flags.length) return false;
        if (pimState.requirementFilter && f.requirements.indexOf(pimState.requirementFilter) === -1) return false;
        if (pimState.search) {
            var q = pimState.search.toLowerCase();
            var hay = [f.roleName, f.pathLabel, f.approvalLabel].concat(
                f.requirements, f.notifications, f.approvers.map(function (a) { return a.label; })
            ).join("   ").toLowerCase();
            if (hay.indexOf(q) === -1) return false;
        }
        return true;
    }

    function nodeId(col, label, flow) {
        return col === "path" ? "path|" + flow.id : col + "|" + label;
    }

    function nodeColor(n, flowsById) {
        if (n.column === "role") return tierColor(n.tier);
        if (n.column === "path") {
            var f = flowsById.get(n.id.slice("path|".length));
            if (f && f.flags.some(function (fl) { return fl.severity === "fail"; })) return "#a4262c";
            if (f && f.flags.length) return "#8a6d00";
            return (f && PATH_COLORS[f.path]) || "#5c2d91";
        }
        if (n.column === "approval") return APPROVAL_COLORS[n.name] || "#605e5c";
        if (n.column === "requirement") return "#5c2d91";
        if (n.column === "notification") return "#038387";
        return "#5c2d91";
    }

    function buildGraph(flows) {
        var activeCols = COLUMN_ORDER.filter(function (c) { return pimState.columns.has(c); });
        var nodeMap = new Map();
        var linkMap = new Map();
        var flowsById = new Map();
        flows.forEach(function (f) { flowsById.set(f.id, f); });

        function ensureNode(col, label, f) {
            var id = nodeId(col, label, f);
            if (!nodeMap.has(id)) {
                // No cross-cutting relationship data (e.g. group/CA membership) is available for
                // PIM role settings yet - every role/path node would otherwise get a tag that just
                // restates its own column, so nodes stay untagged until a genuine signal exists.
                nodeMap.set(id, { id: id, name: label, column: col, tier: col === "role" ? f.roleTier : null, flowIds: new Set(), tags: [] });
            }
            nodeMap.get(id).flowIds.add(f.id);
            return id;
        }

        flows.forEach(function (f) {
            var perCol = activeCols.map(function (c) {
                return COLUMNS[c].values(f).map(function (label) { return ensureNode(c, label, f); });
            });
            for (var i = 0; i < perCol.length - 1; i++) {
                perCol[i].forEach(function (sId) {
                    perCol[i + 1].forEach(function (tId) {
                        var key = sId + "→" + tId;
                        var link = linkMap.get(key);
                        if (!link) { link = { source: sId, target: tId, value: 0, flowIds: new Set() }; linkMap.set(key, link); }
                        link.value += 1;
                        link.flowIds.add(f.id);
                    });
                });
            }
        });

        var nodes = Array.from(nodeMap.values());
        var index = new Map(nodes.map(function (n, i) { return [n.id, i]; }));
        var links = Array.from(linkMap.values()).map(function (l) {
            return { source: index.get(l.source), target: index.get(l.target), value: l.value, flowIds: l.flowIds };
        });
        return { nodes: nodes, links: links, flowsById: flowsById };
    }

    // =====================================================================================
    // Rendering
    // =====================================================================================
    function renderStats() {
        var flows = currentFlows();
        var model = pimState.snapshotIdx >= 0 ? pimModelForSnapshot(snapshots[pimState.snapshotIdx]) : null;
        $("pimStatRoles").textContent = model ? model.roleCount.toLocaleString() : "0";

        var roleIdsNoMfa = {}, roleIdsNoApproval = {}, roleIdsFlagged = {};
        flows.forEach(function (f) {
            var rid = f.roleId || f.roleName;
            if (f.flags.some(function (fl) { return fl.id === "noMfaActivation"; })) roleIdsNoMfa[rid] = true;
            if (f.flags.some(function (fl) { return fl.id === "noApprovalActivation"; })) roleIdsNoApproval[rid] = true;
            if (f.flags.length) roleIdsFlagged[rid] = true;
        });
        $("pimStatNoMfa").textContent = Object.keys(roleIdsNoMfa).length.toLocaleString();
        $("pimStatNoApproval").textContent = Object.keys(roleIdsNoApproval).length.toLocaleString();
        $("pimStatFlagged").textContent = Object.keys(roleIdsFlagged).length.toLocaleString();
        $("pimStatTierData").textContent = roleDefinitionTierIndex.size ? "loaded (" + roleDefinitionTierIndex.size + " role(s) classified)" : "not generated";
        document.querySelectorAll("[data-pim-metric]").forEach(function (tile) {
            var metric = tile.getAttribute("data-pim-metric");
            var selected = metric === "all" ? !pimState.flagFilter && pimState.metricFilter === "all" : (metric === "anyRisk" ? pimState.metricFilter === "anyRisk" : pimState.flagFilter === metric);
            tile.classList.toggle("selected", selected);
            tile.setAttribute("aria-pressed", String(selected));
        });
    }

    function renderControls() {
        var sel = $("pimSnapshot");
        var idxs = detailedSnapshotIdxs();
        var html = "";
        idxs.forEach(function (i) {
            html += '<option value="' + i + '"' + (i === pimState.snapshotIdx ? " selected" : "") + ">" + esc(snapshotLabel(snapshots[i], i)) + "</option>";
        });
        sel.innerHTML = html;

        var pathHtml = "";
        PATH_DEFS.forEach(function (pd) {
            pathHtml += '<span class="ca-toggle' + (pimState.pathFilter.has(pd.key) ? " on" : "") + '" role="button" tabindex="0" data-path="' + pd.key + '">' + esc(pd.shortLabel) + "</span>";
        });
        $("pimPathToggles").innerHTML = pathHtml;

        var colHtml = "";
        COLUMN_ORDER.forEach(function (c) {
            colHtml += '<span class="ca-toggle' + (pimState.columns.has(c) ? " on" : "") + '" role="button" tabindex="0" data-col="' + c + '">' + COLUMNS[c].label + "</span>";
        });
        $("pimColToggles").innerHTML = colHtml;

        var flows = currentFlows();
        var flags = {};
        flows.forEach(function (f) { f.flags.forEach(function (fl) { flags[fl.id] = fl.text.split(".")[0]; }); });
        var fHtml = '<option value="">All flags</option>';
        Object.keys(flags).sort().forEach(function (id) {
            fHtml += '<option value="' + esc(id) + '"' + (id === pimState.flagFilter ? " selected" : "") + ">" + esc(flags[id]) + "</option>";
        });
        $("pimFltFlag").innerHTML = fHtml;

        var reqs = {};
        flows.forEach(function (f) { f.requirements.forEach(function (r) { reqs[r] = true; }); });
        var rHtml = '<option value="">All requirements</option>';
        Object.keys(reqs).sort().forEach(function (r) {
            rHtml += '<option value="' + esc(r) + '"' + (r === pimState.requirementFilter ? " selected" : "") + ">" + esc(r) + "</option>";
        });
        $("pimFltRequirement").innerHTML = rHtml;
    }

    var pimSvg = null, pimTooltip = null, pimTraceFlowIds = null;

    function rolePermissions(roleDef) {
        if (!roleDef || !Array.isArray(roleDef.rolePermissions)) return [];
        return roleDef.rolePermissions.flatMap(function (permission) {
            if (typeof permission === "string") return [permission];
            return Array.isArray(permission.AllowedResourceActions) ? permission.AllowedResourceActions : [];
        });
    }

    function openNodeInspector(node, graph) {
        var flow = graph.flowsById.get(Array.from(node.flowIds)[0]);
        if (!flow) return;
        window.EntraOpsObjectInspector.open({
            title: node.name,
            tier: flow.roleTier,
            roleReference: flow.roleId,
            tags: node.tags,
            fields: [
                { label: "Flow column", value: COLUMNS[node.column].label },
                { label: "Role", value: flow.roleName },
                { label: "Role ID", value: flow.roleId },
                { label: "Assignment path", value: flow.pathLabel },
                { label: "Classified service", value: flow.roleTierService },
                { label: "Approval", value: flow.approvalLabel },
                { label: "Role description", value: flow.roleDef && flow.roleDef.description }
            ],
            apiPermissions: rolePermissions(flow.roleDef),
            related: Array.from(node.flowIds).map(function (id) {
                var relatedFlow = graph.flowsById.get(id);
                return { label: relatedFlow.roleName + " - " + relatedFlow.pathShortLabel, href: EntraOpsReportUtils.flowDeepLink(id) };
            })
        });
    }

    function renderSankey() {
        pimSvg = pimSvg || d3.select("#pimSankey");
        pimTooltip = pimTooltip || d3.select("#tooltip");
        var emptyEl = $("pimSankeyEmpty");
        var all = currentFlows();
        var flows = all.filter(flowMatchesFilters);
        if (pimState.traceNodeId) {
            flows = flows.filter(function (f) { return pimTraceFlowIds && pimTraceFlowIds.has(f.id); });
        }
        $("pimFreshness").textContent = EntraOpsReportUtils.freshnessText(DATA, snapshots[pimState.snapshotIdx]);
        $("pimFilterSummary").textContent = " · " + flows.length + " of " + all.length + " assignment path(s) shown";
        $("pimClearTrace").classList.toggle("hidden", !pimState.traceNodeId);

        renderStats();
        renderFlagsSummary(all);

        if (!all.length) {
            pimSvg.selectAll("*").remove();
            pimSvg.attr("height", 0);
            emptyEl.classList.remove("hidden");
            emptyEl.textContent = "No microsoft.entra.rolesetting resources with embedded content in this snapshot. Pick a snapshot marked with ✓ content, ensure microsoft.entra.roleSetting (and microsoft.entra.roleDefinition) are in TenantGovernanceSnapshot.ResourcesToInclude, or regenerate the dataset with a higher -MaxDetailedSnapshots.";
            return;
        }
        if (!flows.length || pimState.columns.size < 2) {
            pimSvg.selectAll("*").remove();
            pimSvg.attr("height", 0);
            emptyEl.classList.remove("hidden");
            emptyEl.textContent = pimState.columns.size < 2 ? "Select at least two columns to draw a flow." : "No PIM assignment paths match the current filters.";
            return;
        }
        emptyEl.classList.add("hidden");

        var graph = buildGraph(flows);
        var nodeCount = graph.nodes.length;

        var width = Math.max(960, document.querySelector("#secPimSankey .diagram-wrap").clientWidth - 48);
        var height = Math.max(480, nodeCount * 19);

        pimSvg.attr("width", width).attr("height", height);
        pimSvg.selectAll("*").remove();

        var sankey = d3.sankey().nodeWidth(14).nodePadding(9).extent([[8, 28], [width - 8, height - 8]]);
        var layout;
        try {
            layout = sankey({
                nodes: graph.nodes.map(function (d) { return Object.assign({}, d); }),
                links: graph.links.map(function (d) { return Object.assign({}, d); })
            });
        } catch (e) {
            emptyEl.classList.remove("hidden");
            emptyEl.textContent = "Unable to lay out the flow (possible cycle). Try different columns.";
            return;
        }
        var nodes = layout.nodes, links = layout.links;

        // Id-indexed lookup so the link mousemove handler doesn't scan all flows per pointer event.
        var allFlowsById = new Map();
        all.forEach(function (f) { allFlowsById.set(f.id, f); });

        function flowNamesFor(ids, limit) {
            var names = [];
            ids.forEach(function (id) { var f = allFlowsById.get(id); if (f) names.push(f.roleName + " – " + f.pathShortLabel); });
            var shown = names.slice(0, limit || 6).map(esc).join("<br/>");
            if (names.length > (limit || 6)) shown += "<br/>… and " + (names.length - (limit || 6)) + " more";
            return shown;
        }

        pimSvg.append("g").attr("class", "links")
            .selectAll("path").data(links).join("path")
            .attr("class", "link")
            .attr("d", d3.sankeyLinkHorizontal())
            .attr("stroke", "var(--viz-flow-link)")
            .attr("stroke-opacity", 0.32)
            .attr("stroke-width", function (d) { return Math.max(1, d.width); })
            .on("mousemove", function (ev, d) {
                pimTooltip.classed("hidden", false)
                    .style("left", (ev.clientX + 14) + "px").style("top", (ev.clientY + 14) + "px")
                    .html("<b>" + esc(d.source.name) + "</b> → <b>" + esc(d.target.name) + "</b><br/>" +
                        d.flowIds.size + " assignment path" + (d.flowIds.size === 1 ? "" : "s") + ":<br/>" + flowNamesFor(d.flowIds));
            })
            .on("mouseleave", function () { pimTooltip.classed("hidden", true); });

        var nodeSel = pimSvg.append("g").attr("class", "nodes")
            .selectAll("g").data(nodes).join("g").attr("class", "node");

        nodeSel.append("rect")
            .attr("x", function (d) { return d.x0; })
            .attr("y", function (d) { return d.y0; })
            .attr("width", function (d) { return d.x1 - d.x0; })
            .attr("height", function (d) { return Math.max(2, d.y1 - d.y0); })
            .attr("fill", function (d) { return nodeColor(d, graph.flowsById); })
            .attr("rx", 2)
            .on("mousemove", function (ev, d) {
                var extra = "";
                if (d.column === "path") {
                    var f = graph.flowsById.get(d.id.slice("path|".length));
                    if (f) {
                        extra = esc(f.roleName) + " – " + esc(f.pathShortLabel) +
                            (f.roleTier ? "<br/>Role tier: " + esc(f.roleTier) : "<br/>Role tier: Unclassified") +
                            "<br/>" + esc(f.approvalLabel) +
                            (f.flags.length ? "<br/>" + f.flags.map(function (fl) { return "⚠ " + esc(fl.text); }).join("<br/>") : "") +
                            "<br/><i>Click for full detail</i>";
                    }
                } else {
                    extra = (d.tier ? "Tier: " + esc(d.tier) + "<br/>" : "") +
                        (d.tags.length ? "<b>Tags:</b> " + d.tags.map(esc).join(", ") + "<br/>" : "") +
                        d.flowIds.size + " assignment path" + (d.flowIds.size === 1 ? "" : "s") +
                        "<br/><i>Click to trace this node</i>";
                }
                pimTooltip.classed("hidden", false)
                    .style("left", (ev.clientX + 14) + "px").style("top", (ev.clientY + 14) + "px")
                    .html("<b>" + esc(d.name) + "</b><br/>" + extra);
            })
            .on("mouseleave", function () { pimTooltip.classed("hidden", true); })
            .on("click", function (ev, d) {
                ev.stopPropagation();
                pimState.traceNodeId = d.id;
                pimTraceFlowIds = d.flowIds;
                if (d.column === "path") {
                    renderFlowDetail(d.id.slice("path|".length));
                } else {
                    $("pimFlowDetail").classList.add("hidden");
                }
                openNodeInspector(d, graph);
                renderSankey();
            });

        nodeSel.append("text")
            .attr("x", function (d) { return d.x0 < width / 2 ? d.x1 + 6 : d.x0 - 6; })
            .attr("y", function (d) { return (d.y0 + d.y1) / 2; })
            .attr("dy", "0.35em")
            .attr("text-anchor", function (d) { return d.x0 < width / 2 ? "start" : "end"; })
            .text(function (d) { return truncate(d.name, 42); })
            .each(function (d) {
                if (!d.tags.length) return;
                d3.select(this).append("tspan").attr("fill", "var(--viz-muted)").text(" ⓘ").append("title").text(d.tags.join("; "));
            })
            .filter(function (d) { return d.y1 - d.y0 < 8; })
            .remove();

        var colX = {};
        nodes.forEach(function (n) {
            if (!(n.column in colX)) colX[n.column] = [];
            colX[n.column].push((n.x0 + n.x1) / 2);
        });
        Object.keys(colX).forEach(function (c) {
            var cx = colX[c].reduce(function (a, b) { return a + b; }, 0) / colX[c].length;
            pimSvg.append("text").attr("x", cx).attr("y", 0).attr("dy", "0.8em").attr("text-anchor", "middle")
                .attr("font-size", 11).attr("font-weight", 600).attr("fill", "var(--viz-muted)")
                .text(COLUMNS[c].label.toUpperCase());
        });

        pimSvg.on("click", function () {
            if (pimState.traceNodeId) {
                pimState.traceNodeId = null;
                pimTraceFlowIds = null;
                $("pimFlowDetail").classList.add("hidden");
                renderSankey();
            }
        });
    }

    function renderFlowDetail(flowId) {
        var f = currentFlows().filter(function (x) { return x.id === flowId; })[0];
        var el = $("pimFlowDetail");
        if (!f) { el.classList.add("hidden"); return; }

        function list(title, items) {
            if (!items || !items.length) return "";
            return "<div style='margin-bottom:6px;'><b>" + esc(title) + ":</b> " + items.map(esc).join(" · ") + "</div>";
        }
        function tieredList(title, items) {
            if (!items || !items.length) return "";
            var html = items.map(function (it) {
                var chip = it.tier ? ' <span class="status-chip modified" style="background:' + tierColor(it.tier) + ';color:#fff;">' + esc(it.tier) + "</span>" : "";
                return esc(it.label) + chip;
            }).join(" · ");
            return "<div style='margin-bottom:6px;'><b>" + esc(title) + ":</b> " + html + "</div>";
        }

        var borderColor = f.flags.some(function (fl) { return fl.severity === "fail"; }) ? "#a4262c" : (f.flags.length ? "#8a6d00" : "#0e700e");
        var html = '<div class="card" style="border-left:4px solid ' + borderColor + ';">';
        html += '<div class="card-head">' + esc(f.roleName) + " – " + esc(f.pathShortLabel) +
            (f.roleTier ? ' <span class="status-chip modified" style="background:' + tierColor(f.roleTier) + ';color:#fff;">' + esc(f.roleTier) + "</span>" : ' <span class="status-chip modified" style="background:#a19f9d;color:#fff;">Unclassified</span>') +
            '<span class="chip ' + (f.approvalRequired ? "brand" : "warn") + '">' + esc(f.approvalLabel) + "</span></div>";
        html += '<div class="card-pad" style="font-size:13px;">';
        var pd = PATH_DEFS.filter(function (x) { return x.key === f.path; })[0];
        if (pd) html += "<p class='muted' style='margin-top:0;'>" + esc(pd.description) + "</p>";
        if (f.roleDef && f.roleDef.description) html += list("Role description", [f.roleDef.description]);
        if (f.roleTierService) html += list("Classified service", [f.roleTierService]);
        html += list("Requirement(s) to request", f.requirements);
        html += tieredList("Approver(s)", f.approvers);
        html += list("Notification(s)", f.notifications);
        html += list("Duration / expiration", [f.duration]);
        if (f.flags.length) {
            html += "<div style='margin-top:8px;'>" + f.flags.map(function (fl) {
                return '<div class="ca-gap-row"><span class="ca-gap-icon ' + (fl.severity === "fail" ? "fail" : "warn") + '">' + (fl.severity === "fail" ? "✕" : "!") + '</span><div class="ca-gap-detail">' + esc(fl.text) + "</div></div>";
            }).join("") + "</div>";
        }
        html += '<div class="muted" style="font-size:12px;margin-top:4px;">Source: <code>' + esc(f.resource.p) + "</code></div>";
        html += "</div></div>";
        el.innerHTML = html;
        el.classList.remove("hidden");
    }

    // =====================================================================================
    // Risk flags summary (mirrors the Access Package Flow / Conditional Access coverage lists)
    // =====================================================================================
    function renderFlagsSummary(flows) {
        var el = $("pimFlagsBody");
        if (!flows.length) { el.innerHTML = '<div class="muted">No microsoft.entra.rolesetting resources with embedded content in the selected snapshot.</div>'; return; }

        var flagged = flows.filter(function (f) { return f.flags.length > 0; });
        if (!flagged.length) {
            el.innerHTML = '<div class="ca-gap-row"><span class="ca-gap-icon ok">✓</span><div><div class="ca-gap-title">No risk flags found</div><div class="ca-gap-detail">Every privileged role in this snapshot requires MFA and approval to activate, has no unenforced approver configuration, and does not allow permanent privileged assignments.</div></div></div>';
            return;
        }

        var rows = [];
        flagged.forEach(function (f) {
            f.flags.forEach(function (fl) {
                rows.push({ flow: f, flag: fl, tier: f.roleTier || "Unclassified", service: f.roleTierService || "Unclassified / no service" });
            });
        });
        if (pimFlagState.search) {
            var query = pimFlagState.search.toLowerCase();
            rows = rows.filter(function (row) {
                return [row.flow.roleName, row.flow.pathLabel, row.tier, row.service, row.flag.text].join(" ").toLowerCase().indexOf(query) !== -1;
            });
        }
        if (!rows.length) {
            el.innerHTML = '<div class="muted">No risk flags match the current search.</div>';
            return;
        }
        rows.sort(function (a, b) {
            if (pimFlagState.sortBy === "severity") {
                var severityOrder = { fail: 0, warn: 1 };
                var severityDiff = severityOrder[a.flag.severity] - severityOrder[b.flag.severity];
                if (severityDiff) return severityDiff;
            } else if (pimFlagState.sortBy === "tier") {
                var tierDiff = tierRank(a.tier) - tierRank(b.tier);
                if (tierDiff) return tierDiff;
            } else if (pimFlagState.sortBy === "service") {
                var serviceDiff = a.service.localeCompare(b.service);
                if (serviceDiff) return serviceDiff;
            }
            return a.flow.roleName.localeCompare(b.flow.roleName) || a.flow.pathOrder - b.flow.pathOrder || a.flag.text.localeCompare(b.flag.text);
        });
        var groups = {};
        rows.forEach(function (row) {
            var key = pimFlagState.groupBy === "tier" ? row.tier : (pimFlagState.groupBy === "service" ? row.service : "All risk flags");
            if (!groups[key]) groups[key] = [];
            groups[key].push(row);
        });
        var html = "";
        var groupNames = Object.keys(groups).sort(function (a, b) {
            return pimFlagState.groupBy === "tier" ? tierRank(a) - tierRank(b) : a.localeCompare(b);
        });
        if (pimFlagState.collapseStateGroupBy !== pimFlagState.groupBy) {
            pimFlagState.collapsedGroups = new Set(groupNames);
            pimFlagState.collapseStateGroupBy = pimFlagState.groupBy;
        }
        groupNames.forEach(function (group) {
            var isCollapsed = pimFlagState.collapsedGroups.has(group);
            var groupId = "risk-group-" + pimFlagState.groupBy + "-" + group;
            var severityCounts = { fail: 0, warn: 0 };
            groups[group].forEach(function (row) { severityCounts[row.flag.severity]++; });
            var pills = (severityCounts.fail ? '<span class="pim-risk-stat-pill fail">&#10005; ' + severityCounts.fail + '</span>' : "") +
                (severityCounts.warn ? '<span class="pim-risk-stat-pill warn">! ' + severityCounts.warn + '</span>' : "");
            html += '<div class="pim-risk-area"><button type="button" class="pim-risk-group-head" data-risk-group="' + esc(group) + '" aria-expanded="' + (!isCollapsed) + '" aria-controls="' + esc(groupId) + '">' +
                '<span class="pim-risk-group-chevron" aria-hidden="true">' + (isCollapsed ? "&#9656;" : "&#9662;") + '</span><span class="pim-risk-group-title">' + esc(group) + '</span><span class="pim-risk-group-stats">' + pills + '</span></button>';
            html += '<div class="pim-risk-group-items' + (isCollapsed ? " hidden" : "") + '" id="' + esc(groupId) + '">';
            groups[group].forEach(function (row) {
                var f = row.flow, fl = row.flag;
                var metadata = f.pathShortLabel + ' · ' + row.tier + ' · ' + row.service;
                html += '<div class="ca-gap-row"><span class="ca-gap-icon ' + (fl.severity === "fail" ? "fail" : "warn") + '">' + (fl.severity === "fail" ? "✕" : "!") + '</span>' +
                    '<div><div class="ca-gap-title">' + esc(f.roleName) + ' <span class="muted" style="font-size:11px;">(' + esc(metadata) + ')</span> ' + EntraOpsReportUtils.reviewControl("pim-request-flow", f.id + "|" + fl.id) + '</div>' +
                    '<div class="ca-gap-detail">' + esc(fl.text) + ' · <a href="../ConfigurationAnalyzer/index.html?view=resources#resource=' + pimState.snapshotIdx + "|" + encodeURIComponent(f.resource.p) + '">Inspect source resource</a></div></div></div>';
            });
            html += "</div></div>";
        });
        html += '<p class="muted" style="font-size:12px;margin-top:10px;">Role tiers come from the generated Classification Explorer catalog and captured role actions. The optional EAM Dashboard dataset adds tenant-specific assignment evidence.</p>';
        el.innerHTML = html;
        EntraOpsReportUtils.bindReviewControls(el);
    }

    function applyFlowDeepLink() {
        var flowId = EntraOpsReportUtils.flowReferenceFromHash();
        if (!flowId) return;
        var flow = currentFlows().filter(function (item) { return item.id === flowId; })[0];
        if (!flow) {
            var previousIdx = pimState.snapshotIdx;
            var detailIdxs = detailedSnapshotIdxs();
            for (var index = detailIdxs.length - 1; index >= 0 && !flow; index--) {
                pimState.snapshotIdx = detailIdxs[index];
                flow = currentFlows().filter(function (item) { return item.id === flowId; })[0];
            }
            if (flow) renderControls();
            else pimState.snapshotIdx = previousIdx;
        }
        if (!flow) return;
        pimState.traceNodeId = "path|" + flowId;
        pimTraceFlowIds = new Set([flowId]);
        renderSankey();
        renderFlowDetail(flowId);
        $("secPimSankey").scrollIntoView({ block: "start" });
    }

    // =====================================================================================
    // Wiring + init
    // =====================================================================================
    function onReady(fn) {
        if (document.readyState !== "loading") fn();
        else document.addEventListener("DOMContentLoaded", fn);
    }

    onReady(function () {
        var navToggle = $("navToggle");
        var nav = $("nav");
        if (navToggle && nav) navToggle.addEventListener("click", function () { nav.classList.toggle("open"); });
        document.querySelectorAll(".nav-item.section-item").forEach(function (item) {
            item.addEventListener("click", function () {
                var target = document.getElementById(item.getAttribute("data-target"));
                if (target) target.scrollIntoView({ behavior: "smooth", block: "start" });
                if (nav) nav.classList.remove("open");
            });
            item.addEventListener("keydown", function (ev) {
                if (ev.key !== "Enter" && ev.key !== " ") return;
                ev.preventDefault();
                item.click();
            });
        });

        if (!DATA || !snapshots.length) return; // empty state stays visible

        $("pimEmptyState").classList.add("hidden");
        $("pimContent").classList.remove("hidden");

        var detailIdxs = detailedSnapshotIdxs();
        if (detailIdxs.length) pimState.snapshotIdx = detailIdxs[detailIdxs.length - 1];

        renderControls();
        renderSankey();
        window.addEventListener("hashchange", applyFlowDeepLink);
        applyFlowDeepLink();

        $("pimSnapshot").addEventListener("change", function () {
            pimState.snapshotIdx = Number(this.value);
            pimState.traceNodeId = null;
            pimTraceFlowIds = null;
            pimState.approvalFilter = "";
            pimState.flagFilter = "";
            pimState.requirementFilter = "";
            $("pimFltApproval").value = "";
            $("pimFlowDetail").classList.add("hidden");
            renderControls();
            renderSankey();
        });
        function toggleKeydown(ev) {
            if (ev.key !== "Enter" && ev.key !== " ") return;
            var t = ev.target.closest(".ca-toggle");
            if (!t) return;
            ev.preventDefault();
            t.click();
        }
        $("pimPathToggles").addEventListener("keydown", toggleKeydown);
        $("pimColToggles").addEventListener("keydown", toggleKeydown);
        $("pimPathToggles").addEventListener("click", function (ev) {
            var t = ev.target.closest("[data-path]");
            if (!t) return;
            var k = t.getAttribute("data-path");
            if (pimState.pathFilter.has(k)) {
                if (pimState.pathFilter.size <= 1) return;
                pimState.pathFilter.delete(k);
            } else pimState.pathFilter.add(k);
            pimState.traceNodeId = null;
            pimTraceFlowIds = null;
            renderControls();
            renderSankey();
        });
        $("pimColToggles").addEventListener("click", function (ev) {
            var t = ev.target.closest("[data-col]");
            if (!t) return;
            var c = t.getAttribute("data-col");
            if (pimState.columns.has(c)) {
                if (pimState.columns.size <= 2) return;
                pimState.columns.delete(c);
            } else pimState.columns.add(c);
            pimState.traceNodeId = null;
            pimTraceFlowIds = null;
            renderControls();
            renderSankey();
        });
        $("pimFltTier").addEventListener("change", function () { pimState.tierFilter = this.value; renderSankey(); });
        $("pimFltApproval").addEventListener("change", function () { pimState.approvalFilter = this.value; renderSankey(); });
        $("pimFltFlag").addEventListener("change", function () { pimState.flagFilter = this.value; pimState.metricFilter = "all"; renderSankey(); });
        $("pimFltRequirement").addEventListener("change", function () { pimState.requirementFilter = this.value; renderSankey(); });
        document.querySelectorAll("[data-pim-metric]").forEach(function (tile) {
            tile.addEventListener("click", function () {
                var metric = tile.getAttribute("data-pim-metric");
                if (metric === "all" || (metric === "anyRisk" && pimState.metricFilter === "anyRisk") || (metric !== "anyRisk" && pimState.flagFilter === metric && pimState.metricFilter === "all")) {
                    pimState.flagFilter = "";
                    pimState.metricFilter = "all";
                } else if (metric === "anyRisk") {
                    pimState.flagFilter = "";
                    pimState.metricFilter = "anyRisk";
                } else {
                    pimState.flagFilter = metric;
                    pimState.metricFilter = "all";
                }
                pimState.traceNodeId = null;
                pimTraceFlowIds = null;
                renderControls();
                renderSankey();
            });
        });
        $("pimFlagGroup").addEventListener("change", function () { pimFlagState.groupBy = this.value; renderFlagsSummary(currentFlows()); });
        $("pimFlagSort").addEventListener("change", function () { pimFlagState.sortBy = this.value; renderFlagsSummary(currentFlows()); });
        $("pimFlagsBody").addEventListener("click", function (ev) {
            var groupHead = ev.target.closest("[data-risk-group]");
            if (!groupHead) return;
            var group = groupHead.getAttribute("data-risk-group");
            if (pimFlagState.collapsedGroups.has(group)) pimFlagState.collapsedGroups.delete(group);
            else pimFlagState.collapsedGroups.add(group);
            renderFlagsSummary(currentFlows());
        });
        $("pimExpandAllRiskGroups").addEventListener("click", function () {
            pimFlagState.collapsedGroups.clear();
            renderFlagsSummary(currentFlows());
        });
        $("pimCollapseAllRiskGroups").addEventListener("click", function () {
            var groups = new Set();
            currentFlows().forEach(function (flow) {
                flow.flags.forEach(function () {
                    groups.add(pimFlagState.groupBy === "tier" ? (flow.roleTier || "Unclassified") : (pimFlagState.groupBy === "service" ? (flow.roleTierService || "Unclassified / no service") : "All risk flags"));
                });
            });
            pimFlagState.collapsedGroups = groups;
            renderFlagsSummary(currentFlows());
        });
        var flagSearchTimer = null;
        $("pimFlagSearch").addEventListener("input", function () {
            var value = this.value;
            clearTimeout(flagSearchTimer);
            flagSearchTimer = setTimeout(function () { pimFlagState.search = value.trim(); renderFlagsSummary(currentFlows()); }, 180);
        });
        var searchTimer = null;
        $("pimFltSearch").addEventListener("input", function () {
            var v = this.value;
            clearTimeout(searchTimer);
            searchTimer = setTimeout(function () { pimState.search = v.trim(); renderSankey(); }, 180);
        });
        $("pimClearTrace").addEventListener("click", function () {
            pimState.traceNodeId = null;
            pimTraceFlowIds = null;
            $("pimFlowDetail").classList.add("hidden");
            renderSankey();
        });
        $("pimResetFilters").addEventListener("click", function () {
            pimState.pathFilter = new Set(PATH_DEFS.map(function (path) { return path.key; }));
            pimState.tierFilter = "";
            pimState.approvalFilter = "";
            pimState.flagFilter = "";
            pimState.metricFilter = "all";
            pimState.requirementFilter = "";
            pimState.search = "";
            pimState.traceNodeId = null;
            pimTraceFlowIds = null;
            $("pimFltTier").value = "";
            $("pimFltApproval").value = "";
            $("pimFltSearch").value = "";
            $("pimFlagSearch").value = "";
            pimFlagState.search = "";
            $("pimFlowDetail").classList.add("hidden");
            renderControls();
            renderSankey();
        });
        $("pimExportFiltered").addEventListener("click", function () {
            var rows = currentFlows().filter(flowMatchesFilters).map(function (flow) {
                return { snapshot: snapshotLabel(snapshots[pimState.snapshotIdx], pimState.snapshotIdx), role: flow.roleName, path: flow.pathLabel, accessLevel: flow.roleTier || "Unclassified", approval: flow.approvalLabel, requirements: flow.requirements.join("; "), riskFlags: flow.flags.map(function (flag) { return flag.id; }).join("; ") };
            });
            EntraOpsReportUtils.exportRows("entraops-pim-request-flow-filtered", rows);
        });
        $("pimExportRiskFlags").addEventListener("click", function () {
            var query = pimFlagState.search.toLowerCase();
            var rows = [];
            currentFlows().forEach(function (flow) {
                flow.flags.forEach(function (flag) {
                    var tier = flow.roleTier || "Unclassified", service = flow.roleTierService || "Unclassified / no service";
                    if (query && [flow.roleName, flow.pathLabel, tier, service, flag.text].join(" ").toLowerCase().indexOf(query) === -1) return;
                    rows.push({ snapshot: snapshotLabel(snapshots[pimState.snapshotIdx], pimState.snapshotIdx), role: flow.roleName, path: flow.pathLabel, accessLevel: tier, service: service, severity: flag.severity, flag: flag.id, detail: flag.text, sourceResource: flow.resource.p });
                });
            });
            EntraOpsReportUtils.exportRows("entraops-pim-request-risk-flags", rows);
        });
    });
})();
