/*
 * EntraOps Conditional Access Analysis
 *
 * Visualizes the Conditional Access policy set of any detailed EntraOps Tenant Governance
 * snapshot (see Reports/ConfigurationAnalyzer, generated by
 * New-EntraOpsTenantGovernanceConfigurationAnalyzerData) as a filterable Sankey flow
 * (Assignments -> Policy -> Target resources -> Network -> Conditions -> Grant controls),
 * plus heuristic Conditional Access coverage gap checks.
 *
 * Reuses the snapshot/blob parsing model + Conditional Access policy parsing from
 * ../ConfigurationAnalyzer/js/core.js (loaded before this file - see index.html). EIDSCA
 * coverage now lives in its own app (Reports/EidscaCoverage).
 */
(function () {
    "use strict";

    var excludedFindingIds = new Set((DATA && Array.isArray(DATA.conditionalAccessAnalysisExcludedFindings) ? DATA.conditionalAccessAnalysisExcludedFindings : []).map(String));
    var caCoverageChecks = [];

    var caState = {
        snapshotIdx: -1,
        columns: new Set(["assignment", "policy", "target", "network", "condition", "grant"]),
        states: new Set(["enabled", "reportOnly", "disabled"]),
        metricFilter: "all",
        grantFilter: "",
        clientAppFilter: "",
        assignmentFilter: "",
        assignmentTierFilter: "",
        targetFilter: "",
        networkFilter: "",
        conditionFilter: "",
        search: "",
        traceNodeId: null
    };

    var COLUMN_ORDER = ["assignment", "policy", "target", "network", "condition", "grant"];
    var COLUMNS = {
        assignment: { label: "Assignments", values: function (p) { return p.assignments; } },
        policy: { label: "Policy", values: function (p) { return [p.name]; } },
        target: { label: "Target resources", values: function (p) { return p.targets; } },
        network: { label: "Network", values: function (p) { return p.network; } },
        condition: { label: "Conditions", values: function (p) { return p.conditions; } },
        grant: { label: "Grant controls", values: function (p) { return p.grants; } }
    };

    var STATE_LABELS = { enabled: "Enabled", reportOnly: "Report-only", disabled: "Disabled" };
    var STATE_COLORS = { enabled: "#0e700e", reportOnly: "#8a6d00", disabled: "#a19f9d" };

    var roleTierIndex = new Map();
    if (EAM_DATA && Array.isArray(EAM_DATA.objects)) {
        EAM_DATA.objects.forEach(function (object) {
            (object.roleAssignments || []).forEach(function (assignment) {
                var tiers = (assignment.classification || []).map(function (classification) { return classification.adminTierLevelName; }).filter(Boolean);
                [assignment.roleDefinitionId, assignment.roleDefinitionName].forEach(function (key) {
                    if (!key) return;
                    var normalized = String(key).toUpperCase();
                    if (!roleTierIndex.has(normalized)) roleTierIndex.set(normalized, new Set());
                    tiers.forEach(function (tier) { roleTierIndex.get(normalized).add(tier); });
                });
            });
        });
    }

    function assignmentTierDetails(policy) {
        if (policy.assignmentTierDetails) return policy.assignmentTierDetails;
        var details = [], seen = {};
        function add(label, tier) {
            if (!tier || seen[label + "|" + tier]) return;
            seen[label + "|" + tier] = true;
            details.push({ label: label, tier: tier });
        }
        arr(policy.raw.IncludeUsers).forEach(function (user) {
            if (user !== "All" && user !== "None" && user !== "GuestsOrExternalUsers") add("User: " + user, identityTierFor(user));
        });
        arr(policy.raw.IncludeGroups).forEach(function (group) { add("Group: " + group, identityTierFor(group)); });
        arr(policy.raw.IncludeRoles).forEach(function (role) {
            var tiers = roleTierIndex.get(String(role).toUpperCase());
            if (tiers) tiers.forEach(function (tier) { add("Role: " + role, tier); });
        });
        policy.assignmentTierDetails = details;
        return details;
    }

    function currentCaPolicies() {
        if (caState.snapshotIdx < 0) return [];
        return caPoliciesForSnapshot(snapshots[caState.snapshotIdx]);
    }

    function renderStats(policies) {
        $("caStatPolicies").textContent = policies.length.toLocaleString();
        $("caStatEnabled").textContent = policies.filter(function (policy) { return policy.state === "enabled"; }).length.toLocaleString();
        $("caStatReportOnly").textContent = policies.filter(function (policy) { return policy.state === "reportOnly"; }).length.toLocaleString();
        $("caStatDisabled").textContent = policies.filter(function (policy) { return policy.state === "disabled"; }).length.toLocaleString();
        document.querySelectorAll("[data-ca-metric]").forEach(function (tile) {
            var selected = tile.getAttribute("data-ca-metric") === caState.metricFilter;
            tile.classList.toggle("selected", selected);
            tile.setAttribute("aria-pressed", String(selected));
        });
    }

    function policyMatchesFilters(p) {
        if (caState.metricFilter !== "all" && p.state !== caState.metricFilter) return false;
        if (!caState.states.has(p.state)) return false;
        if (caState.grantFilter && p.grants.indexOf(caState.grantFilter) === -1) return false;
        if (caState.clientAppFilter) {
            var covers = p.clientAppTypes.indexOf("all") !== -1 || p.clientAppTypes.indexOf(caState.clientAppFilter) !== -1;
            if (!covers) return false;
        }
        if (caState.assignmentFilter && p.assignments.indexOf(caState.assignmentFilter) === -1) return false;
        if (caState.assignmentTierFilter && !assignmentTierDetails(p).some(function (detail) { return detail.tier === caState.assignmentTierFilter; })) return false;
        if (caState.targetFilter && p.targets.indexOf(caState.targetFilter) === -1) return false;
        if (caState.networkFilter && p.network.indexOf(caState.networkFilter) === -1) return false;
        if (caState.conditionFilter && p.conditions.indexOf(caState.conditionFilter) === -1) return false;
        if (caState.search) {
            var q = caState.search.toLowerCase();
            var hay = [p.name].concat(p.assignments, p.targets, p.network, p.conditions, p.grants, p.exclusions).join("   ").toLowerCase();
            if (hay.indexOf(q) === -1) return false;
        }
        return true;
    }

    function nodeId(col, label, policy) {
        // Policy nodes are unique per policy (two policies may share a display name);
        // aspect nodes are shared across policies so common scopes merge visually.
        return col === "policy" ? "policy|" + policy.id : col + "|" + label;
    }

    function linkColor(link) {
        // Strongest signal wins across the policies sharing this link.
        if (link.states.enabled) {
            if (link.grantKinds.block) return "#a4262c";
            if (link.grantKinds.grant) return "#0e700e";
            if (link.grantKinds.session) return "#0078d4";
            return "#a19f9d";
        }
        if (link.states.reportOnly) return "#8a6d00";
        return "#a19f9d";
    }

    function nodeColor(n) {
        if (n.column === "policy") return STATE_COLORS[n.policyState] || "#0078d4";
        if (n.column === "grant") {
            if (n.name === "Block access") return "#a4262c";
            if (n.name === "Session controls only") return "#0078d4";
            if (n.name === "No control (monitor only)") return "#a19f9d";
            return "#0e700e";
        }
        var palette = { assignment: "#5c2d91", target: "#0078d4", network: "#038387", condition: "#c07807" };
        return palette[n.column] || "#605e5c";
    }

    function buildCaGraph(policies) {
        var activeCols = COLUMN_ORDER.filter(function (c) { return caState.columns.has(c); });
        var nodeMap = new Map();
        var linkMap = new Map();

        function ensureNode(col, label, policy) {
            var id = nodeId(col, label, policy);
            if (!nodeMap.has(id)) {
                nodeMap.set(id, {
                    id: id, name: label, column: col,
                    policyState: col === "policy" ? policy.state : null,
                    policyIds: new Set(), value: 0, tags: []
                });
            }
            // Every node in the assignment/target columns is inherently a Conditional Access
            // assignment/target - this whole report is about CA policies, so tagging that would
            // just restate the column header on every single node. Only flag policies that carry
            // exclusions, a real distinguishing fact not obvious from the diagram alone.
            if (col === "policy" && policy.exclusions.length && nodeMap.get(id).tags.indexOf("Conditional Access Exclusion") === -1) {
                nodeMap.get(id).tags.push("Conditional Access Exclusion");
            }
            nodeMap.get(id).policyIds.add(policy.id);
            return id;
        }

        policies.forEach(function (p) {
            var perCol = activeCols.map(function (c) {
                return COLUMNS[c].values(p).map(function (label) { return ensureNode(c, label, p); });
            });
            for (var i = 0; i < perCol.length - 1; i++) {
                perCol[i].forEach(function (sId) {
                    perCol[i + 1].forEach(function (tId) {
                        var key = sId + "→" + tId;
                        var link = linkMap.get(key);
                        if (!link) {
                            link = { source: sId, target: tId, value: 0, policyIds: new Set(), states: {}, grantKinds: {} };
                            linkMap.set(key, link);
                        }
                        link.value += 1;
                        link.policyIds.add(p.id);
                        link.states[p.state] = true;
                        link.grantKinds[p.grantKind] = true;
                    });
                });
            }
        });

        var nodes = Array.from(nodeMap.values());
        var index = new Map(nodes.map(function (n, i) { return [n.id, i]; }));
        var links = Array.from(linkMap.values()).map(function (l) {
            return {
                source: index.get(l.source), target: index.get(l.target), value: l.value,
                policyIds: l.policyIds, states: l.states, grantKinds: l.grantKinds
            };
        });
        return { nodes: nodes, links: links };
    }

    function detailedSnapshotOptions() {
        return detailedSnapshotIdxs();
    }

    function renderCaControls() {
        // Snapshot picker (detailed snapshots only)
        var sel = $("caSnapshot");
        var idxs = detailedSnapshotOptions();
        var html = "";
        idxs.forEach(function (i) {
            html += '<option value="' + i + '"' + (i === caState.snapshotIdx ? " selected" : "") + ">" + esc(snapshotLabel(snapshots[i], i)) + "</option>";
        });
        sel.innerHTML = html;

        // State toggles
        var stHtml = "";
        ["enabled", "reportOnly", "disabled"].forEach(function (s) {
            stHtml += '<span class="ca-toggle' + (caState.states.has(s) ? " on" : "") + '" role="button" tabindex="0" data-state="' + s + '">' + STATE_LABELS[s] + "</span>";
        });
        $("caStateToggles").innerHTML = stHtml;

        // Column toggles
        var colHtml = "";
        COLUMN_ORDER.forEach(function (c) {
            colHtml += '<span class="ca-toggle' + (caState.columns.has(c) ? " on" : "") + '" role="button" tabindex="0" data-col="' + c + '">' + COLUMNS[c].label + "</span>";
        });
        $("caColToggles").innerHTML = colHtml;

        // Grant filter options (from the current snapshot's policy set)
        var grants = {};
        currentCaPolicies().forEach(function (p) { p.grants.forEach(function (g) { grants[g] = true; }); });
        var gHtml = '<option value="">All grant controls</option>';
        Object.keys(grants).sort().forEach(function (g) {
            gHtml += '<option value="' + esc(g) + '"' + (g === caState.grantFilter ? " selected" : "") + ">" + esc(g) + "</option>";
        });
        $("caFltGrant").innerHTML = gHtml;

        var cHtml = '<option value="">All client app types</option>';
        ["browser", "mobileAppsAndDesktopClients", "exchangeActiveSync", "other"].forEach(function (c) {
            cHtml += '<option value="' + c + '"' + (c === caState.clientAppFilter ? " selected" : "") + ">" + esc(CLIENT_APP_LABELS[c]) + "</option>";
        });
        $("caFltClientApp").innerHTML = cHtml;

        // Per-column value filters (Assignment / Target resource / Network / Condition):
        // distinct values pulled from the current snapshot's policy set, same pattern as
        // the grant control filter above.
        var colFilters = [
            { id: "caFltAssignment", col: "assignment", empty: "All assignments", stateKey: "assignmentFilter" },
            { id: "caFltTarget", col: "target", empty: "All target resources", stateKey: "targetFilter" },
            { id: "caFltNetwork", col: "network", empty: "All networks", stateKey: "networkFilter" },
            { id: "caFltCondition", col: "condition", empty: "All conditions", stateKey: "conditionFilter" }
        ];
        colFilters.forEach(function (cf) {
            var values = {};
            currentCaPolicies().forEach(function (p) { COLUMNS[cf.col].values(p).forEach(function (v) { values[v] = true; }); });
            var html = '<option value="">' + cf.empty + '</option>';
            Object.keys(values).sort().forEach(function (v) {
                html += '<option value="' + esc(v) + '"' + (v === caState[cf.stateKey] ? " selected" : "") + ">" + esc(v) + "</option>";
            });
            $(cf.id).innerHTML = html;
        });
    }

    var caSvg = null, caTooltip = null, tracePolicyIds = null;

    function openNodeInspector(node, policies) {
        var relatedPolicies = policies.filter(function (policy) { return node.policyIds.has(policy.id); });
        var policy = relatedPolicies[0];
        var assignmentDetail = policy && assignmentTierDetails(policy).filter(function (detail) { return detail.label === node.name; })[0];
        var roleReference = null;
        if (policy && node.column === "assignment") {
            (policy.raw.IncludeRoles || []).some(function (role) {
                if (node.name === "Role: " + role || node.name === String(role)) { roleReference = role; return true; }
                return false;
            });
        }
        var assignmentReference = /^(User|Group):\s*/.test(node.name) ? node.name.replace(/^(User|Group):\s*/, "") : null;
        var canonicalReference = window.EntraOpsObjectInspector.canonicalReference(assignmentReference);
        var policyFields = node.column === "policy" && policy ? [
            { section: "General", label: "Policy ID", value: policy.id },
            { section: "General", label: "State", value: STATE_LABELS[policy.state] },
            { section: "General", label: "Source path", value: policy.resource && policy.resource.p },
            { section: "Assignments", label: "Included identities", value: policy.assignments.join("; ") },
            { section: "Assignments", label: "Exclusions", value: policy.exclusions.join("; ") },
            { section: "Target resources", label: "Applications and actions", value: policy.targets.join("; ") },
            { section: "Conditions", label: "Network", value: policy.network.join("; ") },
            { section: "Conditions", label: "Conditions", value: policy.conditions.join("; ") },
            { section: "Controls", label: "Grant operator", value: policy.grantOperator },
            { section: "Controls", label: "Grant controls", value: policy.grants.join("; ") },
            { section: "Controls", label: "Session controls", value: policy.sessionControls.join("; ") }
        ] : [
            { label: "Flow column", value: COLUMNS[node.column].label },
            { label: "Role ID", value: roleReference }
        ];
        window.EntraOpsObjectInspector.open({
            title: node.name,
            reference: assignmentReference,
            urlReference: canonicalReference,
            updateUrl: !!canonicalReference,
            tier: assignmentDetail && assignmentDetail.tier,
            roleReference: roleReference,
            tags: node.tags,
            fallbackUserAccess: !!assignmentDetail && assignmentDetail.tier === "UserAccess",
            fields: policyFields,
            apiPermissions: node.column === "target" ? [node.name] : [],
            related: relatedPolicies.map(function (item) {
                return { label: item.name, href: EntraOpsReportUtils.flowDeepLink(item.id) };
            })
        });
    }

    function renderSankey() {
        caSvg = caSvg || d3.select("#sankey");
        caTooltip = caTooltip || d3.select("#tooltip");
        var emptyEl = $("sankeyEmpty");
        var all = currentCaPolicies();
        var policies = all.filter(policyMatchesFilters);
        renderStats(all);
        $("caFreshness").textContent = EntraOpsReportUtils.freshnessText(DATA, snapshots[caState.snapshotIdx]);
        $("caFilterSummary").textContent = " · " + policies.length + " of " + all.length + " policy path(s) shown";
        if (caState.traceNodeId) {
            policies = policies.filter(function (p) {
                return tracePolicyIds && tracePolicyIds.has(p.id);
            });
        }
        $("caClearTrace").classList.toggle("hidden", !caState.traceNodeId);

        if (!all.length) {
            caSvg.selectAll("*").remove();
            caSvg.attr("height", 0);
            emptyEl.classList.remove("hidden");
            emptyEl.textContent = "No Conditional Access policies with embedded content in this snapshot. Pick a snapshot marked with ✓ content, or regenerate the dataset with a higher -MaxDetailedSnapshots.";
            renderGaps(all);
            return;
        }
        renderGaps(all);

        if (!policies.length || caState.columns.size < 2) {
            caSvg.selectAll("*").remove();
            caSvg.attr("height", 0);
            emptyEl.classList.remove("hidden");
            emptyEl.textContent = caState.columns.size < 2 ? "Select at least two columns to draw a flow." : "No policies match the current filters.";
            return;
        }
        emptyEl.classList.add("hidden");

        var graph = buildCaGraph(policies);
        var nodeCount = graph.nodes.length;
        var width = Math.max(960, document.querySelector("#secSankey .diagram-wrap").clientWidth - 48);
        var height = Math.max(480, nodeCount * 19);

        caSvg.attr("width", width).attr("height", height);
        caSvg.selectAll("*").remove();

        var sankey = d3.sankey().nodeWidth(14).nodePadding(9)
            .extent([[8, 28], [width - 8, height - 8]]);

        var layout;
        try {
            layout = sankey({
                nodes: graph.nodes.map(function (d) { return Object.assign({}, d); }),
                links: graph.links.map(function (d) { return Object.assign({}, d); })
            });
        } catch (e) {
            emptyEl.classList.remove("hidden");
            emptyEl.textContent = "Unable to lay out the flow (possible cycle). Try different columns.";
            return;
        }

        var nodes = layout.nodes, links = layout.links;

        // Id-indexed lookups so the mousemove handlers below don't scan the policy list
        // per pointer event.
        var policiesById = new Map();
        all.forEach(function (p) { policiesById.set(p.id, p); });

        function policyNamesFor(ids, limit) {
            var names = [];
            ids.forEach(function (id) { var p = policiesById.get(id); if (p) names.push(p.name); });
            var shown = names.slice(0, limit || 6).map(esc).join("<br/>");
            if (names.length > (limit || 6)) shown += "<br/>… and " + (names.length - (limit || 6)) + " more";
            return shown;
        }

        caSvg.append("g").attr("class", "links")
            .selectAll("path").data(links).join("path")
            .attr("class", "link")
            .attr("d", d3.sankeyLinkHorizontal())
            .attr("stroke", function (d) { return linkColor(d); })
            .attr("stroke-opacity", 0.38)
            .attr("stroke-dasharray", function (d) { return (!d.states.enabled && d.states.reportOnly) ? "6,3" : null; })
            .attr("stroke-width", function (d) { return Math.max(1, d.width); })
            .on("mousemove", function (ev, d) {
                caTooltip.classed("hidden", false)
                    .style("left", (ev.clientX + 14) + "px").style("top", (ev.clientY + 14) + "px")
                    .html("<b>" + esc(d.source.name) + "</b> → <b>" + esc(d.target.name) + "</b><br/>" +
                        d.policyIds.size + " polic" + (d.policyIds.size === 1 ? "y" : "ies") + ":<br/>" + policyNamesFor(d.policyIds));
            })
            .on("mouseleave", function () { caTooltip.classed("hidden", true); });

        var nodeSel = caSvg.append("g").attr("class", "nodes")
            .selectAll("g").data(nodes).join("g").attr("class", "node");

        nodeSel.append("rect")
            .attr("x", function (d) { return d.x0; })
            .attr("y", function (d) { return d.y0; })
            .attr("width", function (d) { return d.x1 - d.x0; })
            .attr("height", function (d) { return Math.max(2, d.y1 - d.y0); })
            .attr("fill", function (d) { return nodeColor(d); })
            .attr("rx", 2)
            .on("mousemove", function (ev, d) {
                var extra = "";
                if (d.column === "policy") {
                    var pol = policiesById.get(String(d.id).slice("policy|".length));
                    if (pol) {
                        extra = STATE_LABELS[pol.state] +
                            (pol.grantOperator && pol.grants.length > 1 ? " · grant operator: " + esc(pol.grantOperator) : "") +
                            (pol.exclusions.length ? "<br/>" + pol.exclusions.length + " exclusion(s)" : "") +
                            (pol.sessionControls.length ? "<br/>Session: " + esc(pol.sessionControls.join(", ")) : "") +
                            "<br/><i>Click to trace &amp; open details</i>";
                    }
                } else {
                    extra = (d.tags.length ? "<b>Tags:</b> " + d.tags.map(esc).join(", ") + "<br/>" : "") +
                        d.policyIds.size + " polic" + (d.policyIds.size === 1 ? "y" : "ies") + "<br/><i>Click to trace this node</i>";
                }
                caTooltip.classed("hidden", false)
                    .style("left", (ev.clientX + 14) + "px").style("top", (ev.clientY + 14) + "px")
                    .html("<b>" + esc(d.name) + "</b><br/>" + extra);
            })
            .on("mouseleave", function () { caTooltip.classed("hidden", true); })
            .on("click", function (ev, d) {
                ev.stopPropagation();
                caState.traceNodeId = d.id;
                tracePolicyIds = d.policyIds;
                if (d.column === "policy") renderPolicyDetail(d.id.slice("policy|".length));
                else $("caPolicyDetail").classList.add("hidden");
                openNodeInspector(d, all);
                renderSankey();
            });

        nodeSel.append("text")
            .attr("x", function (d) { return d.x0 < width / 2 ? d.x1 + 6 : d.x0 - 6; })
            .attr("y", function (d) { return (d.y0 + d.y1) / 2; })
            .attr("dy", "0.35em")
            .attr("text-anchor", function (d) { return d.x0 < width / 2 ? "start" : "end"; })
            .text(function (d) { return truncate(d.name, 42); })
            .each(function (d) {
                if (!d.tags.length) return;
                d3.select(this).append("tspan").attr("fill", "var(--viz-muted)").text(" ⓘ").append("title").text(d.tags.join("; "));
            })
            .filter(function (d) { return d.y1 - d.y0 < 8; })
            .remove();

        // Column headers
        var colX = {};
        nodes.forEach(function (n) {
            if (!(n.column in colX)) colX[n.column] = [];
            colX[n.column].push((n.x0 + n.x1) / 2);
        });
        Object.keys(colX).forEach(function (c) {
            var cx = colX[c].reduce(function (a, b) { return a + b; }, 0) / colX[c].length;
            caSvg.append("text").attr("x", cx).attr("y", 0).attr("dy", "0.8em").attr("text-anchor", "middle")
                .attr("font-size", 11).attr("font-weight", 600).attr("fill", "var(--viz-muted)")
                .text(COLUMNS[c].label.toUpperCase());
        });

        // Clicking the empty background clears an active trace
        caSvg.on("click", function () {
            if (caState.traceNodeId) {
                caState.traceNodeId = null;
                tracePolicyIds = null;
                $("caPolicyDetail").classList.add("hidden");
                renderSankey();
            }
        });
    }

    function renderPolicyDetail(policyId) {
        var pol = currentCaPolicies().filter(function (p) { return p.id === policyId; })[0];
        var el = $("caPolicyDetail");
        if (!pol) { el.classList.add("hidden"); return; }
        function list(title, items) {
            if (!items || !items.length) return "";
            return "<div style='margin-bottom:6px;'><b>" + esc(title) + ":</b> " + items.map(esc).join(" · ") + "</div>";
        }
        var html = '<div class="card" style="border-left:4px solid ' + (STATE_COLORS[pol.state] || "#0078d4") + ';">';
        html += '<div class="card-head">' + esc(pol.name) + '<span class="chip ' + (pol.state === "enabled" ? "brand" : "warn") + '">' + STATE_LABELS[pol.state] + "</span></div>";
        html += '<div class="card-pad" style="font-size:13px;">';
        html += list("Assignments", pol.assignments);
        html += list("Assignment access levels", assignmentTierDetails(pol).map(function (detail) { return detail.label + " (" + detail.tier + ")"; }));
        html += list("Excluded", pol.exclusions);
        html += list("Target resources", pol.targets);
        html += list("Network", pol.network);
        html += list("Conditions", pol.conditions);
        html += list("Grant controls" + (pol.grants.length > 1 && pol.grantOperator ? " (" + pol.grantOperator + ")" : ""), pol.grants);
        html += list("Session controls", pol.sessionControls);
        html += '<div class="muted" style="font-size:12px;margin-top:4px;">Source: <code>' + esc(pol.resource.p) + "</code></div>";
        html += "</div></div>";
        el.innerHTML = html;
        el.classList.remove("hidden");
    }

    // =====================================================================================
    // Conditional Access coverage gap checks (heuristics over the parsed policy set)
    // =====================================================================================
    function renderGaps(policies) {
        var el = $("gapsBody");
        if (!policies.length) {
            el.innerHTML = '<div class="muted">No Conditional Access policies with embedded content in the selected snapshot.</div>';
            return;
        }
        var enabled = policies.filter(function (p) { return p.state === "enabled"; });
        var reportOnly = policies.filter(function (p) { return p.state === "reportOnly"; });
        var disabled = policies.filter(function (p) { return p.state === "disabled"; });

        function names(list, max) {
            var n = list.map(function (p) { return p.name; });
            var out = n.slice(0, max || 5).join(", ");
            if (n.length > (max || 5)) out += ", … (+" + (n.length - (max || 5)) + ")";
            return out;
        }
        function hasControl(p) { return p.grantKind === "block" || p.grantKind === "grant"; }
        function requiresMfa(p) {
            return p.grants.some(function (g) { return g === "Require MFA" || g.indexOf("Auth strength:") === 0; });
        }
        function requiresDevice(p) {
            return p.grants.some(function (g) { return g === "Require compliant device" || g === "Require hybrid joined device"; });
        }

        var checks = [];

        // 1. Policies not enforced
        checks.push({
            id: "policyNotEnforced",
            status: (reportOnly.length + disabled.length) === 0 ? "ok" : "warn",
            title: "All policies enforced",
            detail: (reportOnly.length + disabled.length) === 0
                ? "Every Conditional Access policy is enabled."
                : reportOnly.length + " report-only (" + names(reportOnly) + ") and " + disabled.length + " disabled (" + names(disabled) + ") policies create access paths without enforced controls."
        });

        // 2. Legacy authentication blocked
        var legacyBlockers = enabled.filter(function (p) {
            var legacy = p.clientAppTypes.indexOf("exchangeActiveSync") !== -1 || p.clientAppTypes.indexOf("other") !== -1;
            return legacy && p.grantKind === "block";
        });
        checks.push({
            id: "legacyAuthentication",
            status: legacyBlockers.length ? "ok" : "fail",
            title: "Legacy authentication blocked",
            detail: legacyBlockers.length
                ? "Blocked by: " + names(legacyBlockers) + "."
                : "No enabled policy blocks legacy client apps (Exchange ActiveSync / other clients). Legacy protocols bypass MFA - this is a common uncovered access path."
        });

        // 3. MFA for all users on all resources
        var allUserMfa = enabled.filter(function (p) {
            return p.includesAllUsers && p.includesAllApps && requiresMfa(p);
        });
        var allUserMfaExclusions = allUserMfa.reduce(function (acc, p) { return acc + p.exclusions.length; }, 0);
        checks.push({
            id: "allUserMfa",
            status: allUserMfa.length ? (allUserMfaExclusions > 0 ? "warn" : "ok") : "fail",
            title: "MFA (or authentication strength) required for all users on all resources",
            detail: allUserMfa.length
                ? "Covered by: " + names(allUserMfa) + (allUserMfaExclusions ? ". Note: " + allUserMfaExclusions + " exclusion(s) across these policies - each excluded user/group/role is an access path without this MFA requirement." : ".")
                : "No enabled policy targets all users on all resources with an MFA/authentication strength requirement."
        });

        // 4. Privileged roles covered
        var roleTargeted = enabled.filter(function (p) { return p.includedRoles.length && (requiresMfa(p) || requiresDevice(p) || p.grantKind === "block"); });
        checks.push({
            id: "privilegedRoleControls",
            status: roleTargeted.length ? "ok" : (allUserMfa.length ? "warn" : "fail"),
            title: "Dedicated controls for privileged (directory role) assignments",
            detail: roleTargeted.length
                ? "Role-targeted policies: " + names(roleTargeted) + "."
                : (allUserMfa.length
                    ? "No role-targeted policy found - privileged accounts only inherit the general all-user coverage. Consider phishing-resistant authentication strength and device requirements for admin roles."
                    : "No enabled policy targets directory roles with MFA/device/block controls - privileged access paths have no dedicated Conditional Access coverage.")
        });

        // 5. Risk-based policies
        var signInRisk = enabled.filter(function (p) { return p.signInRiskLevels.length && hasControl(p); });
        var userRisk = enabled.filter(function (p) { return p.userRiskLevels.length && hasControl(p); });
        checks.push({
            id: "riskBasedPolicies",
            status: (signInRisk.length && userRisk.length) ? "ok" : ((signInRisk.length || userRisk.length) ? "warn" : "fail"),
            title: "Risk-based policies (Identity Protection)",
            detail: "Sign-in risk: " + (signInRisk.length ? names(signInRisk) : "not covered") +
                " · User risk: " + (userRisk.length ? names(userRisk) : "not covered") + "."
        });

        // 6. Device-based controls
        var deviceControls = enabled.filter(requiresDevice);
        checks.push({
            id: "deviceControls",
            status: deviceControls.length ? "ok" : "warn",
            title: "Device compliance / hybrid join required somewhere",
            detail: deviceControls.length
                ? "Device-based controls in: " + names(deviceControls) + "."
                : "No enabled policy requires a compliant or hybrid-joined device."
        });

        // 7. Guest coverage
        var guestPolicies = enabled.filter(function (p) {
            return p.assignments.indexOf("Guests / external users") !== -1 && hasControl(p);
        });
        checks.push({
            id: "guestCoverage",
            status: guestPolicies.length ? "ok" : "warn",
            title: "Guest / external user coverage",
            detail: guestPolicies.length
                ? "Guest-targeted policies: " + names(guestPolicies) + "."
                : "No enabled policy explicitly targets guests/external users with a control."
        });

        // 8. Client app type coverage by all-user policies
        var uncoveredClientApps = ["browser", "mobileAppsAndDesktopClients", "exchangeActiveSync", "other"].filter(function (c) {
            return !enabled.some(function (p) {
                if (!p.includesAllUsers || !hasControl(p)) return false;
                return p.clientAppTypes.indexOf("all") !== -1 || p.clientAppTypes.indexOf(c) !== -1;
            });
        });
        checks.push({
            id: "clientAppCoverage",
            status: uncoveredClientApps.length === 0 ? "ok" : "warn",
            title: "Every client app type covered for all users",
            detail: uncoveredClientApps.length === 0
                ? "All client app types are covered by at least one enabled all-user policy with a control."
                : "No enabled all-user policy with a control covers: " + uncoveredClientApps.map(function (c) { return CLIENT_APP_LABELS[c]; }).join(", ") + " - sign-ins via these clients are an access path without Conditional Access coverage."
        });

        // 9. Exclusion surface
        var exclusionCount = {};
        policies.forEach(function (p) {
            p.exclusions.forEach(function (e) {
                if (!exclusionCount[e]) exclusionCount[e] = 0;
                exclusionCount[e]++;
            });
        });
        var topExclusions = Object.keys(exclusionCount).sort(function (a, b) { return exclusionCount[b] - exclusionCount[a]; }).slice(0, 8);
        checks.push({
            id: "exclusionSurface",
            status: topExclusions.length ? "warn" : "ok",
            title: "Exclusion surface",
            detail: topExclusions.length
                ? "Most frequently excluded: " + topExclusions.map(function (e) { return e + " (" + exclusionCount[e] + "×)"; }).join(", ") + ". Every exclusion is an access path outside the policy - verify emergency access accounts are monitored."
                : "No exclusions configured across the policy set."
        });

        checks = checks.filter(function (check) { return !excludedFindingIds.has(check.id); });
        caCoverageChecks = checks.slice();
        var icons = { ok: "✓", warn: "!", fail: "✕" };
        var html = "";
        checks.forEach(function (c) {
            html += '<div class="ca-gap-row">' +
                '<span class="ca-gap-icon ' + c.status + '">' + icons[c.status] + "</span>" +
                '<div><div class="ca-gap-title">' + esc(c.title) + " " + EntraOpsReportUtils.reviewControl("conditional-access-analysis", c.id) + "</div>" +
                '<div class="ca-gap-detail">' + esc(c.detail) + "</div></div></div>";
        });
        html += '<p class="muted" style="font-size:12px;margin-top:10px;">Heuristic checks computed only from the captured Conditional Access policy set of the selected snapshot - they cannot see users, apps or sign-in activity outside the policies. Treat "ok" as a starting point, not as proof of coverage.</p>';
        el.innerHTML = html;
        EntraOpsReportUtils.bindReviewControls(el);
    }

    function applyFlowDeepLink() {
        var policyId = EntraOpsReportUtils.flowReferenceFromHash();
        if (!policyId) return;
        var policy = currentCaPolicies().filter(function (item) { return item.id === policyId; })[0];
        if (!policy) {
            var previousIdx = caState.snapshotIdx;
            var detailIdxs = detailedSnapshotOptions();
            for (var index = detailIdxs.length - 1; index >= 0 && !policy; index--) {
                caState.snapshotIdx = detailIdxs[index];
                policy = currentCaPolicies().filter(function (item) { return item.id === policyId; })[0];
            }
            if (policy) renderCaControls();
            else caState.snapshotIdx = previousIdx;
        }
        if (!policy) return;
        caState.traceNodeId = "policy|" + policyId;
        tracePolicyIds = new Set([policyId]);
        renderSankey();
        renderPolicyDetail(policyId);
        $("secSankey").scrollIntoView({ block: "start" });
    }

    // =====================================================================================
    // Wiring + init
    // =====================================================================================
    function onReady(fn) {
        if (document.readyState !== "loading") fn();
        else document.addEventListener("DOMContentLoaded", fn);
    }

    onReady(function () {
        var navToggle = $("navToggle");
        var nav = $("nav");
        if (navToggle && nav) {
            navToggle.addEventListener("click", function () { nav.classList.toggle("open"); });
        }
        document.querySelectorAll(".nav-item.section-item").forEach(function (item) {
            item.addEventListener("click", function () {
                var target = document.getElementById(item.getAttribute("data-target"));
                if (target) target.scrollIntoView({ behavior: "smooth", block: "start" });
                if (nav) nav.classList.remove("open");
            });
            item.addEventListener("keydown", function (ev) {
                if (ev.key !== "Enter" && ev.key !== " ") return;
                ev.preventDefault();
                item.click();
            });
        });

        if (!DATA || !snapshots.length) return; // empty state stays visible

        $("caEmptyState").classList.add("hidden");
        $("caContent").classList.remove("hidden");

        var detailIdxs = detailedSnapshotOptions();
        if (detailIdxs.length) {
            caState.snapshotIdx = detailIdxs[detailIdxs.length - 1];
        }
        renderCaControls();
        renderSankey();
        window.addEventListener("hashchange", applyFlowDeepLink);
        applyFlowDeepLink();

        $("caSnapshot").addEventListener("change", function () {
            caState.snapshotIdx = Number(this.value);
            caState.traceNodeId = null;
            tracePolicyIds = null;
            caState.grantFilter = "";
            caState.clientAppFilter = "";
            caState.assignmentFilter = "";
            caState.assignmentTierFilter = "";
            caState.targetFilter = "";
            caState.networkFilter = "";
            caState.conditionFilter = "";
            $("caFltAssignmentTier").value = "";
            $("caPolicyDetail").classList.add("hidden");
            renderCaControls();
            renderSankey();
        });
        function toggleKeydown(ev) {
            if (ev.key !== "Enter" && ev.key !== " ") return;
            var t = ev.target.closest(".ca-toggle");
            if (!t) return;
            ev.preventDefault();
            t.click();
        }
        $("caStateToggles").addEventListener("keydown", toggleKeydown);
        $("caColToggles").addEventListener("keydown", toggleKeydown);
        $("caStateToggles").addEventListener("click", function (ev) {
            var t = ev.target.closest("[data-state]");
            if (!t) return;
            var s = t.getAttribute("data-state");
            if (caState.states.has(s)) caState.states.delete(s); else caState.states.add(s);
            renderCaControls();
            renderSankey();
        });
        $("caColToggles").addEventListener("click", function (ev) {
            var t = ev.target.closest("[data-col]");
            if (!t) return;
            var c = t.getAttribute("data-col");
            if (caState.columns.has(c)) {
                if (caState.columns.size <= 2) return; // keep at least two columns
                caState.columns.delete(c);
            } else caState.columns.add(c);
            caState.traceNodeId = null;
            tracePolicyIds = null;
            renderCaControls();
            renderSankey();
        });
        $("caFltGrant").addEventListener("change", function () { caState.grantFilter = this.value; renderSankey(); });
        $("caFltClientApp").addEventListener("change", function () { caState.clientAppFilter = this.value; renderSankey(); });
        $("caFltAssignment").addEventListener("change", function () { caState.assignmentFilter = this.value; renderSankey(); });
        $("caFltAssignmentTier").addEventListener("change", function () { caState.assignmentTierFilter = this.value; renderSankey(); });
        $("caFltTarget").addEventListener("change", function () { caState.targetFilter = this.value; renderSankey(); });
        $("caFltNetwork").addEventListener("change", function () { caState.networkFilter = this.value; renderSankey(); });
        $("caFltCondition").addEventListener("change", function () { caState.conditionFilter = this.value; renderSankey(); });
        document.querySelectorAll("[data-ca-metric]").forEach(function (tile) {
            tile.addEventListener("click", function () {
                var metric = tile.getAttribute("data-ca-metric");
                caState.metricFilter = caState.metricFilter === metric || metric === "all" ? "all" : metric;
                // A metric tile filters on a policy state - make sure that state toggle is on,
                // otherwise the state filter would immediately hide every matching policy.
                if (caState.metricFilter !== "all") caState.states.add(caState.metricFilter);
                caState.traceNodeId = null;
                tracePolicyIds = null;
                renderCaControls();
                renderSankey();
            });
        });
        var searchTimer = null;
        $("caFltSearch").addEventListener("input", function () {
            var v = this.value;
            clearTimeout(searchTimer);
            searchTimer = setTimeout(function () { caState.search = v.trim(); renderSankey(); }, 180);
        });
        $("caClearTrace").addEventListener("click", function () {
            caState.traceNodeId = null;
            tracePolicyIds = null;
            $("caPolicyDetail").classList.add("hidden");
            renderSankey();
        });
        $("caResetFilters").addEventListener("click", function () {
            caState.states = new Set(["enabled", "reportOnly", "disabled"]);
            caState.metricFilter = "all";
            caState.grantFilter = "";
            caState.clientAppFilter = "";
            caState.assignmentFilter = "";
            caState.assignmentTierFilter = "";
            caState.targetFilter = "";
            caState.networkFilter = "";
            caState.conditionFilter = "";
            caState.search = "";
            caState.traceNodeId = null;
            tracePolicyIds = null;
            $("caFltAssignmentTier").value = "";
            $("caFltSearch").value = "";
            $("caPolicyDetail").classList.add("hidden");
            renderCaControls();
            renderSankey();
        });
        $("caExportFiltered").addEventListener("click", function () {
            var rows = currentCaPolicies().filter(policyMatchesFilters).map(function (policy) {
                return { snapshot: snapshotLabel(snapshots[caState.snapshotIdx], caState.snapshotIdx), policy: policy.name, state: STATE_LABELS[policy.state], assignments: policy.assignments.join("; "), targets: policy.targets.join("; "), grants: policy.grants.join("; "), conditions: policy.conditions.join("; "), exclusions: policy.exclusions.join("; ") };
            });
            EntraOpsReportUtils.exportRows("entraops-conditional-access-filtered", rows);
        });
        $("caExportCoverageGaps").addEventListener("click", function () {
            var snapshot = snapshots[caState.snapshotIdx];
            EntraOpsReportUtils.exportRows("entraops-conditional-access-coverage-gaps", caCoverageChecks.map(function (check) {
                return { snapshot: snapshotLabel(snapshot, caState.snapshotIdx), finding: check.id, status: check.status, title: check.title, detail: check.detail };
            }));
        });
    });
})();
